"""
Lorentzian KNN strategy — Python port of TradingView's most popular ML indicator.

This module implements a strategy that uses a Lorentzian distance‑based k‑nearest‑neighbors
classifier to generate buy/sell signals. The classifier is trained on historical price
features generated by :func:`app.ml.models.lorentzian_knn.compute_lorentzian_features`.  The
strategy applies several filters (confidence, direction confirmation, and a 20‑period SMA
price filter) before emitting a :class:`app.strategies.base.Signal`.

The implementation follows the pattern used by other strategies in the codebase:
* Lazy in‑memory model construction.
* Asynchronous ``analyze`` entry point for live trading.
* ``backtest_signals`` for historical performance evaluation.

Only docstrings and type annotations are added; the underlying logic remains unchanged.
"""

import logging
import time
from typing import Any, Dict, List, Optional

import numpy as np
import pandas as pd

from app.ml.models.lorentzian_knn import (
    LORENTZIAN_FEATURES,
    LorentzianKNN,
    compute_lorentzian_features,
)
from app.strategies.base import AbstractStrategy, BacktestSignals, Signal

logger = logging.getLogger(__name__)


class LorentzianStrategy(AbstractStrategy):
    """
    Lorentzian K‑Nearest‑Neighbors classification strategy.

    Attributes
    ----------
    name : str
        Internal identifier used by the platform.
    display_name : str
        Human‑readable name shown in UI components.
    market_type : str
        The market category this strategy is intended for (e.g., ``"equity"``).
    strategy_type : str
        Classification of the strategy; here it is ``"ml_enhanced"``.
    risk_bucket : str
        Risk bucket label for portfolio construction.
    tick_interval_seconds : float
        Expected data tick interval.
    confidence_threshold : float
        Minimum confidence required (0‑1) before a signal is emitted.
    """

    name = "lorentzian_knn"
    display_name = "Lorentzian Classification (ML)"
    market_type = "equity"
    strategy_type = "ml_enhanced"
    risk_bucket = "directional"
    tick_interval_seconds = 300.0
    confidence_threshold = 0.65

    def __init__(self, params: Optional[Dict[str, Any]] = None):
        """
        Initialise the strategy with optional hyper‑parameters.

        Parameters
        ----------
        params : dict | None, optional
            Dictionary of hyper‑parameters. Supported keys are:

            * ``"k"`` – Number of neighbours for KNN (default ``8``).
            * ``"lookback"`` – Historical look‑back period for feature generation
              (default ``2000``).
            * ``"subsample"`` – Sub‑sampling interval for incremental library updates
              (default ``4``).
        """
        super().__init__(params)
        self.k: int = params.get("k", 8) if params else 8
        self.lookback: int = params.get("lookback", 2000) if params else 2000
        self.subsample: int = params.get("subsample", 4) if params else 4
        self._model: Optional[LorentzianKNN] = None
        self._signal_counter: int = 0

    def _get_or_build_model(self, df: pd.DataFrame) -> LorentzianKNN:
        """
        Lazily build (or retrieve) the Lorentzian KNN model from a DataFrame.

        The model is constructed only once per strategy instance. Historical price data
        is transformed into features, and the resulting feature matrix together with the
        forward‑looking binary labels (price up = 1, else 0) are used to populate the
        KNN library.

        Parameters
        ----------
        df : pd.DataFrame
            Historical OHLCV data. Must contain a ``"close"`` column.

        Returns
        -------
        LorentzianKNN
            A fully‑trained KNN model ready for inference.
        """
        if self._model is None:
            self._model = LorentzianKNN(k=self.k, lookback=self.lookback, subsample=self.subsample)
            feat_df = compute_lorentzian_features(df)
            features = feat_df[LORENTZIAN_FEATURES].fillna(0).values
            # Label: 1 if price goes up next bar
            labels = (df["close"].shift(-1) > df["close"]).astype(int).values
            self._model.fit_library(features[:-1], labels[:-1])
        return self._model

    async def analyze(self, data: pd.DataFrame, symbol: str) -> Optional[Signal]:
        """
        Generate a live trading signal based on the latest market data.

        The method extracts the most recent feature vector, computes the probability of a
        bullish move, and applies a series of filters (confidence, direction
        confirmation, and SMA‑20 price filter). If all criteria are satisfied, a
        :class:`Signal` object is returned; otherwise ``None`` is returned.

        Parameters
        ----------
        data : pd.DataFrame
            Recent market data for the target symbol. Must contain a ``"close"`` column.
        symbol : str
            Ticker symbol for which the signal is being generated.

        Returns
        -------
        Signal | None
            A populated :class:`Signal` if a trade signal is generated; otherwise ``None``.
        """
        start_time = time.perf_counter()
        if len(data) < 50:
            logger.info(
                "analyze_skipped",
                extra={
                    "symbol": symbol,
                    "reason": "insufficient_data",
                    "execution_time_ms": (time.perf_counter() - start_time) * 1000,
                },
            )
            return None

        model = self._get_or_build_model(data)
        feat_df = compute_lorentzian_features(data)
        features = feat_df[LORENTZIAN_FEATURES].fillna(0).values

        # Latest feature vector
        latest_features = features[-1:].astype(np.float32)
        # Previous feature vector for confirmation (if available)
        prev_features = features[-2:-1].astype(np.float32) if len(features) >= 2 else None

        import torch

        x_latest = torch.tensor(latest_features, dtype=torch.float32)
        prob = float(model.forward(x_latest).item())
        confidence = abs(prob - 0.5) * 2

        if confidence < self.confidence_threshold:
            logger.info(
                "analyze_no_signal",
                extra={
                    "symbol": symbol,
                    "confidence": confidence,
                    "threshold": self.confidence_threshold,
                    "execution_time_ms": (time.perf_counter() - start_time) * 1000,
                },
            )
            return None

        # Confirmation filter: previous probability must agree with direction
        if prev_features is not None:
            x_prev = torch.tensor(prev_features, dtype=torch.float32)
            prev_prob = float(model.forward(x_prev).item())
            direction_consistent = (prob > 0.5 and prev_prob > 0.5) or (
                prob < 0.5 and prev_prob < 0.5
            )
            if not direction_consistent:
                logger.info(
                    "analyze_no_signal",
                    extra={
                        "symbol": symbol,
                        "reason": "direction_not_confirmed",
                        "execution_time_ms": (time.perf_counter() - start_time) * 1000,
                    },
                )
                return None

        # Price filter: align with 20‑period SMA
        sma20 = data["close"].rolling(window=20).mean().iloc[-1]
        price = data["close"].iloc[-1]
        if np.isnan(sma20):
            logger.info(
                "analyze_no_signal",
                extra={
                    "symbol": symbol,
                    "reason": "sma_not_available",
                    "execution_time_ms": (time.perf_counter() - start_time) * 1000,
                },
            )
            return None

        if prob > 0.5:
            if price <= sma20:
                logger.info(
                    "analyze_no_signal",
                    extra={
                        "symbol": symbol,
                        "reason": "price_below_sma",
                        "execution_time_ms": (time.perf_counter() - start_time) * 1000,
                    },
                )
                return None
            direction = "long"
        else:
            if price >= sma20:
                logger.info(
                    "analyze_no_signal",
                    extra={
                        "symbol": symbol,
                        "reason": "price_above_sma",
                        "execution_time_ms": (time.perf_counter() - start_time) * 1000,
                    },
                )
                return None
            direction = "short"

        # Construct the signal
        signal = Signal(
            symbol=symbol,
            direction=direction,
            confidence=confidence,
            timestamp=data.index[-1],
        )

        # Monitoring: increment counter and log key metrics
        self._signal_counter += 1
        exec_time_ms = (time.perf_counter() - start_time) * 1000
        logger.info(
            "signal_generated",
            extra={
                "symbol": symbol,
                "direction": direction,
                "confidence": confidence,
                "signal_count": self._signal_counter,
                "execution_time_ms": exec_time_ms,
                "pnl_estimate": 0.0,  # Live signal – P&L will be realized later
            },
        )
        return signal

    def backtest_signals(self, data: pd.DataFrame) -> BacktestSignals:
        """
        Run the strategy over historical data to generate signals and compute performance.

        Parameters
        ----------
        data : pd.DataFrame
            Historical OHLCV data for backtesting.

        Returns
        -------
        BacktestSignals
            Container holding generated signals and performance metrics.
        """
        start_time = time.perf_counter()
        model = self._get_or_build_model(data)
        feat_df = compute_lorentzian_features(data)
        features = feat_df[LORENTZIAN_FEATURES].fillna(0).values

        signals: List[Signal] = []
        for i in range(1, len(data)):
            latest_features = features[i : i + 1].astype(np.float32)
            prev_features = features[i - 1 : i].astype(np.float32)

            import torch

            x_latest = torch.tensor(latest_features, dtype=torch.float32)
            prob = float(model.forward(x_latest).item())
            confidence = abs(prob - 0.5) * 2

            if confidence < self.confidence_threshold:
                continue

            # Direction confirmation
            x_prev = torch.tensor(prev_features, dtype=torch.float32)
            prev_prob = float(model.forward(x_prev).item())
            if not ((prob > 0.5 and prev_prob > 0.5) or (prob < 0.5 and prev_prob < 0.5)):
                continue

            # SMA filter
            window = 20
            if i < window:
                continue
            sma20 = data["close"].iloc[i - window + 1 : i + 1].mean()
            price = data["close"].iloc[i]
            if np.isnan(sma20):
                continue

            if prob > 0.5 and price <= sma20:
                direction = "long"
            elif prob <= 0.5 and price >= sma20:
                direction = "short"
            else:
                continue

            signal = Signal(
                symbol=data["symbol"].iloc[i] if "symbol" in data.columns else "UNKNOWN",
                direction=direction,
                confidence=confidence,
                timestamp=data.index[i],
            )
            signals.append(signal)

        # Compute P&L from generated signals (simple next‑bar return approximation)
        pnl = 0.0
        for sig in signals:
            idx = data.index.get_loc(sig.timestamp)
            if idx + 1 >= len(data):
                continue
            next_price = data["close"].iloc[idx + 1]
            cur_price = data["close"].iloc[idx]
            if sig.direction == "long":
                pnl += (next_price - cur_price) / cur_price
            else:
                pnl += (cur_price - next_price) / cur_price

        exec_time_ms = (time.perf_counter() - start_time) * 1000
        logger.info(
            "backtest_completed",
            extra={
                "signal_count": len(signals),
                "execution_time_ms": exec_time_ms,
                "total_pnl": pnl,
            },
        )
        return BacktestSignals(signals=signals, total_pnl=pnl, execution_time_ms=exec_time_ms)