"""ML-filtered breakout strategy."""

import pandas as pd

from app.ml.inference import get_inference_service
from app.strategies.base import AbstractStrategy, BacktestSignals, Signal
from app.strategies.manual.breakout import BreakoutStrategy


class MLBreakoutStrategy(AbstractStrategy):
    """Combine a traditional breakout signal with an ML filter."""

    name = "ml_breakout"
    display_name = "ML Breakout (Volume + Ensemble)"
    market_type = "equity"
    strategy_type = "ml_enhanced"
    risk_bucket = "directional"
    tick_interval_seconds = 900.0

    def __init__(self, params: dict | None = None):
        """
        Initialise the ML‑enhanced breakout strategy.

        Parameters
        ----------
        params : dict | None
            Configuration parameters forwarded to the underlying breakout strategy.
        """
        super().__init__(params)
        self._base = BreakoutStrategy(params)

    async def analyze(self, data: pd.DataFrame, symbol: str) -> Signal | None:
        """
        Generate a signal by first applying the base breakout logic and then
        filtering it through an ML model.

        Parameters
        ----------
        data : pd.DataFrame
            Historical price/volume data for the symbol.
        symbol : str
            Ticker symbol.

        Returns
        -------
        Signal | None
            The filtered signal, or ``None`` if the base strategy does not produce one.
        """
        base_signal = await self._base.analyze(data, symbol)
        if not base_signal:
            return None

        try:
            inference = get_inference_service()
            ml_result = await inference.predict(data, symbol)

            if (
                ml_result
                and ml_result["confidence"] > 0.65
                and ml_result["prediction"] == "up"
            ):
                # Blend confidence scores, capping at 0.92.
                blended_confidence = (base_signal.confidence + ml_result["confidence"]) / 2
                base_signal.confidence = min(0.92, blended_confidence)
                base_signal.strategy_name = self.name
                base_signal.strategy_type = self.strategy_type
                return base_signal
        except Exception:
            # If ML inference fails, fall back to the base signal.
            return base_signal

        return None

    def backtest_signals(self, df: pd.DataFrame) -> BacktestSignals:
        """
        Proxy backtesting to the underlying breakout strategy.

        Parameters
        ----------
        df : pd.DataFrame
            Historical data for backtesting.

        Returns
        -------
        BacktestSignals
            Signals generated by the base breakout strategy.
        """
        return self._base.backtest_signals(df)