"""ML-filtered breakout strategy.

This module defines :class:`MLBreakoutStrategy`, which enhances a traditional
breakout strategy with a machine‑learning inference step. The ML model provides
additional confidence signals based on recent market data. If the model predicts
an upward move with sufficient confidence, the base breakout signal is
adjusted accordingly.
"""

import pandas as pd
from app.strategies.base import AbstractStrategy, Signal, BacktestSignals
from app.strategies.manual.breakout import BreakoutStrategy
from app.ml.inference import get_inference_service


class MLBreakoutStrategy(AbstractStrategy):
    """A breakout strategy augmented with machine‑learning inference.

    Attributes
    ----------
    name : str
        Internal identifier for the strategy.
    display_name : str
        Human‑readable name shown in UI or logs.
    market_type : str
        Type of market this strategy applies to (e.g., ``"equity"``).
    strategy_type : str
        Category of the strategy, indicating it uses ML enhancements.
    risk_bucket : str
        Risk classification used for portfolio allocation.
    tick_interval_seconds : float
        Desired time interval between ticks for the strategy.
    """

    name = "ml_breakout"
    display_name = "ML Breakout (Volume + Ensemble)"
    market_type = "equity"
    strategy_type = "ml_enhanced"
    risk_bucket = "directional"
    tick_interval_seconds = 900.0

    def __init__(self, params: dict | None = None) -> None:
        """Create a new ``MLBreakoutStrategy`` instance.

        Parameters
        ----------
        params : dict | None, optional
            Optional configuration dictionary passed to the underlying
            :class:`BreakoutStrategy`. If ``None``, default parameters are used.
        """
        super().__init__(params)
        self._base = BreakoutStrategy(params)

    async def analyze(self, data: pd.DataFrame, symbol: str) -> Signal | None:
        """Generate a trading signal using both the base breakout logic and ML inference.

        The method first obtains a signal from the underlying breakout strategy.
        If a signal is produced, it queries the ML inference service. When the ML
        model predicts an upward movement with confidence greater than ``0.65``,
        the base signal's confidence is blended with the ML confidence (capped at
        ``0.92``) and the strategy metadata is updated.

        Parameters
        ----------
        data : pd.DataFrame
            Historical market data required by both the breakout and ML models.
        symbol : str
            Ticker symbol for which the signal is being generated.

        Returns
        -------
        Signal | None
            The adjusted signal if the ML model agrees, the original base signal
            on inference failure, or ``None`` if the base strategy does not emit a
            signal.
        """
        base_signal = await self._base.analyze(data, symbol)
        if not base_signal:
            return None
        try:
            inference = get_inference_service()
            ml_result = await inference.predict(data, symbol)
            if (
                ml_result
                and ml_result["confidence"] > 0.65
                and ml_result["prediction"] == "up"
            ):
                base_signal.confidence = min(
                    0.92, (base_signal.confidence + ml_result["confidence"]) / 2
                )
                base_signal.strategy_name = self.name
                base_signal.strategy_type = self.strategy_type
                return base_signal
        except Exception:
            return base_signal
        return None

    def backtest_signals(self, df: pd.DataFrame) -> BacktestSignals:
        """Delegate back‑testing to the underlying breakout strategy.

        Parameters
        ----------
        df : pd.DataFrame
            Dataframe containing historical price data for back‑testing.

        Returns
        -------
        BacktestSignals
            Signals generated by the base breakout strategy for the supplied data.
        """
        return self._base.backtest_signals(df)