"""ML-filtered mean reversion strategy.

This module defines :class:`MLMeanReversionStrategy`, which augments the classic
mean‑reversion logic with a machine‑learning filter. The ML model is consulted
to validate the direction suggested by the base mean‑reversion strategy,
reducing false signals while preserving the original risk and execution
characteristics.

The strategy is intended for equity markets and operates on 5‑minute (300‑second)
bars.
"""

from __future__ import annotations

import pandas as pd
from typing import Any, Dict, Optional

from app.strategies.base import AbstractStrategy, Signal, BacktestSignals
from app.strategies.manual.mean_reversion import MeanReversionStrategy
from app.ml.inference import get_inference_service


class MLMeanReversionStrategy(AbstractStrategy):
    """Mean‑reversion strategy enhanced with an ML filter.

    Attributes
    ----------
    name : str
        Internal identifier used by the platform.
    display_name : str
        Human‑readable name shown in UI components.
    market_type : str
        Market category (e.g., ``"equity"``).
    strategy_type : str
        Classification indicating an ML‑enhanced approach.
    risk_bucket : str
        Risk categorisation for portfolio allocation.
    tick_interval_seconds : float
        Expected interval between data ticks (5‑minute bars).
    """

    name = "ml_mean_reversion"
    display_name = "ML Mean Reversion (BB + ML Filter)"
    market_type = "equity"
    strategy_type = "ml_enhanced"
    risk_bucket = "directional"
    tick_interval_seconds = 300.0

    def __init__(self, params: Optional[Dict[str, Any]] = None) -> None:
        """Create a new ML‑enhanced mean‑reversion strategy.

        Parameters
        ----------
        params : dict | None, optional
            Strategy configuration parameters passed to the underlying
            :class:`MeanReversionStrategy`. If ``None``, defaults are used.
        """
        super().__init__(params)
        self._base = MeanReversionStrategy(params)

    async def analyze(self, data: pd.DataFrame, symbol: str) -> Optional[Signal]:
        """Generate a trading signal for a given symbol.

        The method first obtains a signal from the underlying mean‑reversion
        strategy. If a base signal is present, it queries the ML inference service
        to validate the direction. When the ML confidence exceeds 0.60 and the
        prediction aligns with the base signal, the base signal's confidence is
        boosted (capped at 0.93) and returned.

        Parameters
        ----------
        data : pandas.DataFrame
            Historical price data for the symbol, indexed by timestamp.
        symbol : str
            Ticker symbol of the instrument being analysed.

        Returns
        -------
        Signal | None
            An enriched :class:`Signal` if both the base strategy and ML filter
            agree; otherwise ``None``. In case of ML service failure, the base
            signal is returned as a fallback.
        """
        base_signal = await self._base.analyze(data, symbol)
        if not base_signal:
            return None
        try:
            inference = get_inference_service()
            ml_result = await inference.predict(data, symbol)
            if ml_result and ml_result["confidence"] > 0.60:
                match = (
                    (ml_result["prediction"] == "up" and base_signal.side == "buy")
                    or (ml_result["prediction"] == "down" and base_signal.side == "sell")
                )
                if match:
                    base_signal.confidence = min(0.93, base_signal.confidence * 1.1)
                    base_signal.strategy_name = self.name
                    base_signal.strategy_type = self.strategy_type
                    return base_signal
                return None  # ML disagrees — skip
        except Exception:
            return base_signal  # fallback
        return None

    def backtest_signals(self, df: pd.DataFrame) -> BacktestSignals:
        """Delegate back‑testing to the underlying mean‑reversion strategy.

        Parameters
        ----------
        df : pandas.DataFrame
            Dataframe containing historical price data for back‑testing.

        Returns
        -------
        BacktestSignals
            The collection of signals generated by the base mean‑reversion
            strategy for the provided dataset.
        """
        return self._base.backtest_signals(df)