"""ML-filtered mean reversion strategy.

Reduces false signals by approximately 30% by applying a machine‑learning filter on top
of the classic Bollinger‑Band mean‑reversion logic.
"""

from __future__ import annotations

import pandas as pd
from typing import Any, Dict, Optional

from app.strategies.base import AbstractStrategy, Signal, BacktestSignals
from app.strategies.manual.mean_reversion import MeanReversionStrategy
from app.ml.inference import get_inference_service


class MLMeanReversionStrategy(AbstractStrategy):
    """Mean‑reversion strategy enhanced with a machine‑learning filter.

    The strategy delegates the core mean‑reversion logic to
    :class:`MeanReversionStrategy` and then validates the signal using an
    asynchronous ML inference service.  If the ML model agrees with the base
    signal and its confidence exceeds a threshold, the signal confidence is
    slightly boosted; otherwise the signal is discarded.

    Attributes
    ----------
    name : str
        Internal identifier for the strategy.
    display_name : str
        Human‑readable name shown in UI / logs.
    market_type : str
        Market category (e.g., ``"equity"``).
    strategy_type : str
        Category indicating the strategy is ML‑enhanced.
    risk_bucket : str
        Risk classification used for portfolio allocation.
    tick_interval_seconds : float
        Expected data granularity for the strategy.
    """

    name = "ml_mean_reversion"
    display_name = "ML Mean Reversion (BB + ML Filter)"
    market_type = "equity"
    strategy_type = "ml_enhanced"
    risk_bucket = "directional"
    tick_interval_seconds = 300.0

    def __init__(self, params: Optional[Dict[str, Any]] = None) -> None:
        """Create a new ML‑enhanced mean‑reversion strategy.

        Parameters
        ----------
        params : dict | None, optional
            Optional configuration dictionary forwarded to the underlying
            :class:`MeanReversionStrategy`.  If ``None``, defaults defined by the
            base strategy are used.
        """
        super().__init__(params)
        self._base = MeanReversionStrategy(params)

    async def analyze(self, data: pd.DataFrame, symbol: str) -> Signal | None:
        """Generate a trading signal for a given symbol.

        The method first obtains a base signal from the underlying mean‑reversion
        strategy.  It then queries the ML inference service; if the model predicts
        the same direction with confidence greater than ``0.60``, the base signal
        confidence is modestly increased and the signal is returned.

        Parameters
        ----------
        data : pandas.DataFrame
            Historical price and indicator data required by the strategy.
        symbol : str
            Ticker symbol for which the analysis is performed.

        Returns
        -------
        Signal | None
            A populated :class:`Signal` object if both the base strategy and the
            ML filter agree, otherwise ``None``.  In case of any exception from the
            ML service, the unfiltered base signal is returned as a fallback.
        """
        base_signal = await self._base.analyze(data, symbol)
        if not base_signal:
            return None
        try:
            inference = get_inference_service()
            ml_result = await inference.predict(data, symbol)
            if ml_result and ml_result["confidence"] > 0.60:
                match = (
                    (ml_result["prediction"] == "up" and base_signal.side == "buy")
                    or (ml_result["prediction"] == "down" and base_signal.side == "sell")
                )
                if match:
                    base_signal.confidence = min(0.93, base_signal.confidence * 1.1)
                    base_signal.strategy_name = self.name
                    base_signal.strategy_type = self.strategy_type
                    return base_signal
                return None  # ML disagrees — skip
        except Exception:
            return base_signal  # fallback
        return None

    def backtest_signals(self, df: pd.DataFrame) -> BacktestSignals:
        """Delegate backtesting to the underlying mean‑reversion strategy.

        Parameters
        ----------
        df : pandas.DataFrame
            Dataframe containing historical market data for backtesting.

        Returns
        -------
        BacktestSignals
            Collection of signals generated by the base strategy.
        """
        return self._base.backtest_signals(df)