from __future__ import annotations

import logging
from typing import Optional

import numpy as np
import pandas as pd
from pydantic import BaseModel, Field, validator

import app.ml.features.pandas_ta_compat as ta

_logger = logging.getLogger(__name__)


class TechnicalFeatures(BaseModel):
    """
    Pydantic schema representing the technical indicator features generated by
    :func:`add_technical_features`.

    The schema is permissive (``extra = "allow"``) because the exact set of
    columns depends on the availability of the underlying price series and the
    success of each indicator computation. Only a subset of the most common
    fields are explicitly documented; any additional columns produced by the
    feature pipeline will be accepted without validation.

    Attributes
    ----------
    returns_1: Optional[float]
        One‑period (daily) return expressed as a decimal fraction. Example: ``0.0012``.
    returns_5: Optional[float]
        Five‑period return. Example: ``0.0056``.
    returns_10: Optional[float]
        Ten‑period return. Example: ``0.0123``.
    returns_21: Optional[float]
        Twenty‑one‑period return (approximately one month). Example: ``0.0234``.
    vol_5: Optional[float]
        Annualized volatility based on a 5‑period rolling window of log returns.
    vol_21: Optional[float]
        Annualized volatility based on a 21‑period rolling window.
    vol_63: Optional[float]
        Annualized volatility based on a 63‑period rolling window.
    ema_9_diff: Optional[float]
        Normalized distance between price and 9‑period EMA.
    ema_21_diff: Optional[float]
        Normalized distance between price and 21‑period EMA.
    ema_50_diff: Optional[float]
        Normalized distance between price and 50‑period EMA.
    rsi_14: Optional[float]
        Relative Strength Index over 14 periods, scaled to ``[0, 1]``.
    rsi_21: Optional[float]
        Relative Strength Index over 21 periods, scaled to ``[0, 1]``.
    macd: Optional[float]
        MACD line normalized by price.
    macd_signal: Optional[float]
        MACD signal line normalized by price.
    macd_hist: Optional[float]
        MACD histogram normalized by price.
    bb_upper_dist: Optional[float]
        Distance from price to upper Bollinger Band, normalized by price.
    bb_lower_dist: Optional[float]
        Distance from price to lower Bollinger Band, normalized by price.
    bb_width: Optional[float]
        Width of Bollinger Bands relative to the middle band.
    obv_change: Optional[float]
        Five‑period percent change of On‑Balance Volume.
    volume_ratio: Optional[float]
        Current volume divided by its 20‑period moving average.
    atr_14: Optional[float]
        Average True Range over 14 periods.
    atr_pct: Optional[float]
        ATR expressed as a fraction of price.
    stoch_k: Optional[float]
        Stochastic %K line, scaled to ``[0, 1]``.
    stoch_d: Optional[float]
        Stochastic %D line, scaled to ``[0, 1]``.
    adx: Optional[float]
        Average Directional Index over 14 periods, scaled to ``[0, 1]``.
    """

    returns_1: Optional[float] = Field(
        None, description="One‑period return", example=0.0012
    )
    returns_5: Optional[float] = Field(
        None, description="Five‑period return", example=0.0056
    )
    returns_10: Optional[float] = Field(
        None, description="Ten‑period return", example=0.0123
    )
    returns_21: Optional[float] = Field(
        None, description="Twenty‑one‑period return", example=0.0234
    )
    vol_5: Optional[float] = Field(
        None,
        description="Annualized volatility (5‑period rolling window of log returns)",
        example=0.18,
    )
    vol_21: Optional[float] = Field(
        None,
        description="Annualized volatility (21‑period rolling window of log returns)",
        example=0.22,
    )
    vol_63: Optional[float] = Field(
        None,
        description="Annualized volatility (63‑period rolling window of log returns)",
        example=0.27,
    )
    ema_9_diff: Optional[float] = Field(
        None,
        description="Normalized distance between price and 9‑period EMA",
        example=-0.015,
    )
    ema_21_diff: Optional[float] = Field(
        None,
        description="Normalized distance between price and 21‑period EMA",
        example=0.004,
    )
    ema_50_diff: Optional[float] = Field(
        None,
        description="Normalized distance between price and 50‑period EMA",
        example=0.012,
    )
    rsi_14: Optional[float] = Field(
        None,
        description="RSI over 14 periods scaled to [0, 1]",
        example=0.58,
    )
    rsi_21: Optional[float] = Field(
        None,
        description="RSI over 21 periods scaled to [0, 1]",
        example=0.62,
    )
    macd: Optional[float] = Field(
        None,
        description="MACD line normalized by price",
        example=0.003,
    )
    macd_signal: Optional[float] = Field(
        None,
        description="MACD signal line normalized by price",
        example=0.0025,
    )
    macd_hist: Optional[float] = Field(
        None,
        description="MACD histogram normalized by price",
        example=-0.0005,
    )
    bb_upper_dist: Optional[float] = Field(
        None,
        description="Normalized distance from price to upper Bollinger Band",
        example=0.012,
    )
    bb_lower_dist: Optional[float] = Field(
        None,
        description="Normalized distance from price to lower Bollinger Band",
        example=0.008,
    )
    bb_width: Optional[float] = Field(
        None,
        description="Bollinger Band width relative to middle band",
        example=0.04,
    )
    obv_change: Optional[float] = Field(
        None,
        description="Five‑period percent change of On‑Balance Volume",
        example=0.03,
    )
    volume_ratio: Optional[float] = Field(
        None,
        description="Current volume divided by its 20‑period moving average",
        example=1.15,
    )
    atr_14: Optional[float] = Field(
        None,
        description="Average True Range over 14 periods",
        example=0.012,
    )
    atr_pct: Optional[float] = Field(
        None,
        description="ATR expressed as a fraction of price",
        example=0.0015,
    )
    stoch_k: Optional[float] = Field(
        None,
        description="Stochastic %K line scaled to [0, 1]",
        example=0.45,
    )
    stoch_d: Optional[float] = Field(
        None,
        description="Stochastic %D line scaled to [0, 1]",
        example=0.48,
    )
    adx: Optional[float] = Field(
        None,
        description="Average Directional Index over 14 periods scaled to [0, 1]",
        example=0.35,
    )

    @validator("*", pre=True, always=True)
    def _ensure_float_or_none(cls, v):
        """
        Validate that each feature value is either ``None`` or a ``float``.
        ``NaN`` values from pandas are coerced to ``None`` to keep the schema
        JSON‑serializable.
        """
        if v is None:
            return None
        if isinstance(v, (float, int)):
            return float(v)
        # pandas may produce ``np.nan`` which is not JSON serializable
        if isinstance(v, (np.floating, np.integer)):
            return float(v)
        return None

    class Config:
        extra = "allow"
        title = "Technical Features"
        description = (
            "Schema for technical indicator features derived from price "
            "time‑series data. Fields not explicitly listed are permitted "
            "and will be stored as ``float`` if possible."
        )
        schema_extra = {
            "example": {
                "returns_1": 0.0012,
                "vol_21": 0.22,
                "ema_9_diff": -0.015,
                "rsi_14": 0.58,
                "macd": 0.003,
                "bb_upper_dist": 0.012,
                "obv_change": 0.03,
                "volume_ratio": 1.15,
                "atr_14": 0.012,
                "stoch_k": 0.45,
                "adx": 0.35,
            }
        }


def _safe_apply(func, *args, **kwargs) -> Optional[pd.DataFrame]:
    """
    Helper to execute a function safely.

    Parameters
    ----------
    func : callable
        The function to execute.
    *args, **kwargs :
        Arguments passed to ``func``.

    Returns
    -------
    Optional[pd.DataFrame]
        The result of ``func`` if successful, otherwise ``None``.
    """
    try:
        return func(*args, **kwargs)
    except (KeyError, ValueError, TypeError) as exc:
        _logger.error(
            "Technical feature computation failed in %s with args=%s, kwargs=%s",
            func.__name__,
            args,
            kwargs,
            exc_info=exc,
        )
        return None


def add_technical_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Compute a suite of technical indicators and append them as new columns
    to a copy of the input DataFrame.

    Parameters
    ----------
    df : pd.DataFrame
        Input price DataFrame. Must contain a ``close`` column. Optional
        columns are ``high``, ``low`` and ``volume``. Missing optional columns
        are filled with sensible defaults (e.g., ``high`` and ``low`` default
        to ``close``; ``volume`` defaults to a series of ones).

    Returns
    -------
    pd.DataFrame
        A new DataFrame containing the original columns plus the technical
        feature columns. If a particular indicator cannot be computed,
        its column is omitted and the error is logged.
    """
    if "close" not in df.columns:
        raise ValueError("Input DataFrame must contain a 'close' column.")

    df = df.copy()
    close = df["close"]
    high = df.get("high", close)
    low = df.get("low", close)
    volume = df.get("volume", pd.Series(1, index=df.index))

    # --- Returns ---
    for n in [1, 5, 10, 21]:
        try:
            df[f"returns_{n}"] = close.pct_change(n)
        except Exception as exc:  # pragma: no cover
            _logger.error("Failed to compute returns_%d", n, exc_info=exc)

    # --- Volatility (rolling std of log returns) ---
    try:
        log_ret = np.log(close / close.shift(1))
        for n in [5, 21, 63]:
            df[f"vol_{n}"] = log_ret.rolling(n).std() * np.sqrt(252)
    except Exception as exc:  # pragma: no cover
        _logger.error("Failed to compute volatility features", exc_info=exc)

    # --- EMA distance (normalized) ---
    for span in [9, 21, 50]:
        try:
            ema = close.ewm(span=span).mean()
            df[f"ema_{span}_diff"] = (close - ema) / (ema + 1e-9)
        except Exception as exc:  # pragma: no cover
            _logger.error("Failed to compute EMA distance for span %d", span, exc_info=exc)

    # --- RSI ---
    rsi14 = _safe_apply(ta.rsi, close, length=14)
    rsi21 = _safe_apply(ta.rsi, close, length=21)
    if rsi14 is not None:
        df["rsi_14"] = rsi14 / 100.0  # normalize to [0,1]
    if rsi21 is not None:
        df["rsi_21"] = rsi21 / 100.0

    # --- MACD ---
    macd_df = _safe_apply(ta.macd, close, fast=12, slow=26, signal=9)
    if macd_df is not None:
        try:
            df["macd"] = macd_df["MACD_12_26_9"] / (close + 1e-9)
            df["macd_signal"] = macd_df["MACDs_12_26_9"] / (close + 1e-9)
            df["macd_hist"] = macd_df["MACDh_12_26_9"] / (close + 1e-9)
        except Exception as exc:  # pragma: no cover
            _logger.error("Failed to normalize MACD components", exc_info=exc)

    # --- Bollinger Bands ---
    bb = _safe_apply(ta.bbands, close, length=20, std=2.0)
    if bb is not None:
        try:
            upper = bb["BBU_20_2.0"]
            lower = bb["BBL_20_2.0"]
            mid = bb["BBM_20_2.0"]
            df["bb_upper_dist"] = (upper - close) / (close + 1e-9)
            df["bb_lower_dist"] = (close - lower) / (close + 1e-9)
            df["bb_width"] = (upper - lower) / (mid + 1e-9)
        except Exception as exc:  # pragma: no cover
            _logger.error("Failed to compute Bollinger Band features", exc_info=exc)

    # --- OBV change (normalized) ---
    obv = _safe_apply(ta.obv, close, volume)
    if obv is not None:
        try:
            df["obv_change"] = obv.pct_change(5).fillna(0)
        except Exception as exc:  # pragma: no cover
            _logger.error("Failed to compute OBV change", exc_info=exc)

    # --- Volume ratio ---
    try:
        vol_ma = volume.rolling(20).mean()
        df["volume_ratio"] = volume / (vol_ma + 1e-9)
    except Exception as exc:  # pragma: no cover
        _logger.error("Failed to compute volume ratio", exc_info=exc)

    # --- ATR ---
    atr = _safe_apply(ta.atr, high, low, close, length=14)
    if atr is not None:
        try:
            df["atr_14"] = atr
            df["atr_pct"] = atr / (close + 1e-9)
        except Exception as exc:  # pragma: no cover
            _logger.error("Failed to compute ATR related features", exc_info=exc)

    # --- Stochastic ---
    stoch = _safe_apply(ta.stoch, high, low, close, k=14, d=3)
    if stoch is not None:
        try:
            df["stoch_k"] = stoch["STOCHk_14_3_3"] / 100.0
            df["stoch_d"] = stoch["STOCHd_14_3_3"] / 100.0
        except Exception as exc:  # pragma: no cover
            _logger.error("Failed to compute Stochastic Oscillator features", exc_info=exc)

    # --- ADX ---
    adx_df = _safe_apply(ta.adx, high, low, close, length=14)
    if adx_df is not None:
        try:
            df["adx"] = adx_df["ADX_14"] / 100.0
        except Exception as exc:  # pragma: no cover
            _logger.error("Failed to compute ADX feature", exc_info=exc)

    return df