"""
Auto-status / self-diagnose.
============================
Probes the live system — LLM providers, Slack, Alpaca, backend — and regenerates
SYSTEM_STATUS.md so the repo always shows current truth. Run on a schedule (see
system-status.yml). The point: nobody has to ask "what's working / what do I need
to fix" — and the moment a missing key is added, the next run flips it to green.

Never prints secret values. Pure read-only probes. Exits 0 even if things are
down (a status report failing is itself a failure mode we don't want).
"""
from __future__ import annotations

import json
import os
import sys
import urllib.request
import urllib.error
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import llm_common  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[2]
STATUS_FILE = REPO_ROOT / "SYSTEM_STATUS.md"
UA = getattr(llm_common, "_BROWSER_UA", "Mozilla/5.0")


def probe_providers() -> list[dict]:
    rows = []
    for p in llm_common._PROVIDERS:
        name = p["name"]
        if not llm_common._has_key(p):
            rows.append({"name": name, "state": "no key", "ok": False})
            continue
        try:
            out = llm_common._call_provider(p, "You are terse.", "Reply one word: PONG", 16, 0.0)
            rows.append({"name": name, "state": f"OK ({out[:20]})", "ok": bool(out)})
        except urllib.error.HTTPError as e:
            rows.append({"name": name, "state": f"HTTP {e.code}", "ok": False})
        except Exception as e:
            rows.append({"name": name, "state": type(e).__name__, "ok": False})
    return rows


def probe_slack() -> dict:
    tok = os.environ.get("SLACK_BOT_TOKEN", "").strip()
    if not tok:
        return {"ok": False, "detail": "no SLACK_BOT_TOKEN"}
    try:
        req = urllib.request.Request(
            "https://slack.com/api/auth.test", data=b"",
            headers={"Authorization": f"Bearer {tok}", "User-Agent": UA}, method="POST",
        )
        with urllib.request.urlopen(req, timeout=15) as r:
            d = json.loads(r.read())
        return {"ok": bool(d.get("ok")), "detail": d.get("team") or d.get("error") or "?"}
    except Exception as e:
        return {"ok": False, "detail": type(e).__name__}


def probe_alpaca() -> dict:
    key = os.environ.get("ALPACA_API_KEY", "").strip()
    sec = os.environ.get("ALPACA_SECRET_KEY", "").strip()
    if not key:
        return {"ok": False, "detail": "missing ALPACA_API_KEY (key id)"}
    if not sec:
        return {"ok": False, "detail": "missing ALPACA_SECRET_KEY"}
    base = os.environ.get("ALPACA_BASE_URL", "https://paper-api.alpaca.markets").rstrip("/")
    try:
        req = urllib.request.Request(
            f"{base}/v2/account",
            headers={"APCA-API-KEY-ID": key, "APCA-API-SECRET-KEY": sec, "User-Agent": UA},
        )
        with urllib.request.urlopen(req, timeout=15) as r:
            d = json.loads(r.read())
        return {"ok": True, "detail": f"account {d.get('status', '?')}, equity {d.get('equity', '?')}"}
    except urllib.error.HTTPError as e:
        return {"ok": False, "detail": f"HTTP {e.code} (check key pair)"}
    except Exception as e:
        return {"ok": False, "detail": type(e).__name__}


def probe_backend() -> dict:
    url = os.environ.get("BACKEND_HEALTH_URL", "").strip()
    if not url:
        return {"ok": None, "detail": "no BACKEND_HEALTH_URL set"}
    try:
        req = urllib.request.Request(url, headers={"User-Agent": UA})
        with urllib.request.urlopen(req, timeout=15) as r:
            d = json.loads(r.read())
        return {"ok": True, "detail": d.get("status", "up")}
    except Exception as e:
        return {"ok": False, "detail": type(e).__name__}


def render() -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    providers = probe_providers()
    live = [p["name"] for p in providers if p["ok"]]
    slack = probe_slack()
    alpaca = probe_alpaca()
    backend = probe_backend()

    def mark(ok):
        return "✅" if ok else ("⚠️" if ok is None else "❌")

    lines = [
        "# QuantEdge — System Status (auto-generated)",
        "",
        f"_Regenerated by `auto_status.py` at {ts}. Do not hand-edit — the next run overwrites it._",
        "",
        "## Brain (LLM cascade)",
        f"**{len(live)}/{len(providers)} providers live:** {', '.join(live) or 'NONE'}",
        "",
        "| Provider | State |",
        "|---|---|",
    ]
    lines += [f"| {p['name']} | {mark(p['ok'])} {p['state']} |" for p in providers]
    lines += [
        "",
        "## Integrations",
        "| Service | Status | Detail |",
        "|---|---|---|",
        f"| Slack | {mark(slack['ok'])} | {slack['detail']} |",
        f"| Alpaca (trading/data) | {mark(alpaca['ok'])} | {alpaca['detail']} |",
        f"| Backend API | {mark(backend['ok'])} | {backend['detail']} |",
        "",
        "## What needs a human",
        "See [`docs/OWNER_ACTIONS.md`](docs/OWNER_ACTIONS.md). In short:",
        f"- Alpaca: {'✅ trading-ready' if alpaca['ok'] else '❌ ' + alpaca['detail']}",
        f"- Backend: {'✅ up' if backend['ok'] else '⚠️ down / not configured'}",
        f"- Brain: {'✅ healthy' if live else '❌ no providers answering'}",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    content = render()
    STATUS_FILE.write_text(content)
    print(content)


if __name__ == "__main__":
    main()
