"""
Employee Introduction System — Daily Icebreaker + Conversation Test
=====================================================================
Every day, each employee introduces themselves on every channel they're in.
Other employees on that channel reply. Then one final follow-up round.

No hardcoded responses — all text generated by free LLM cascade.
Employees are defined as structured config (role, expertise, personality).
Conversations are fully dynamic based on the channel topic and other members present.

Architecture:
  Round 0 — Each employee posts their intro to each of their channels
  Round 1 — Every OTHER employee in the channel replies to the intro (in-thread)
  Round 2 — Each original poster does one follow-up reply to the most interesting reply

Run daily via GitHub Actions.
"""
from __future__ import annotations

import json, os, re, sys, time, urllib.request
from datetime import datetime, timezone
from pathlib import Path

SLACK_TOKEN = os.environ.get("SLACK_BOT_TOKEN", "")
ALLOW_PAID  = os.environ.get("ALLOW_PAID_APIS", "False")
if ALLOW_PAID.lower() == "true":
    sys.exit(1)

TODAY = datetime.now(timezone.utc).strftime("%Y-%m-%d")

# ── Employee definitions (structured config — NO hardcoded responses) ──────────
# Each employee: name, title, expertise, personality, channels they belong to

EMPLOYEES = [
    {
        "id": "alex_research",
        "name": "Alex Chen",
        "title": "Senior Research Analyst",
        "expertise": "cross-sectional momentum, factor construction, academic paper implementation",
        "personality": "methodical, cites papers, thinks in Sharpe ratios",
        "channels": ["desk-research", "alpha-research", "general", "squad-alpha-research"],
    },
    {
        "id": "priya_quant",
        "name": "Priya Sharma",
        "title": "Quantitative Strategist",
        "expertise": "statistical arbitrage, cointegration pairs trading, regime detection",
        "personality": "data-driven, loves p-values, skeptical of overfitting",
        "channels": ["desk-research", "alpha-research", "ml-research", "squad-alpha-research"],
    },
    {
        "id": "marcus_risk",
        "name": "Marcus Rivera",
        "title": "Head of Risk",
        "expertise": "Kelly criterion, CVaR, drawdown management, position sizing, correlation limits",
        "personality": "conservative, always asks about tail risk, never skips stress tests",
        "channels": ["risk", "risk-alerts", "desk-research", "leadership", "squad-risk"],
    },
    {
        "id": "sofia_ml",
        "name": "Sofia Petrov",
        "title": "ML Engineer",
        "expertise": "LSTM, XGBoost, Lorentzian KNN, feature engineering, walk-forward validation",
        "personality": "excited about model architectures, practical, hates leakage",
        "channels": ["ml-research", "ml-experiments", "engineering", "squad-ml-modeling"],
    },
    {
        "id": "james_exec",
        "name": "James Kim",
        "title": "Execution Specialist",
        "expertise": "TWAP, VWAP, limit-first algorithms, market microstructure, slippage minimization",
        "personality": "obsessed with basis points, practical, values speed over perfection",
        "channels": ["execution", "desk-equities", "engineering", "squad-execution"],
    },
    {
        "id": "luna_crypto",
        "name": "Luna Nakamura",
        "title": "Crypto Desk Lead",
        "expertise": "Binance perpetuals, funding rate arbitrage, on-chain metrics, liquidation cascades",
        "personality": "fast-moving, monitors 24/7, thinks in funding rates and open interest",
        "channels": ["desk-crypto", "crypto", "alpha-research", "squad-alpha-research"],
    },
    {
        "id": "oliver_backend",
        "name": "Oliver Walsh",
        "title": "Senior Backend Engineer",
        "expertise": "FastAPI async, SQLAlchemy, Redis, WebSocket, Alpaca API integration",
        "personality": "practical, values reliability over cleverness, writes tests first",
        "channels": ["backend", "engineering", "devops", "squad-backend"],
    },
    {
        "id": "nina_frontend",
        "name": "Nina Torres",
        "title": "Frontend Engineer",
        "expertise": "React, TypeScript, TradingView widgets, Lightweight Charts, real-time WebSocket UI",
        "personality": "user-focused, cares about latency, makes ugly data look beautiful",
        "channels": ["frontend", "engineering", "product", "squad-frontend"],
    },
    {
        "id": "raj_tv",
        "name": "Raj Patel",
        "title": "TradingView Indicator Specialist",
        "expertise": "EMA stacks, Squeeze Pro, Wave Trend, VWAP bands, multi-timeframe confluence",
        "personality": "chart obsessed, speaks in indicator names, always tuning parameters",
        "channels": ["desk-tv-indicators", "desk-research", "alpha-research"],
    },
    {
        "id": "ceo_dana",
        "name": "Dana Webb",
        "title": "CEO / Portfolio Manager",
        "expertise": "fund strategy, investor relations, portfolio construction, Sharpe vs benchmark",
        "personality": "big picture thinker, investor pitch ready, keeps focus on outperforming benchmarks",
        "channels": ["general", "leadership", "announcements", "desk-research"],
    },
    {
        "id": "data_eng_kai",
        "name": "Kai Okonkwo",
        "title": "Data Engineer",
        "expertise": "OHLCV pipelines, Redis price cache, yfinance, Binance REST, data quality",
        "personality": "upstream-focused, pedantic about data freshness, loves monitoring dashboards",
        "channels": ["data-engineering", "engineering", "backend", "squad-data"],
    },
    {
        "id": "poly_analyst",
        "name": "Zara Mendez",
        "title": "Polymarket Analyst",
        "expertise": "prediction markets, probability calibration, binary arbitrage, event resolution",
        "personality": "thinks in probabilities, sharp on market microstructure of prediction markets",
        "channels": ["desk-polymarket", "alpha-research", "polymarket"],
    },
]

# ── Free LLM cascade ──────────────────────────────────────────────────────────

def _llm(prompt: str, max_tokens: int = 200) -> str | None:
    providers = [
        ("gemini",    os.environ.get("GEMINI_API_KEY", os.environ.get("GEMINI_API_KEY_1", "")),
         "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions", "gemini-2.0-flash"),
        ("groq",      os.environ.get("GROQ_API_KEY", ""),
         "https://api.groq.com/openai/v1/chat/completions", "llama-3.3-70b-versatile"),
        ("deepseek",  os.environ.get("DEEPSEEK_API_KEY", ""),
         "https://api.deepseek.com/v1/chat/completions", "deepseek-chat"),
        ("together",  os.environ.get("TOGETHER_API_KEY", ""),
         "https://api.together.xyz/v1/chat/completions", "meta-llama/Llama-3.3-70B-Instruct-Turbo"),
        ("cerebras",  os.environ.get("CEREBRAS_API_KEY", ""),
         "https://api.cerebras.ai/v1/chat/completions", "llama-3.3-70b"),
        ("sambanova", os.environ.get("SAMBANOVA_API_KEY", ""),
         "https://api.sambanova.ai/v1/chat/completions", "Meta-Llama-3.3-70B-Instruct"),
        ("hyperbolic", os.environ.get("HYPERBOLIC_API_KEY", ""),
         "https://api.hyperbolic.xyz/v1/chat/completions", "meta-llama/Llama-3.3-70B-Instruct"),
    ]
    for pname, key, url, model in providers:
        if not key or key in ("disabled", ""):
            continue
        try:
            payload = json.dumps({
                "model": model,
                "messages": [{"role": "user", "content": prompt}],
                "max_tokens": max_tokens,
                "temperature": 0.8,   # higher temp for personality variety
            }).encode()
            req = urllib.request.Request(url, data=payload, headers={
                "Authorization": f"Bearer {key}", "Content-Type": "application/json",
            })
            with urllib.request.urlopen(req, timeout=30) as resp:
                data = json.loads(resp.read())
            return data["choices"][0]["message"]["content"].strip()
        except Exception as e:
            print(f"[intros] {pname}: {e}")
    return None


# ── Slack API helpers ─────────────────────────────────────────────────────────

def _slack(method: str, payload: dict) -> dict:
    if not SLACK_TOKEN:
        return {}
    try:
        data = json.dumps(payload).encode()
        req = urllib.request.Request(
            f"https://slack.com/api/{method}", data=data,
            headers={"Authorization": f"Bearer {SLACK_TOKEN}",
                     "Content-Type": "application/json"},
        )
        with urllib.request.urlopen(req, timeout=15) as resp:
            return json.loads(resp.read())
    except Exception as e:
        print(f"[intros] Slack {method}: {e}")
        return {}


def resolve_channels() -> dict[str, str]:
    """Return {channel_name: channel_id} for all channels."""
    result = _slack("conversations.list", {
        "exclude_archived": True,
        "types": "public_channel,private_channel",
        "limit": 200,
    })
    return {ch["name"]: ch["id"] for ch in result.get("channels", [])}


def post(channel_id: str, text: str, thread_ts: str | None = None) -> str | None:
    payload: dict = {"channel": channel_id, "text": text, "mrkdwn": True}
    if thread_ts:
        payload["thread_ts"] = thread_ts
    result = _slack("chat.postMessage", payload)
    return result.get("ts")


# ── Prompt builders ───────────────────────────────────────────────────────────

def build_intro_prompt(employee: dict, channel: str, channel_members: list[dict]) -> str:
    other_names = [e["name"] for e in channel_members if e["id"] != employee["id"]]
    teammates = ", ".join(other_names[:4]) if other_names else "the team"
    return f"""You are {employee['name']}, {employee['title']} at QuantEdge — an AI-powered quantitative trading firm.

Your expertise: {employee['expertise']}
Your personality: {employee['personality']}

Write a brief Slack introduction message for the #{channel} channel.
You are introducing yourself to your teammates ({teammates}) who are also in this channel.
Make it natural, specific to your role, and relevant to what this channel is about.
Mention one specific thing you're working on or excited about right now.
Keep it to 3-5 sentences. Use casual but professional Slack tone. No hashtags or emojis spam."""


def build_reply_prompt(
    replier: dict, intro_author: dict, intro_text: str, channel: str
) -> str:
    return f"""You are {replier['name']}, {replier['title']} at QuantEdge — an AI-powered quantitative trading firm.
Your expertise: {replier['expertise']}
Your personality: {replier['personality']}

Your colleague {intro_author['name']} ({intro_author['title']}) just posted this introduction in #{channel}:
"{intro_text}"

Write a natural, genuine Slack reply. Reference something specific they said.
Ask a relevant follow-up question OR share a related perspective from your own work.
Keep it to 2-3 sentences. Sound like a real colleague, not a bot."""


def build_followup_prompt(
    author: dict, best_reply_author: dict, best_reply_text: str,
    channel: str, all_replies: list[str]
) -> str:
    reply_summary = " | ".join(r[:80] for r in all_replies[:3])
    return f"""You are {author['name']}, {author['title']} at QuantEdge.
Your expertise: {author['expertise']}
Your personality: {author['personality']}

You posted an intro in #{channel}. Your colleagues replied.
{best_reply_author['name']} said: "{best_reply_text}"

All replies so far: {reply_summary}

Write a 2-3 sentence follow-up. Respond to what {best_reply_author['name']} said specifically.
Move the conversation forward — propose something concrete to collaborate on, or share a quick insight.
Sound natural, like a real colleague wrapping up a brief Slack thread."""


# ── Main conversation engine ──────────────────────────────────────────────────

def run_channel_conversations(channel_name: str, channel_id: str, members: list[dict]) -> None:
    """Run full 2-round intro conversation for all members in a channel."""
    if len(members) < 2:
        print(f"[intros] #{channel_name}: only {len(members)} member(s), skipping")
        return

    print(f"\n[intros] #{channel_name}: {len(members)} members")

    # Round 0: Each member posts their intro
    intros: list[dict] = []   # {employee, text, thread_ts}

    for emp in members:
        prompt = build_intro_prompt(emp, channel_name, members)
        text = _llm(prompt, max_tokens=150)
        if not text:
            print(f"[intros]   {emp['name']}: LLM failed, skipping")
            continue

        # Format: *Name | Title*\n text
        formatted = f"*{emp['name']}* | _{emp['title']}_\n{text}"
        ts = post(channel_id, formatted)
        if ts:
            intros.append({"employee": emp, "text": text, "thread_ts": ts})
            print(f"[intros]   {emp['name']}: intro posted (ts={ts})")
        time.sleep(1.5)   # rate limit

    if not intros:
        return

    time.sleep(2)

    # Round 1: Every other member replies to each intro
    for intro in intros:
        author = intro["employee"]
        repliers = [m for m in members if m["id"] != author["id"]]

        replies: list[dict] = []   # {employee, text}
        for replier in repliers[:3]:   # max 3 replies per intro to avoid noise
            prompt = build_reply_prompt(replier, author, intro["text"], channel_name)
            reply_text = _llm(prompt, max_tokens=120)
            if not reply_text:
                continue

            formatted = f"*{replier['name']}:* {reply_text}"
            post(channel_id, formatted, thread_ts=intro["thread_ts"])
            replies.append({"employee": replier, "text": reply_text})
            print(f"[intros]   {replier['name']} → replied to {author['name']}")
            time.sleep(1.5)

        if not replies:
            continue

        time.sleep(2)

        # Round 2: Original poster follows up to the most interesting reply
        best_reply = replies[0]   # pick first (or could pick longest/most specific)
        prompt = build_followup_prompt(
            author, best_reply["employee"], best_reply["text"],
            channel_name, [r["text"] for r in replies]
        )
        followup = _llm(prompt, max_tokens=120)
        if followup:
            formatted = f"*{author['name']}:* {followup}"
            post(channel_id, formatted, thread_ts=intro["thread_ts"])
            print(f"[intros]   {author['name']}: follow-up posted")
        time.sleep(1.5)


def main() -> None:
    if not SLACK_TOKEN:
        print("[intros] No SLACK_BOT_TOKEN — dry run only")
        # Dry-run: print what would happen
        for emp in EMPLOYEES[:3]:
            print(f"  {emp['name']} ({emp['title']}) → channels: {emp['channels']}")
        return

    print(f"[intros] Starting daily employee introductions — {TODAY}")
    print(f"[intros] {len(EMPLOYEES)} employees across multiple channels")

    channel_map = resolve_channels()
    if not channel_map:
        print("[intros] Could not resolve channels — check SLACK_BOT_TOKEN")
        return

    # Build per-channel member list dynamically
    channel_members: dict[str, list[dict]] = {}
    for emp in EMPLOYEES:
        for ch in emp["channels"]:
            channel_members.setdefault(ch, []).append(emp)

    # Run conversations only on channels that exist in Slack
    # Process channels with most members first (richest conversations)
    ordered = sorted(
        [(ch, members) for ch, members in channel_members.items() if ch in channel_map],
        key=lambda x: -len(x[1])
    )

    if not ordered:
        print("[intros] No matching channels found in Slack workspace")
        return

    for channel_name, members in ordered:
        ch_id = channel_map[channel_name]
        run_channel_conversations(channel_name, ch_id, members)
        time.sleep(3)  # pause between channels

    print(f"\n[intros] Done. Conversations run on {len(ordered)} channels.")


if __name__ == "__main__":
    main()
