"""
Employee Introduction System — Daily Icebreaker + Conversation Test
=====================================================================
Every day, each employee introduces themselves on every channel they're in.
Other employees on that channel reply. Then one final follow-up round.

No hardcoded responses — all text generated by free LLM cascade.
Employees are defined as structured config (role, expertise, personality).
Conversations are fully dynamic based on the channel topic and other members present.

Architecture:
  Round 0 — Each employee posts their intro to each of their channels
  Round 1 — Every OTHER employee in the channel replies to the intro (in-thread)
  Round 2 — Each original poster does one follow-up reply to the most interesting reply

Run daily via GitHub Actions.
"""
from __future__ import annotations

import json
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

# Use shared LLM infrastructure — no more copy-paste cascade
sys.path.insert(0, str(Path(__file__).parent))
from llm_common import llm, slack_post, slack_read_thread, memory_write, get_company_context

SLACK_TOKEN = os.environ.get("SLACK_BOT_TOKEN", "")
ALLOW_PAID = os.environ.get("ALLOW_PAID_APIS", "False")
if ALLOW_PAID.lower() == "true":
    sys.exit(1)

TODAY = datetime.now(timezone.utc).strftime("%Y-%m-%d")

# ── Employee definitions (structured config — NO hardcoded responses) ──────────
# Each employee: name, title, expertise, personality, channels they belong to

EMPLOYEES = [
    {
        "id": "alex_research",
        "name": "Alex Chen",
        "title": "Senior Research Analyst",
        "expertise": "cross-sectional momentum, factor construction, academic paper implementation",
        "personality": "methodical, cites papers, thinks in Sharpe ratios",
        "channels": ["desk-research", "alpha-research", "general", "squad-alpha-research"],
    },
    {
        "id": "priya_quant",
        "name": "Priya Sharma",
        "title": "Quantitative Strategist",
        "expertise": "statistical arbitrage, cointegration pairs trading, regime detection",
        "personality": "data-driven, loves p-values, skeptical of overfitting",
        "channels": ["desk-research", "alpha-research", "ml-research", "squad-alpha-research"],
    },
    {
        "id": "marcus_risk",
        "name": "Marcus Rivera",
        "title": "Head of Risk",
        "expertise": "Kelly criterion, CVaR, drawdown management, position sizing, correlation limits",
        "personality": "conservative, always asks about tail risk, never skips stress tests",
        "channels": ["risk", "risk-alerts", "desk-research", "leadership", "squad-risk"],
    },
    {
        "id": "sofia_ml",
        "name": "Sofia Petrov",
        "title": "ML Engineer",
        "expertise": "LSTM, XGBoost, Lorentzian KNN, feature engineering, walk-forward validation",
        "personality": "excited about model architectures, practical, hates leakage",
        "channels": ["ml-research", "ml-experiments", "engineering", "squad-ml-modeling"],
    },
    {
        "id": "james_exec",
        "name": "James Kim",
        "title": "Execution Specialist",
        "expertise": "TWAP, VWAP, limit-first algorithms, market microstructure, slippage minimization",
        "personality": "obsessed with basis points, practical, values speed over perfection",
        "channels": ["execution", "desk-equities", "engineering", "squad-execution"],
    },
    {
        "id": "luna_crypto",
        "name": "Luna Nakamura",
        "title": "Crypto Desk Lead",
        "expertise": "Binance perpetuals, funding rate arbitrage, on-chain metrics, liquidation cascades",
        "personality": "fast-moving, monitors 24/7, thinks in funding rates and open interest",
        "channels": ["desk-crypto", "crypto", "alpha-research", "squad-alpha-research"],
    },
    {
        "id": "oliver_backend",
        "name": "Oliver Walsh",
        "title": "Senior Backend Engineer",
        "expertise": "FastAPI async, SQLAlchemy, Redis, WebSocket, Alpaca API integration",
        "personality": "practical, values reliability over cleverness, writes tests first",
        "channels": ["backend", "engineering", "devops", "squad-backend"],
    },
    {
        "id": "nina_frontend",
        "name": "Nina Torres",
        "title": "Frontend Engineer",
        "expertise": "React, TypeScript, TradingView widgets, Lightweight Charts, real-time WebSocket UI",
        "personality": "user-focused, cares about latency, makes ugly data look beautiful",
        "channels": ["frontend", "engineering", "product", "squad-frontend"],
    },
    {
        "id": "raj_tv",
        "name": "Raj Patel",
        "title": "TradingView Indicator Specialist",
        "expertise": "EMA stacks, Squeeze Pro, Wave Trend, VWAP bands, multi-timeframe confluence",
        "personality": "chart obsessed, speaks in indicator names, always tuning parameters",
        "channels": ["desk-tv-indicators", "desk-research", "alpha-research"],
    },
    {
        "id": "ceo_dana",
        "name": "Dana Webb",
        "title": "CEO / Portfolio Manager",
        "expertise": "fund strategy, investor relations, portfolio construction, Sharpe vs benchmark",
        "personality": "big picture thinker, investor pitch ready, keeps focus on outperforming benchmarks",
        "channels": ["general", "leadership", "announcements", "desk-research"],
    },
    {
        "id": "data_eng_kai",
        "name": "Kai Okonkwo",
        "title": "Data Engineer",
        "expertise": "OHLCV pipelines, Redis price cache, yfinance, Binance REST, data quality",
        "personality": "upstream-focused, pedantic about data freshness, loves monitoring dashboards",
        "channels": ["data-engineering", "engineering", "backend", "squad-data"],
    },
    {
        "id": "poly_analyst",
        "name": "Zara Mendez",
        "title": "Polymarket Analyst",
        "expertise": "prediction markets, probability calibration, binary arbitrage, event resolution",
        "personality": "thinks in probabilities, sharp on market microstructure of prediction markets",
        "channels": ["desk-polymarket", "alpha-research", "polymarket"],
    },
]

# ── Slack helpers — delegates to llm_common ───────────────────────────────────

def resolve_channels() -> dict[str, str]:
    """Return {channel_name: channel_id} for all channels."""
    import urllib.request
    if not SLACK_TOKEN:
        return {}
    try:
        req = urllib.request.Request(
            "https://slack.com/api/conversations.list?limit=200&types=public_channel,private_channel",
            headers={"Authorization": f"Bearer {SLACK_TOKEN}"},
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read())
            return {ch["name"]: ch["id"] for ch in data.get("channels", [])}
    except Exception:
        return {}


def post(channel_id: str, text: str, thread_ts: str | None = None) -> str | None:
    result = slack_post(channel_id, text, thread_ts=thread_ts)
    return result.get("ts") if result else None


def read_thread(channel_id: str, thread_ts: str) -> list[dict]:
    """Read actual Slack thread so replies see what was really said."""
    return slack_read_thread(channel_id, thread_ts, limit=15)


# ── Prompt builders ───────────────────────────────────────────────────────────

def build_intro_prompt(employee: dict, channel: str, channel_members: list[dict]) -> str:
    other_names = [e["name"] for e in channel_members if e["id"] != employee["id"]]
    teammates = ", ".join(other_names[:4]) if other_names else "the team"
    return f"""You are {employee['name']}, {employee['title']} at QuantEdge — an AI-powered quantitative trading firm.

Your expertise: {employee['expertise']}
Your personality: {employee['personality']}

Write a brief Slack introduction message for the #{channel} channel.
You are introducing yourself to your teammates ({teammates}) who are also in this channel.
Make it natural, specific to your role, and relevant to what this channel is about.
Mention one specific thing you're working on or excited about right now.
Keep it to 3-5 sentences. Use casual but professional Slack tone. No hashtags or emojis spam."""


def build_reply_prompt(
    replier: dict, intro_author: dict, intro_text: str, channel: str
) -> str:
    return f"""You are {replier['name']}, {replier['title']} at QuantEdge — an AI-powered quantitative trading firm.
Your expertise: {replier['expertise']}
Your personality: {replier['personality']}

Your colleague {intro_author['name']} ({intro_author['title']}) just posted this introduction in #{channel}:
"{intro_text}"

Write a natural, genuine Slack reply. Reference something specific they said.
Ask a relevant follow-up question OR share a related perspective from your own work.
Keep it to 2-3 sentences. Sound like a real colleague, not a bot."""


def build_followup_prompt(
    author: dict, best_reply_author: dict, best_reply_text: str,
    channel: str, all_replies: list[str]
) -> str:
    reply_summary = " | ".join(r[:80] for r in all_replies[:3])
    return f"""You are {author['name']}, {author['title']} at QuantEdge.
Your expertise: {author['expertise']}
Your personality: {author['personality']}

You posted an intro in #{channel}. Your colleagues replied.
{best_reply_author['name']} said: "{best_reply_text}"

All replies so far: {reply_summary}

Write a 2-3 sentence follow-up. Respond to what {best_reply_author['name']} said specifically.
Move the conversation forward — propose something concrete to collaborate on, or share a quick insight.
Sound natural, like a real colleague wrapping up a brief Slack thread."""


# ── Main conversation engine ──────────────────────────────────────────────────

def run_channel_conversations(channel_name: str, channel_id: str, members: list[dict]) -> None:
    """Run full 2-round intro conversation. Thread history injected into each round for genuine continuity."""
    if len(members) < 2:
        print(f"[intros] #{channel_name}: only {len(members)} member(s), skipping")
        return

    print(f"\n[intros] #{channel_name}: {len(members)} members")

    # Round 0: Each member posts their intro
    intros: list[dict] = []

    for emp in members:
        prompt = build_intro_prompt(emp, channel_name, members)
        text = llm(
            prompt,
            system=f"You are {emp['name']}, {emp['title']} at QuantEdge. Sound like a real person on Slack.",
            max_tokens=150,
            temperature=0.85,
            inject_company_context=True,
        )
        if not text or "unavailable" in text:
            print(f"[intros]   {emp['name']}: LLM failed, skipping")
            continue

        formatted = f"*{emp['name']}* | _{emp['title']}_\n{text}"
        ts = post(channel_id, formatted)
        if ts:
            intros.append({"employee": emp, "text": text, "thread_ts": ts})
            print(f"[intros]   {emp['name']}: intro posted (ts={ts})")
        time.sleep(1.5)

    if not intros:
        return

    time.sleep(2)

    # Round 1: Every other member replies — reads ACTUAL thread first (genuine multi-turn)
    for intro in intros:
        author = intro["employee"]
        repliers = [m for m in members if m["id"] != author["id"]]

        # Read actual thread (may have external replies we didn't generate)
        actual_thread = read_thread(channel_id, intro["thread_ts"])
        thread_context = "\n".join(
            f"{m.get('username', 'colleague')}: {m.get('text', '')[:120]}"
            for m in actual_thread[1:]  # skip root message
        )[:600]

        replies: list[dict] = []
        for replier in repliers[:3]:
            prompt = build_reply_prompt(replier, author, intro["text"], channel_name)
            if thread_context:
                prompt += f"\n\nThread so far:\n{thread_context}"

            reply_text = llm(
                prompt,
                system=f"You are {replier['name']}, {replier['title']} at QuantEdge.",
                max_tokens=120,
                temperature=0.85,
                inject_company_context=False,  # already got it in Round 0
            )
            if not reply_text or "unavailable" in reply_text:
                continue

            formatted = f"*{replier['name']}:* {reply_text}"
            post(channel_id, formatted, thread_ts=intro["thread_ts"])
            replies.append({"employee": replier, "text": reply_text})
            print(f"[intros]   {replier['name']} → replied to {author['name']}")
            time.sleep(1.5)

        if not replies:
            continue

        time.sleep(2)

        # Round 2: Original poster follows up — reads full thread AGAIN for true continuity
        actual_thread_r2 = read_thread(channel_id, intro["thread_ts"])
        full_thread_context = "\n".join(
            f"{m.get('username', 'colleague')}: {m.get('text', '')[:120]}"
            for m in actual_thread_r2[1:]
        )[:800]

        best_reply = replies[0]
        prompt = build_followup_prompt(
            author, best_reply["employee"], best_reply["text"],
            channel_name, [r["text"] for r in replies],
        )
        if full_thread_context:
            prompt += f"\n\nFull thread context:\n{full_thread_context}"

        followup = llm(
            prompt,
            system=f"You are {author['name']}, {author['title']} at QuantEdge.",
            max_tokens=120,
            temperature=0.85,
            inject_company_context=False,
        )
        if followup and "unavailable" not in followup:
            formatted = f"*{author['name']}:* {followup}"
            post(channel_id, formatted, thread_ts=intro["thread_ts"])
            print(f"[intros]   {author['name']}: follow-up posted")

            # Write to company brain — what did employees actually discuss?
            memory_write("slack_insights", {
                "summary": f"#{channel_name}: {author['name']} and team discussed: {intro['text'][:100]}",
                "participants": [m["name"] for m in members],
                "channel": channel_name,
            })
        time.sleep(1.5)


def main() -> None:
    if not SLACK_TOKEN:
        print("[intros] No SLACK_BOT_TOKEN — dry run only")
        # Dry-run: print what would happen
        for emp in EMPLOYEES[:3]:
            print(f"  {emp['name']} ({emp['title']}) → channels: {emp['channels']}")
        return

    print(f"[intros] Starting daily employee introductions — {TODAY}")
    print(f"[intros] {len(EMPLOYEES)} employees across multiple channels")

    channel_map = resolve_channels()
    if not channel_map:
        print("[intros] Could not resolve channels — check SLACK_BOT_TOKEN")
        return

    # Build per-channel member list dynamically
    channel_members: dict[str, list[dict]] = {}
    for emp in EMPLOYEES:
        for ch in emp["channels"]:
            channel_members.setdefault(ch, []).append(emp)

    # Run conversations only on channels that exist in Slack
    # Process channels with most members first (richest conversations)
    ordered = sorted(
        [(ch, members) for ch, members in channel_members.items() if ch in channel_map],
        key=lambda x: -len(x[1])
    )

    if not ordered:
        print("[intros] No matching channels found in Slack workspace")
        return

    for channel_name, members in ordered:
        ch_id = channel_map[channel_name]
        run_channel_conversations(channel_name, ch_id, members)
        time.sleep(3)  # pause between channels

    print(f"\n[intros] Done. Conversations run on {len(ordered)} channels.")


if __name__ == "__main__":
    main()
