"""
Render Failure → GitHub Issue Bridge

When a Render deploy fails, this creates/updates a GitHub Issue with the
full error logs. Claude (via the existing pull_request_read MCP tools)
can then read the issue directly without the user copy-pasting errors.

Triggered by:
1. Render webhook (deploy_failed event) → repository_dispatch event
2. Manual workflow_dispatch
3. Render-monitor cron (every 15 min)

Required secrets:
  RENDER_API_KEY     — Render Dashboard → Account Settings → API Keys
  RENDER_SERVICE_ID  — From service URL: dashboard.render.com/web/srv_XXXXXX
  GITHUB_TOKEN       — Auto-provided by GitHub Actions
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import httpx

RENDER_API        = "https://api.render.com/v1"
RENDER_API_KEY    = os.environ.get("RENDER_API_KEY", "")
RENDER_SERVICE_ID = os.environ.get("RENDER_SERVICE_ID", "")
GH_TOKEN          = os.environ.get("GITHUB_TOKEN", "")
GH_REPO           = os.environ.get("GH_REPO", "bahllaavanye-afk/Test")
SLACK_TOKEN       = os.environ.get("SLACK_BOT_TOKEN", "")

ISSUE_TITLE_PREFIX = "🔴 Render Deploy Failure"


def render_get(path: str) -> dict | list | None:
    if not RENDER_API_KEY:
        return None
    try:
        r = httpx.get(
            f"{RENDER_API}{path}",
            headers={"Authorization": f"Bearer {RENDER_API_KEY}", "Accept": "application/json"},
            timeout=20,
        )
        if r.status_code == 200:
            return r.json()
    except Exception as e:
        print(f"Render API error: {e}")
    return None


def gh_request(method: str, path: str, payload: dict | None = None) -> dict | list | None:
    if not GH_TOKEN:
        return None
    try:
        url = f"https://api.github.com/repos/{GH_REPO}{path}"
        headers = {
            "Authorization": f"Bearer {GH_TOKEN}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }
        if method == "GET":
            r = httpx.get(url, headers=headers, timeout=20)
        elif method == "POST":
            r = httpx.post(url, headers=headers, json=payload, timeout=20)
        elif method == "PATCH":
            r = httpx.patch(url, headers=headers, json=payload, timeout=20)
        else:
            return None
        if r.status_code in (200, 201):
            return r.json()
        print(f"GitHub API {r.status_code}: {r.text[:200]}")
    except Exception as e:
        print(f"GitHub API error: {e}")
    return None


def slack(msg: str) -> None:
    if not SLACK_TOKEN:
        return
    try:
        httpx.post(
            "https://slack.com/api/chat.postMessage",
            headers={"Authorization": f"Bearer {SLACK_TOKEN}"},
            json={"channel": "#infra-alerts", "text": msg, "mrkdwn": True},
            timeout=10,
        )
    except Exception:
        pass


def find_or_create_issue(deploy_id: str, status: str, logs: str, commit_msg: str) -> dict | None:
    """Find an existing open issue for Render failures or create a new one."""
    # Search for an existing open issue
    issues = gh_request("GET", "/issues?state=open&labels=render-failure&per_page=10") or []
    matching = next((i for i in issues if ISSUE_TITLE_PREFIX in i.get("title", "")), None)

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    body_lines = [
        f"**Auto-generated by Render Monitor at {timestamp}**",
        "",
        f"**Deploy ID:** `{deploy_id}`",
        f"**Status:** `{status}`",
        f"**Commit:** {commit_msg}",
        "",
        "## Failure Logs (last 100 lines)",
        "",
        "```",
        logs[-8000:] if logs else "(no logs available)",
        "```",
        "",
        "## How to fix",
        "",
        "Claude Code will read this issue automatically and propose a fix.",
        "If the error mentions `Network is unreachable` and an IPv6 address, the fix is:",
        "1. Go to Supabase Dashboard → Settings → Database → Connection pooling",
        "2. Copy the Transaction mode URL (port 6543)",
        "3. Set DATABASE_URL in Render to that pooler URL",
        "",
        "---",
        "_Auto-updated by `.github/scripts/render_failure_issue.py`_",
    ]
    body = "\n".join(body_lines)

    if matching:
        issue_number = matching["number"]
        # Update existing issue
        gh_request("PATCH", f"/issues/{issue_number}", {"body": body})
        print(f"Updated issue #{issue_number}")
        return matching
    else:
        # Create new issue
        new_issue = gh_request("POST", "/issues", {
            "title": f"{ISSUE_TITLE_PREFIX} — {status} on {timestamp}",
            "body": body,
            "labels": ["render-failure", "auto-generated", "bug"],
        })
        if new_issue:
            print(f"Created issue #{new_issue['number']}: {new_issue['html_url']}")
            slack(f"🔴 *Render deploy failed* — Issue created: {new_issue['html_url']}\nClaude will auto-fix shortly.")
        return new_issue


def close_resolved_issues(current_status: str) -> None:
    """If latest deploy is live, close any open render-failure issues."""
    if current_status != "live":
        return
    issues = gh_request("GET", "/issues?state=open&labels=render-failure&per_page=10") or []
    for issue in issues:
        if ISSUE_TITLE_PREFIX in issue.get("title", ""):
            num = issue["number"]
            gh_request("POST", f"/issues/{num}/comments", {
                "body": "✅ Render deploy is now LIVE — closing this issue automatically."
            })
            gh_request("PATCH", f"/issues/{num}", {"state": "closed"})
            print(f"Closed issue #{num} (deploy recovered)")
            slack(f"✅ *Render recovered* — Closed issue #{num}")


def main() -> None:
    if not RENDER_API_KEY:
        print("RENDER_API_KEY not set — add it as a GitHub Secret:")
        print("  1. Render Dashboard → Account Settings → API Keys → Create API Key")
        print("  2. Copy key (rnd_...)")
        print("  3. github.com/bahllaavanye-afk/Test → Settings → Secrets → New repository secret")
        print("     Name: RENDER_API_KEY")
        print("     Value: rnd_...")
        sys.exit(0)  # graceful exit so the workflow doesn't show as failed

    if not RENDER_SERVICE_ID:
        print("RENDER_SERVICE_ID not set")
        print("Get it from your Render service URL: dashboard.render.com/web/srv_XXXXXX")
        sys.exit(0)

    # Get latest deploys
    deploys_data = render_get(f"/services/{RENDER_SERVICE_ID}/deploys?limit=5")
    if not deploys_data or not isinstance(deploys_data, list):
        print("Could not fetch deploys")
        sys.exit(0)

    latest = deploys_data[0].get("deploy", deploys_data[0])
    status     = latest.get("status", "unknown")
    deploy_id  = latest.get("id", "")
    commit_msg = (latest.get("commit", {}) or {}).get("message", "")[:120]

    print(f"Latest deploy: {status} | id={deploy_id} | commit={commit_msg}")

    FAILED = ("failed", "build_failed", "canceled", "update_failed", "pre_deploy_failed")
    if status in FAILED:
        # Get logs
        logs_data = render_get(f"/services/{RENDER_SERVICE_ID}/deploys/{deploy_id}/logs") or []
        if isinstance(logs_data, list):
            logs = "\n".join(item.get("message", "") for item in logs_data[-150:])
        else:
            logs = ""

        find_or_create_issue(deploy_id, status, logs, commit_msg)
    elif status == "live":
        close_resolved_issues(status)
        print("Deploy is live — no action needed")


if __name__ == "__main__":
    main()
