import uuid
from datetime import datetime, date
from sqlalchemy import String, Numeric, DateTime, Date, Boolean, JSON, create_engine
from sqlalchemy.orm import Mapped, mapped_column, sessionmaker
from app.database import Base

class ComparisonResult(Base):
    __tablename__ = "comparison_results"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    strategy_name: Mapped[str] = mapped_column(String(64), nullable=False)
    symbol: Mapped[str] = mapped_column(String(32), nullable=False)
    interval: Mapped[str] = mapped_column(String(8), nullable=False)
    start_date: Mapped[date] = mapped_column(Date, nullable=False)
    end_date: Mapped[date] = mapped_column(Date, nullable=False)

    # Manual strategy metrics
    manual_sharpe: Mapped[float | None] = mapped_column(Numeric(8, 4))
    manual_sortino: Mapped[float | None] = mapped_column(Numeric(8, 4))
    manual_return: Mapped[float | None] = mapped_column(Numeric(10, 4))
    manual_max_dd: Mapped[float | None] = mapped_column(Numeric(8, 4))
    manual_win_rate: Mapped[float | None] = mapped_column(Numeric(6, 4))

    # ML-enhanced strategy metrics
    ml_sharpe: Mapped[float | None] = mapped_column(Numeric(8, 4))
    ml_sortino: Mapped[float | None] = mapped_column(Numeric(8, 4))
    ml_return: Mapped[float | None] = mapped_column(Numeric(10, 4))
    ml_max_dd: Mapped[float | None] = mapped_column(Numeric(8, 4))
    ml_win_rate: Mapped[float | None] = mapped_column(Numeric(6, 4))

    # Benchmark metrics
    spy_sharpe: Mapped[float | None] = mapped_column(Numeric(8, 4))
    spy_return: Mapped[float | None] = mapped_column(Numeric(10, 4))

    # Statistical significance
    t_statistic: Mapped[float | None] = mapped_column(Numeric(8, 4))
    p_value: Mapped[float | None] = mapped_column(Numeric(8, 6))
    is_significant: Mapped[bool | None] = mapped_column(Boolean)
    winner: Mapped[str | None] = mapped_column(String(8))  # manual|ml|neither

    # Full equity curves for chart rendering
    equity_curves: Mapped[dict | None] = mapped_column(JSON)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


# -------------------------------------------------------------------------
# Unit tests for edge/boundary conditions
# -------------------------------------------------------------------------
import unittest

# In‑memory SQLite engine for isolated testing
_engine = create_engine('sqlite:///:memory:', echo=False)
Base.metadata.create_all(_engine)
_Session = sessionmaker(bind=_engine)

class TestComparisonResult(unittest.TestCase):
    def setUp(self):
        self.session = _Session()

    def tearDown(self):
        self.session.close()

    def test_auto_generated_uuid_is_valid(self):
        """Boundary test: ensure the autogenerated id is a valid UUID string."""
        result = ComparisonResult(
            strategy_name="test_strategy",
            symbol="AAPL",
            interval="1d",
            start_date=date(2023, 1, 1),
            end_date=date(2023, 1, 1),
            created_at=datetime.utcnow()
        )
        self.session.add(result)
        self.session.commit()
        # The id should be a non‑empty string that can be parsed as a UUID
        self.assertIsInstance(result.id, str)
        self.assertNotEqual(result.id, "")
        try:
            uuid_obj = uuid.UUID(result.id)
        except ValueError:
            self.fail("Generated id is not a valid UUID")
        self.assertEqual(str(uuid_obj), result.id)

    def test_numeric_precision_and_rounding(self):
        """Edge case: values at the limits of defined precision are stored correctly."""
        max_sharpe = 9999.9999  # 8 total digits, 4 decimal places
        max_return = 99999999.9999  # 10 total digits, 4 decimal places
        result = ComparisonResult(
            strategy_name="precise_strategy",
            symbol="MSFT",
            interval="5m",
            start_date=date(2022, 12, 31),
            end_date=date(2023, 1, 31),
            manual_sharpe=max_sharpe,
            manual_return=max_return,
            created_at=datetime.utcnow()
        )
        self.session.add(result)
        self.session.commit()
        fetched = self.session.get(ComparisonResult, result.id)
        # Stored values should be rounded to the defined scale
        self.assertAlmostEqual(float(fetched.manual_sharpe), max_sharpe, places=4)
        self.assertAlmostEqual(float(fetched.manual_return), max_return, places=4)

    def test_equity_curves_json_storage(self):
        """Boundary test: storing a complex nested dictionary in the JSON column."""
        complex_curve = {
            "dates": ["2023-01-01", "2023-01-02"],
            "values": [100.0, 101.5],
            "metadata": {"source": "simulation", "params": {"alpha": 0.1, "beta": None}}
        }
        result = ComparisonResult(
            strategy_name="json_strategy",
            symbol="GOOG",
            interval="1h",
            start_date=date(2023, 1, 1),
            end_date=date(2023, 1, 2),
            equity_curves=complex_curve,
            created_at=datetime.utcnow()
        )
        self.session.add(result)
        self.session.commit()
        fetched = self.session.get(ComparisonResult, result.id)
        self.assertEqual(fetched.equity_curves, complex_curve)


if __name__ == "__main__":
    unittest.main()