import uuid
from datetime import datetime
from typing import List, Optional, Dict, Any

from sqlalchemy import String, Numeric, DateTime, Boolean, Integer, JSON, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base

# Strategy configuration constants
ENTRY_CONFIDENCE_THRESHOLD: float = 0.70  # Minimum confidence for an entry signal
CONFIRMATION_COUNT: int = 3               # Required consecutive predictions in the same direction
EXIT_CONFIDENCE_DROP: float = 0.20       # Confidence drop that triggers an exit


class MLModel(Base):
    """
    ORM model representing a machine‑learning model used for generating trading signals.

    Attributes
    ----------
    id : str
        Primary key, UUID string.
    name : str
        Human‑readable name of the model.
    model_type : str
        Type of model (e.g., ``lstm``, ``xgboost``, ``lorentzian``, ``tft``, ``ensemble``).
    market_type : str
        Market category (e.g., ``equity``, ``crypto``, ``polymarket``).
    symbol : Optional[str]
        Symbol the model is trained on; ``None`` indicates a multi‑symbol model.
    version : int
        Model version number.
    artifact_path : str
        Filesystem path to stored model artifacts.
    hyperparams : Dict[str, Any]
        Hyper‑parameter dictionary used for training.
    features : List[Any]
        List of feature names used by the model.
    train_start : Optional[datetime]
        Timestamp of the start of the training period.
    train_end : Optional[datetime]
        Timestamp of the end of the training period.
    val_accuracy : Optional[float]
        Validation accuracy metric.
    val_sharpe : Optional[float]
        Validation Sharpe ratio.
    val_loss : Optional[float]
        Validation loss.
    is_active : bool
        Flag indicating if the model is currently active.
    trained_at : datetime
        Timestamp when the model was last trained.
    predictions : List[MLPrediction]
        Collection of predictions generated by this model.
    """

    __tablename__ = "ml_models"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    name: Mapped[str] = mapped_column(String(128), nullable=False)
    model_type: Mapped[str] = mapped_column(String(32), nullable=False)   # lstm|xgboost|lorentzian|tft|ensemble
    market_type: Mapped[str] = mapped_column(String(16), nullable=False)  # equity|crypto|polymarket
    symbol: Mapped[Optional[str]] = mapped_column(String(32))               # None = multi-symbol
    version: Mapped[int] = mapped_column(Integer, default=1)
    artifact_path: Mapped[str] = mapped_column(String(512), nullable=False)
    hyperparams: Mapped[Dict[str, Any]] = mapped_column(JSON, default=dict)
    features: Mapped[List[Any]] = mapped_column(JSON, default=list)
    train_start: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    train_end: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    val_accuracy: Mapped[Optional[float]] = mapped_column(Numeric(6, 4))
    val_sharpe: Mapped[Optional[float]] = mapped_column(Numeric(8, 4))
    val_loss: Mapped[Optional[float]] = mapped_column(Numeric(12, 6))
    is_active: Mapped[bool] = mapped_column(Boolean, default=False)
    trained_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    predictions: Mapped[List["MLPrediction"]] = relationship(
        "MLPrediction", back_populates="model", cascade="all, delete-orphan"
    )

    def latest_prediction(self) -> Optional["MLPrediction"]:
        """
        Return the most recent prediction for this model based on timestamp.

        Returns
        -------
        Optional[MLPrediction]
            The latest prediction if any exist; otherwise ``None``.
        """
        if not self.predictions:
            return None
        return max(self.predictions, key=lambda p: p.ts)

    def is_signal_strong(self, recent: List["MLPrediction"]) -> bool:
        """
        Determine whether recent predictions satisfy the entry criteria.

        The signal is considered strong when:
        1. The latest prediction's confidence exceeds ``ENTRY_CONFIDENCE_THRESHOLD``.
        2. The latest prediction direction is not ``neutral``.
        3. At least ``CONFIRMATION_COUNT`` consecutive recent predictions share the same direction.

        Parameters
        ----------
        recent : List[MLPrediction]
            A list of recent predictions to evaluate.

        Returns
        -------
        bool
            ``True`` if the entry signal meets all criteria; otherwise ``False``.
        """
        if not recent:
            return False

        latest = max(recent, key=lambda p: p.ts)
        if latest.prediction == "neutral" or latest.confidence < ENTRY_CONFIDENCE_THRESHOLD:
            return False

        same_dir_count = 0
        for pred in sorted(recent, key=lambda p: p.ts, reverse=True):
            if pred.prediction == latest.prediction:
                same_dir_count += 1
                if same_dir_count >= CONFIRMATION_COUNT:
                    return True
            else:
                break

        return False

    def should_exit(self, recent: List["MLPrediction"]) -> bool:
        """
        Evaluate whether an exit condition is triggered based on recent predictions.

        Exit is triggered when:
        * Confidence drops below ``ENTRY_CONFIDENCE_THRESHOLD - EXIT_CONFIDENCE_DROP``, or
        * An opposite prediction appears within the recent window.

        Parameters
        ----------
        recent : List[MLPrediction]
            A list of recent predictions to evaluate.

        Returns
        -------
        bool
            ``True`` if an exit condition is met; otherwise ``False``.
        """
        if not recent:
            return False

        latest = max(recent, key=lambda p: p.ts)
        confidence_floor = ENTRY_CONFIDENCE_THRESHOLD - EXIT_CONFIDENCE_DROP
        if latest.confidence < confidence_floor:
            return True

        opposite = {"up": "down", "down": "up"}
        opposite_dir = opposite.get(latest.prediction)
        if opposite_dir:
            for pred in recent:
                if pred.prediction == opposite_dir:
                    return True

        return False


class MLPrediction(Base):
    """
    ORM model representing a single prediction generated by an ``MLModel``.

    Attributes
    ----------
    id : str
        Primary key, UUID string.
    model_id : str
        Foreign key referencing the originating ``MLModel``.
    symbol : str
        Symbol the prediction applies to.
    ts : datetime
        Timestamp of the prediction.
    prediction : str
        Predicted direction (``up``, ``down``, or ``neutral``).
    confidence : float
        Confidence score associated with the prediction.
    feature_values : Dict[str, Any]
        Mapping of feature names to the values used for this prediction.
    actual_outcome : Optional[str]
        Actual outcome recorded after the event; ``None`` if not yet known.
    created_at : datetime
        Record creation timestamp.
    model : MLModel
        Relationship back to the originating model.
    """

    __tablename__ = "ml_predictions"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    model_id: Mapped[str] = mapped_column(
        String,
        ForeignKey("ml_models.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    symbol: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    ts: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, index=True)
    prediction: Mapped[str] = mapped_column(String(8), nullable=False)   # up|down|neutral
    confidence: Mapped[float] = mapped_column(Numeric(5, 4), nullable=False)
    feature_values: Mapped[Dict[str, Any]] = mapped_column(JSON, default=dict)
    actual_outcome: Mapped[Optional[str]] = mapped_column(String(8))        # filled in ex-post
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    model: Mapped["MLModel"] = relationship("MLModel", back_populates="predictions")