import uuid
from sqlalchemy import String, Boolean, create_engine
from sqlalchemy.orm import Mapped, mapped_column, relationship, sessionmaker
from sqlalchemy.exc import IntegrityError
import pytest

from app.database import Base
from app.models.base import TimestampMixin


class User(Base, TimestampMixin):
    __tablename__ = "users"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    email: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)
    hashed_password: Mapped[str] = mapped_column(String(255), nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    is_superuser: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    accounts: Mapped[list["Account"]] = relationship("Account", back_populates="user", lazy="select")


# ------------------- Unit Tests ------------------- #

@pytest.fixture
def session():
    """Create an in‑memory SQLite session for isolated testing."""
    engine = create_engine("sqlite:///:memory:")
    Base.metadata.create_all(engine)
    Session = sessionmaker(bind=engine)
    return Session()


def test_user_default_id_is_uuid(session):
    """Ensure the autogenerated `id` is a valid UUID string."""
    user = User(email="test@example.com", hashed_password="hash")
    session.add(user)
    session.commit()
    # The constructor uses `uuid.uuid4()`; verify it parses back to a UUID object.
    parsed_uuid = uuid.UUID(user.id)
    assert isinstance(parsed_uuid, uuid.UUID)


def test_user_email_uniqueness(session):
    """Verify that the unique constraint on `email` raises an IntegrityError on duplicates."""
    user1 = User(email="duplicate@example.com", hashed_password="hash1")
    user2 = User(email="duplicate@example.com", hashed_password="hash2")
    session.add_all([user1, user2])
    with pytest.raises(IntegrityError):
        session.commit()


def test_user_email_max_length_boundary(session):
    """
    Test the boundary condition for the maximum email length (255 characters).
    The local part is stretched to hit the limit while staying within the allowed size.
    """
    local_part = "a" * 64  # 64 chars + 1 '@' + 11 chars domain = 76 < 255, safe buffer
    domain = "example.com"
    email = f"{local_part}@{domain}"
    assert len(email) <= 255, "Email exceeds defined column length"

    user = User(email=email, hashed_password="hash")
    session.add(user)
    session.commit()

    fetched_user = session.get(User, user.id)
    assert fetched_user is not None
    assert fetched_user.email == email