"""Pre-built bot templates that users can start from."""
from __future__ import annotations

BOT_TEMPLATES: dict[str, dict] = {
    "rsi_oversold_bounce": {
        "name": "RSI Oversold Bounce",
        "description": "Buy when RSI drops below 30 (oversold), exit when RSI recovers to 60",
        "symbol": "SPY",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1h"},
        "conditions": [
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": "<", "value": 30},
            {"type": "time_window", "start_time": "09:30", "end_time": "16:00"},
            {"type": "no_position"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 5, "stop_loss_pct": 2},
        "exit_rules": [
            {"type": "take_profit", "value": 3},
            {"type": "stop_loss", "value": 2},
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": ">", "indicator_value": 60},
        ],
    },
    "momentum_breakout": {
        "name": "Momentum Breakout",
        "description": "Buy when price breaks above 50-day SMA with RSI above 50",
        "symbol": "QQQ",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "price_vs_ma", "ma_period": 50, "operator": ">"},
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": ">", "value": 50},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 10, "stop_loss_pct": 3, "take_profit_pct": 8},
        "exit_rules": [
            {"type": "stop_loss", "value": 3},
            {"type": "take_profit", "value": 8},
        ],
    },
    "mean_reversion_bb": {
        "name": "Bollinger Band Mean Reversion",
        "description": "Buy at lower BB, sell at upper BB",
        "symbol": "AAPL",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1h"},
        "conditions": [
            {"type": "indicator", "indicator": "bb", "operator": "price_below_lower"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 5, "stop_loss_pct": 3},
        "exit_rules": [
            {"type": "indicator", "indicator": "bb", "operator": "price_above_upper"},
            {"type": "stop_loss", "value": 3},
        ],
    },
    "crypto_rsi_dip": {
        "name": "Crypto RSI Dip Buyer",
        "description": "Buy BTC/ETH when RSI(4h) dips below 35",
        "symbol": "BTCUSDT",
        "market_type": "crypto",
        "trigger": {"type": "schedule", "interval": "4h"},
        "conditions": [
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": "<", "value": 35},
            {"type": "no_position"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 3, "stop_loss_pct": 5, "take_profit_pct": 10},
        "exit_rules": [
            {"type": "take_profit", "value": 10},
            {"type": "stop_loss", "value": 5},
        ],
    },
    "volatility_crush": {
        "name": "Post-Earnings Volatility Crush",
        "description": "Alert when IV is elevated before earnings — set up iron condor",
        "symbol": "SPY",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": "<", "value": 70},
        ],
        "condition_logic": "ALL",
        "action": {"type": "send_alert", "alert_message": "IV elevated — consider iron condor"},
        "exit_rules": [],
    },
    "trend_following_ema": {
        "name": "EMA Trend Follow",
        "description": "Long when EMA(20) > EMA(50), short when EMA(20) < EMA(50)",
        "symbol": "SPY",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "ema_cross", "operator": "bullish_cross"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 10, "stop_loss_pct": 2},
        "exit_rules": [
            {"type": "indicator", "indicator": "ema_cross", "operator": "bearish_cross"},
            {"type": "stop_loss", "value": 2},
        ],
    },
    "weekly_cash_secured_put": {
        "name": "Weekly Cash-Secured Put",
        "description": "Sell weekly put on Friday at 0.20 delta (alert only)",
        "symbol": "SPY",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": ">", "value": 40},
        ],
        "condition_logic": "ALL",
        "action": {"type": "send_alert", "alert_message": "Sell 0.20-delta put — check options chain"},
        "exit_rules": [],
    },
    "swing_macd_signal": {
        "name": "MACD Swing Signal",
        "description": "Long when MACD crosses above signal line with RSI between 40-60",
        "symbol": "SPY",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "macd", "operator": "bullish_cross"},
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": ">", "value": 40},
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": "<", "value": 60},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 8, "stop_loss_pct": 2, "take_profit_pct": 5},
        "exit_rules": [
            {"type": "take_profit", "value": 5},
            {"type": "stop_loss", "value": 2},
        ],
    },
    "portfolio_protect": {
        "name": "Portfolio Protection Alert",
        "description": "Send alert when SPY drops >2% in a day",
        "symbol": "SPY",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "5m"},
        "conditions": [
            {"type": "pnl", "operator": "<", "pnl_pct": -2.0},
        ],
        "condition_logic": "ANY",
        "action": {"type": "send_alert", "alert_message": "SPY down >2% today — review portfolio exposure"},
        "exit_rules": [],
    },
    "btc_dominance_alert": {
        "name": "BTC Dominance Signal",
        "description": "Alert when BTC breaks above a resistance level",
        "symbol": "BTCUSDT",
        "market_type": "crypto",
        "trigger": {"type": "price_cross", "price_level": 100000.0, "direction": "above"},
        "conditions": [],
        "condition_logic": "ALL",
        "action": {"type": "send_alert", "alert_message": "BTC broke $100k — consider rotating to altcoins"},
        "exit_rules": [],
    },
    # ── 10 new templates ────────────────────────────────────────────────────
    "adx_trend_filter": {
        "name": "ADX Trend Filter + EMA Cross",
        "description": "Enter long only when ADX > 25 (strong trend) and EMA(20) crosses above EMA(50)",
        "symbol": "SPY",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "adx", "period": 14, "operator": "trend_strong"},
            {
                "type": "indicator",
                "indicator": "ema_cross",
                "operator": "bullish_cross",
                "fast_period": 20,
                "slow_period": 50,
            },
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 8, "stop_loss_pct": 2, "take_profit_pct": 6},
        "exit_rules": [
            {"type": "indicator", "indicator": "ema_cross", "operator": "bearish_cross", "fast_period": 20, "slow_period": 50},
            {"type": "stop_loss", "value": 2},
            {"type": "take_profit", "value": 6},
        ],
    },
    "stochastic_divergence": {
        "name": "Stochastic Divergence Dip Buyer",
        "description": "Buy when Stochastic K < 20 (oversold) and RSI < 40 — double oversold confluence",
        "symbol": "QQQ",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {
                "type": "indicator",
                "indicator": "stoch",
                "operator": "oversold",
                "k_period": 14,
                "d_period": 3,
            },
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": "<", "value": 40},
            {"type": "no_position"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 6, "stop_loss_pct": 3, "take_profit_pct": 7},
        "exit_rules": [
            {"type": "take_profit", "value": 7},
            {"type": "stop_loss", "value": 3},
            {"type": "indicator", "indicator": "stoch", "operator": "overbought", "k_period": 14, "d_period": 3},
        ],
    },
    "cci_reversal": {
        "name": "CCI Oversold + BB Squeeze Reversal",
        "description": "Buy when CCI < -100 (oversold) and price touches lower Bollinger Band",
        "symbol": "AAPL",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "cci", "period": 20, "operator": "oversold"},
            {"type": "indicator", "indicator": "bb", "operator": "price_below_lower"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 5, "stop_loss_pct": 3, "take_profit_pct": 6},
        "exit_rules": [
            {"type": "indicator", "indicator": "cci", "period": 20, "operator": ">", "indicator_value": 100},
            {"type": "stop_loss", "value": 3},
            {"type": "take_profit", "value": 6},
        ],
    },
    "vwap_bounce": {
        "name": "VWAP Bounce with RSI Confirmation",
        "description": "Buy when price dips below VWAP and RSI < 35 — intraday mean reversion",
        "symbol": "SPY",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1h"},
        "conditions": [
            {"type": "indicator", "indicator": "vwap", "operator": "price_below_vwap"},
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": "<", "value": 35},
            {"type": "time_window", "start_time": "09:30", "end_time": "15:30"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 5, "stop_loss_pct": 1.5, "take_profit_pct": 3},
        "exit_rules": [
            {"type": "indicator", "indicator": "vwap", "operator": "price_above_vwap"},
            {"type": "stop_loss", "value": 1.5},
            {"type": "take_profit", "value": 3},
        ],
    },
    "supertrend_follow": {
        "name": "Supertrend Trend Follower",
        "description": "Long when Supertrend is bullish and price is above EMA(50) — trend confirmation",
        "symbol": "SPY",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {
                "type": "indicator",
                "indicator": "supertrend",
                "period": 10,
                "operator": "bullish",
                "multiplier": 3.0,
            },
            {"type": "price_vs_ma", "ma_period": 50, "operator": ">", "ma_type": "ema"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 10, "stop_loss_pct": 2, "take_profit_pct": 8},
        "exit_rules": [
            {"type": "indicator", "indicator": "supertrend", "period": 10, "operator": "bearish", "multiplier": 3.0},
            {"type": "stop_loss", "value": 2},
        ],
    },
    "ichimoku_cloud_breakout": {
        "name": "Ichimoku Cloud Breakout",
        "description": "Long when price breaks above Ichimoku cloud with bullish Tenkan/Kijun cross",
        "symbol": "SPY",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "ichimoku", "operator": "price_above_cloud"},
            {"type": "indicator", "indicator": "ichimoku", "operator": "tenkan_kijun_cross_bull"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 8, "stop_loss_pct": 3, "take_profit_pct": 9},
        "exit_rules": [
            {"type": "indicator", "indicator": "ichimoku", "operator": "price_below_cloud"},
            {"type": "stop_loss", "value": 3},
            {"type": "take_profit", "value": 9},
        ],
    },
    "mfi_volume_confirm": {
        "name": "MFI Volume Exhaustion Reversal",
        "description": "Buy when MFI < 20 (volume exhaustion) — smart money accumulation signal",
        "symbol": "QQQ",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "mfi", "period": 14, "operator": "oversold"},
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": "<", "value": 45},
            {"type": "no_position"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 6, "stop_loss_pct": 3, "take_profit_pct": 8},
        "exit_rules": [
            {"type": "indicator", "indicator": "mfi", "period": 14, "operator": "overbought"},
            {"type": "stop_loss", "value": 3},
            {"type": "take_profit", "value": 8},
        ],
    },
    "momentum_acceleration": {
        "name": "Momentum Acceleration + ADX Strength",
        "description": "Buy when 10-period Rate of Change > 5% and ADX confirms strong trend",
        "symbol": "NVDA",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "momentum", "period": 10, "operator": ">", "value": 5.0},
            {"type": "indicator", "indicator": "adx", "period": 14, "operator": "trend_strong"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 7, "stop_loss_pct": 3, "take_profit_pct": 10},
        "exit_rules": [
            {"type": "indicator", "indicator": "momentum", "period": 10, "operator": "<", "indicator_value": 0},
            {"type": "stop_loss", "value": 3},
            {"type": "take_profit", "value": 10},
        ],
    },
    "multi_indicator_confluence": {
        "name": "Multi-Indicator Confluence Bull",
        "description": "Buy only when RSI, MACD, and Supertrend all agree — high-confidence long signal",
        "symbol": "SPY",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": ">", "value": 50},
            {"type": "indicator", "indicator": "macd", "operator": "bullish_cross"},
            {
                "type": "indicator",
                "indicator": "supertrend",
                "period": 10,
                "operator": "bullish",
                "multiplier": 3.0,
            },
            {"type": "no_position"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 10, "stop_loss_pct": 2, "take_profit_pct": 8},
        "exit_rules": [
            {"type": "indicator", "indicator": "supertrend", "period": 10, "operator": "bearish", "multiplier": 3.0},
            {"type": "indicator", "indicator": "macd", "operator": "bearish_cross"},
            {"type": "stop_loss", "value": 2},
        ],
    },
    "crypto_funding_rate_bot": {
        "name": "Crypto Oversold Accumulator",
        "description": "Buy crypto when RSI < 40 and Stochastic oversold — high funding rate environment dip buyer",
        "symbol": "BTCUSDT",
        "market_type": "crypto",
        "desk": "crypto",
        "trigger": {"type": "schedule", "interval": "4h"},
        "conditions": [
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": "<", "value": 40},
            {
                "type": "indicator",
                "indicator": "stoch",
                "operator": "oversold",
                "k_period": 14,
                "d_period": 3,
            },
            {"type": "no_position"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 4, "stop_loss_pct": 6, "take_profit_pct": 12},
        "exit_rules": [
            {"type": "take_profit", "value": 12},
            {"type": "stop_loss", "value": 6},
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": ">", "indicator_value": 65},
        ],
    },

    # ── OPTIONS DESK ─────────────────────────────────────────────────────────
    "iron_condor_alert": {
        "name": "Iron Condor Setup Alert",
        "description": "Alert when SPY is in a low-IV, range-bound environment — ideal for selling iron condors",
        "symbol": "SPY",
        "market_type": "equity",
        "desk": "options",
        "signal_source": "rule_based",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": ">", "value": 40},
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": "<", "value": 60},
            {"type": "indicator", "indicator": "bb", "operator": "price_inside_bands"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "send_alert", "alert_message": "Iron condor setup: SPY range-bound, sell OTM call+put spreads"},
        "exit_rules": [],
    },
    "covered_call_alert": {
        "name": "Covered Call Opportunity",
        "description": "Alert when holding equity and RSI is overbought — good time to sell covered call",
        "symbol": "SPY",
        "market_type": "equity",
        "desk": "options",
        "signal_source": "rule_based",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": ">", "value": 65},
            {"type": "position_exists"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "send_alert", "alert_message": "Covered call: RSI overbought, sell 30-DTE call at 0.30 delta"},
        "exit_rules": [],
    },
    "credit_spread_alert": {
        "name": "Bull Put Credit Spread Alert",
        "description": "Alert when RSI is oversold — sell put credit spread below support",
        "symbol": "QQQ",
        "market_type": "equity",
        "desk": "options",
        "signal_source": "rule_based",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": "<", "value": 40},
            {"type": "no_position"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "send_alert", "alert_message": "Bull put spread: sell put at support, buy lower strike — target 30% max profit"},
        "exit_rules": [],
    },

    # ── FUTURES DESK ─────────────────────────────────────────────────────────
    "es_futures_breakout": {
        "name": "ES Futures Momentum Breakout",
        "description": "Long ES when price breaks above 20-period high with ADX confirming trend",
        "symbol": "SPY",  # proxy for ES — map to futures symbol in live
        "market_type": "equity",
        "desk": "futures",
        "signal_source": "rule_based",
        "trigger": {"type": "schedule", "interval": "1h"},
        "conditions": [
            {"type": "indicator", "indicator": "adx", "period": 14, "operator": "trend_strong"},
            {"type": "price_vs_ma", "ma_period": 20, "operator": ">"},
            {"type": "time_window", "start_time": "09:30", "end_time": "16:00"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 5, "stop_loss_pct": 1.5, "take_profit_pct": 3},
        "exit_rules": [
            {"type": "stop_loss", "value": 1.5},
            {"type": "take_profit", "value": 3},
            {"type": "time_exit", "hours": 8},
        ],
    },
    "cl_crude_trend": {
        "name": "Crude Oil Supertrend Bot",
        "description": "Trade crude oil (CL) via USO ETF using Supertrend with ATR stop",
        "symbol": "USO",
        "market_type": "equity",
        "desk": "futures",
        "signal_source": "rule_based",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "supertrend", "period": 10, "operator": "bullish", "multiplier": 3.0},
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": ">", "value": 45},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 5, "stop_loss_pct": 3, "take_profit_pct": 8},
        "exit_rules": [
            {"type": "indicator", "indicator": "supertrend", "period": 10, "operator": "bearish", "multiplier": 3.0},
            {"type": "stop_loss", "value": 3},
            {"type": "take_profit", "value": 8},
        ],
    },

    # ── COMMODITIES DESK ─────────────────────────────────────────────────────
    "gold_safe_haven": {
        "name": "Gold Safe Haven Flow",
        "description": "Buy GLD when equities (SPY) are weak — risk-off rotation signal",
        "symbol": "GLD",
        "market_type": "equity",
        "desk": "commodities",
        "signal_source": "rule_based",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": ">", "value": 45},
            {"type": "price_vs_ma", "ma_period": 50, "operator": ">"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 5, "stop_loss_pct": 2, "take_profit_pct": 5},
        "exit_rules": [
            {"type": "stop_loss", "value": 2},
            {"type": "take_profit", "value": 5},
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": ">", "indicator_value": 75},
        ],
    },
    "silver_copper_ratio": {
        "name": "Silver RSI Dip Buyer",
        "description": "Buy SLV (silver) on oversold RSI — mean reversion in commodity cycles",
        "symbol": "SLV",
        "market_type": "equity",
        "desk": "commodities",
        "signal_source": "rule_based",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": "<", "value": 30},
            {"type": "indicator", "indicator": "bb", "operator": "price_below_lower"},
            {"type": "no_position"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 4, "stop_loss_pct": 4, "take_profit_pct": 8},
        "exit_rules": [
            {"type": "take_profit", "value": 8},
            {"type": "stop_loss", "value": 4},
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": ">", "indicator_value": 60},
        ],
    },

    # ── FOREX DESK ───────────────────────────────────────────────────────────
    "usd_strength_trade": {
        "name": "USD Strength Trade (via UUP)",
        "description": "Long UUP (USD Bull ETF) when USD momentum is positive and RSI < 60",
        "symbol": "UUP",
        "market_type": "equity",
        "desk": "fx",
        "signal_source": "rule_based",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "price_vs_ma", "ma_period": 20, "operator": ">", "ma_type": "ema"},
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": "<", "value": 60},
            {"type": "no_position"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 5, "stop_loss_pct": 1.5, "take_profit_pct": 3},
        "exit_rules": [
            {"type": "stop_loss", "value": 1.5},
            {"type": "take_profit", "value": 3},
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": ">", "indicator_value": 70},
        ],
    },

    # ── CRYPTO DESK (additional) ──────────────────────────────────────────────
    "eth_btc_rotation": {
        "name": "ETH/BTC Relative Strength Rotation",
        "description": "Long ETH when it's outperforming BTC — altcoin season signal",
        "symbol": "ETHUSDT",
        "market_type": "crypto",
        "desk": "crypto",
        "signal_source": "rule_based",
        "trigger": {"type": "schedule", "interval": "4h"},
        "conditions": [
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": ">", "value": 50},
            {"type": "price_vs_ma", "ma_period": 20, "operator": ">", "ma_type": "ema"},
            {"type": "no_position"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 3, "stop_loss_pct": 5, "take_profit_pct": 10},
        "exit_rules": [
            {"type": "take_profit", "value": 10},
            {"type": "stop_loss", "value": 5},
        ],
    },
    "btc_ml_hybrid": {
        "name": "BTC ML Hybrid Signal",
        "description": "BTC long when rule conditions pass AND ML model is bullish — highest confidence entries only",
        "symbol": "BTCUSDT",
        "market_type": "crypto",
        "desk": "crypto",
        "signal_source": "hybrid",
        "ml_confidence_threshold": 0.65,
        "trigger": {"type": "schedule", "interval": "4h"},
        "conditions": [
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": ">", "value": 45},
            {"type": "indicator", "indicator": "macd", "operator": "bullish_cross"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 3, "stop_loss_pct": 4, "take_profit_pct": 10},
        "exit_rules": [
            {"type": "take_profit", "value": 10},
            {"type": "stop_loss", "value": 4},
        ],
    },
}
