"""Pre-built bot templates that users can start from."""
from __future__ import annotations

BOT_TEMPLATES: dict[str, dict] = {
    "rsi_oversold_bounce": {
        "name": "RSI Oversold Bounce",
        "description": "Buy when RSI drops below 30 (oversold), exit when RSI recovers to 60",
        "symbol": "SPY",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1h"},
        "conditions": [
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": "<", "value": 30},
            {"type": "time_window", "start_time": "09:30", "end_time": "16:00"},
            {"type": "no_position"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 5, "stop_loss_pct": 2},
        "exit_rules": [
            {"type": "take_profit", "value": 3},
            {"type": "stop_loss", "value": 2},
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": ">", "indicator_value": 60},
        ],
    },
    "momentum_breakout": {
        "name": "Momentum Breakout",
        "description": "Buy when price breaks above 50-day SMA with RSI above 50",
        "symbol": "QQQ",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "price_vs_ma", "ma_period": 50, "operator": ">"},
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": ">", "value": 50},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 10, "stop_loss_pct": 3, "take_profit_pct": 8},
        "exit_rules": [
            {"type": "stop_loss", "value": 3},
            {"type": "take_profit", "value": 8},
        ],
    },
    "mean_reversion_bb": {
        "name": "Bollinger Band Mean Reversion",
        "description": "Buy at lower BB, sell at upper BB",
        "symbol": "AAPL",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1h"},
        "conditions": [
            {"type": "indicator", "indicator": "bb", "operator": "price_below_lower"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 5, "stop_loss_pct": 3},
        "exit_rules": [
            {"type": "indicator", "indicator": "bb", "operator": "price_above_upper"},
            {"type": "stop_loss", "value": 3},
        ],
    },
    "crypto_rsi_dip": {
        "name": "Crypto RSI Dip Buyer",
        "description": "Buy BTC/ETH when RSI(4h) dips below 35",
        "symbol": "BTCUSDT",
        "market_type": "crypto",
        "trigger": {"type": "schedule", "interval": "4h"},
        "conditions": [
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": "<", "value": 35},
            {"type": "no_position"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 3, "stop_loss_pct": 5, "take_profit_pct": 10},
        "exit_rules": [
            {"type": "take_profit", "value": 10},
            {"type": "stop_loss", "value": 5},
        ],
    },
    "volatility_crush": {
        "name": "Post-Earnings Volatility Crush",
        "description": "Alert when IV is elevated before earnings — set up iron condor",
        "symbol": "SPY",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": "<", "value": 70},
        ],
        "condition_logic": "ALL",
        "action": {"type": "send_alert", "alert_message": "IV elevated — consider iron condor"},
        "exit_rules": [],
    },
    "trend_following_ema": {
        "name": "EMA Trend Follow",
        "description": "Long when EMA(20) > EMA(50), short when EMA(20) < EMA(50)",
        "symbol": "SPY",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "ema_cross", "operator": "bullish_cross"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 10, "stop_loss_pct": 2},
        "exit_rules": [
            {"type": "indicator", "indicator": "ema_cross", "operator": "bearish_cross"},
            {"type": "stop_loss", "value": 2},
        ],
    },
    "weekly_cash_secured_put": {
        "name": "Weekly Cash-Secured Put",
        "description": "Sell weekly put on Friday at 0.20 delta (alert only)",
        "symbol": "SPY",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": ">", "value": 40},
        ],
        "condition_logic": "ALL",
        "action": {"type": "send_alert", "alert_message": "Sell 0.20-delta put — check options chain"},
        "exit_rules": [],
    },
    "swing_macd_signal": {
        "name": "MACD Swing Signal",
        "description": "Long when MACD crosses above signal line with RSI between 40-60",
        "symbol": "SPY",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "macd", "operator": "bullish_cross"},
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": ">", "value": 40},
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": "<", "value": 60},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 8, "stop_loss_pct": 2, "take_profit_pct": 5},
        "exit_rules": [
            {"type": "take_profit", "value": 5},
            {"type": "stop_loss", "value": 2},
        ],
    },
    "portfolio_protect": {
        "name": "Portfolio Protection Alert",
        "description": "Send alert when SPY drops >2% in a day",
        "symbol": "SPY",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "5m"},
        "conditions": [
            {"type": "pnl", "operator": "<", "pnl_pct": -2.0},
        ],
        "condition_logic": "ANY",
        "action": {"type": "send_alert", "alert_message": "SPY down >2% today — review portfolio exposure"},
        "exit_rules": [],
    },
    "btc_dominance_alert": {
        "name": "BTC Dominance Signal",
        "description": "Alert when BTC breaks above a resistance level",
        "symbol": "BTCUSDT",
        "market_type": "crypto",
        "trigger": {"type": "price_cross", "price_level": 100000.0, "direction": "above"},
        "conditions": [],
        "condition_logic": "ALL",
        "action": {"type": "send_alert", "alert_message": "BTC broke $100k — consider rotating to altcoins"},
        "exit_rules": [],
    },
    # ── 10 new templates ────────────────────────────────────────────────────
    "adx_trend_filter": {
        "name": "ADX Trend Filter + EMA Cross",
        "description": "Enter long only when ADX > 25 (strong trend) and EMA(20) crosses above EMA(50)",
        "symbol": "SPY",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "adx", "period": 14, "operator": "trend_strong"},
            {
                "type": "indicator",
                "indicator": "ema_cross",
                "operator": "bullish_cross",
                "fast_period": 20,
                "slow_period": 50,
            },
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 8, "stop_loss_pct": 2, "take_profit_pct": 6},
        "exit_rules": [
            {"type": "indicator", "indicator": "ema_cross", "operator": "bearish_cross", "fast_period": 20, "slow_period": 50},
            {"type": "stop_loss", "value": 2},
            {"type": "take_profit", "value": 6},
        ],
    },
    "stochastic_divergence": {
        "name": "Stochastic Divergence Dip Buyer",
        "description": "Buy when Stochastic K < 20 (oversold) and RSI < 40 — double oversold confluence",
        "symbol": "QQQ",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {
                "type": "indicator",
                "indicator": "stoch",
                "operator": "oversold",
                "k_period": 14,
                "d_period": 3,
            },
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": "<", "value": 40},
            {"type": "no_position"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 6, "stop_loss_pct": 3, "take_profit_pct": 7},
        "exit_rules": [
            {"type": "take_profit", "value": 7},
            {"type": "stop_loss", "value": 3},
            {"type": "indicator", "indicator": "stoch", "operator": "overbought", "k_period": 14, "d_period": 3},
        ],
    },
    "cci_reversal": {
        "name": "CCI Oversold + BB Squeeze Reversal",
        "description": "Buy when CCI < -100 (oversold) and price touches lower Bollinger Band",
        "symbol": "AAPL",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "cci", "period": 20, "operator": "oversold"},
            {"type": "indicator", "indicator": "bb", "operator": "price_below_lower"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 5, "stop_loss_pct": 3, "take_profit_pct": 6},
        "exit_rules": [
            {"type": "indicator", "indicator": "cci", "period": 20, "operator": ">", "indicator_value": 100},
            {"type": "stop_loss", "value": 3},
            {"type": "take_profit", "value": 6},
        ],
    },
    "vwap_bounce": {
        "name": "VWAP Bounce with RSI Confirmation",
        "description": "Buy when price dips below VWAP and RSI < 35 — intraday mean reversion",
        "symbol": "SPY",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1h"},
        "conditions": [
            {"type": "indicator", "indicator": "vwap", "operator": "price_below_vwap"},
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": "<", "value": 35},
            {"type": "time_window", "start_time": "09:30", "end_time": "15:30"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 5, "stop_loss_pct": 1.5, "take_profit_pct": 3},
        "exit_rules": [
            {"type": "indicator", "indicator": "vwap", "operator": "price_above_vwap"},
            {"type": "stop_loss", "value": 1.5},
            {"type": "take_profit", "value": 3},
        ],
    },
    "supertrend_follow": {
        "name": "Supertrend Trend Follower",
        "description": "Long when Supertrend is bullish and price is above EMA(50) — trend confirmation",
        "symbol": "SPY",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {
                "type": "indicator",
                "indicator": "supertrend",
                "period": 10,
                "operator": "bullish",
                "multiplier": 3.0,
            },
            {"type": "price_vs_ma", "ma_period": 50, "operator": ">", "ma_type": "ema"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 10, "stop_loss_pct": 2, "take_profit_pct": 8},
        "exit_rules": [
            {"type": "indicator", "indicator": "supertrend", "period": 10, "operator": "bearish", "multiplier": 3.0},
            {"type": "stop_loss", "value": 2},
        ],
    },
    "ichimoku_cloud_breakout": {
        "name": "Ichimoku Cloud Breakout",
        "description": "Long when price breaks above Ichimoku cloud with bullish Tenkan/Kijun cross",
        "symbol": "SPY",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "ichimoku", "operator": "price_above_cloud"},
            {"type": "indicator", "indicator": "ichimoku", "operator": "tenkan_kijun_cross_bull"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 8, "stop_loss_pct": 3, "take_profit_pct": 9},
        "exit_rules": [
            {"type": "indicator", "indicator": "ichimoku", "operator": "price_below_cloud"},
            {"type": "stop_loss", "value": 3},
            {"type": "take_profit", "value": 9},
        ],
    },
    "mfi_volume_confirm": {
        "name": "MFI Volume Exhaustion Reversal",
        "description": "Buy when MFI < 20 (volume exhaustion) — smart money accumulation signal",
        "symbol": "QQQ",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "mfi", "period": 14, "operator": "oversold"},
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": "<", "value": 45},
            {"type": "no_position"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 6, "stop_loss_pct": 3, "take_profit_pct": 8},
        "exit_rules": [
            {"type": "indicator", "indicator": "mfi", "period": 14, "operator": "overbought"},
            {"type": "stop_loss", "value": 3},
            {"type": "take_profit", "value": 8},
        ],
    },
    "momentum_acceleration": {
        "name": "Momentum Acceleration + ADX Strength",
        "description": "Buy when 10-period Rate of Change > 5% and ADX confirms strong trend",
        "symbol": "NVDA",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "momentum", "period": 10, "operator": ">", "value": 5.0},
            {"type": "indicator", "indicator": "adx", "period": 14, "operator": "trend_strong"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 7, "stop_loss_pct": 3, "take_profit_pct": 10},
        "exit_rules": [
            {"type": "indicator", "indicator": "momentum", "period": 10, "operator": "<", "indicator_value": 0},
            {"type": "stop_loss", "value": 3},
            {"type": "take_profit", "value": 10},
        ],
    },
    "multi_indicator_confluence": {
        "name": "Multi-Indicator Confluence Bull",
        "description": "Buy only when RSI, MACD, and Supertrend all agree — high-confidence long signal",
        "symbol": "SPY",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": ">", "value": 50},
            {"type": "indicator", "indicator": "macd", "operator": "bullish_cross"},
            {
                "type": "indicator",
                "indicator": "supertrend",
                "period": 10,
                "operator": "bullish",
                "multiplier": 3.0,
            },
            {"type": "no_position"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 10, "stop_loss_pct": 2, "take_profit_pct": 8},
        "exit_rules": [
            {"type": "indicator", "indicator": "supertrend", "period": 10, "operator": "bearish", "multiplier": 3.0},
            {"type": "indicator", "indicator": "macd", "operator": "bearish_cross"},
            {"type": "stop_loss", "value": 2},
        ],
    },
    "crypto_funding_rate_bot": {
        "name": "Crypto Oversold Accumulator",
        "description": "Buy crypto when RSI < 40 and Stochastic oversold — high funding rate environment dip buyer",
        "symbol": "BTCUSDT",
        "market_type": "crypto",
        "trigger": {"type": "schedule", "interval": "4h"},
        "conditions": [
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": "<", "value": 40},
            {
                "type": "indicator",
                "indicator": "stoch",
                "operator": "oversold",
                "k_period": 14,
                "d_period": 3,
            },
            {"type": "no_position"},
        ],
        "condition_logic": "ALL",
        "action": {"type": "open_long", "size_pct": 4, "stop_loss_pct": 6, "take_profit_pct": 12},
        "exit_rules": [
            {"type": "take_profit", "value": 12},
            {"type": "stop_loss", "value": 6},
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": ">", "indicator_value": 65},
        ],
    },
    # ── Income-focused strategies (lower-risk, premium / carry income) ──────────
    "wheel_covered_call": {
        "name": "The Wheel — Covered Call Income",
        "description": "After assignment, sell 0.30-delta covered calls for weekly premium income (alert-only until options execution lands)",
        "symbol": "SPY",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": ">", "value": 45},
        ],
        "condition_logic": "ALL",
        "action": {"type": "send_alert", "alert_message": "Sell 0.30-delta covered call — collect premium"},
        "exit_rules": [],
    },
    "iron_condor_income": {
        "name": "Iron Condor — Neutral Premium Income",
        "description": "Sell defined-risk iron condors in low-volatility, range-bound markets for theta income",
        "symbol": "SPY",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": ">", "value": 40},
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": "<", "value": 60},
        ],
        "condition_logic": "ALL",
        "action": {"type": "send_alert", "alert_message": "Range-bound + low IV — sell 16-delta iron condor (defined risk)"},
        "exit_rules": [],
    },
    "bull_put_credit_spread": {
        "name": "Bull Put Credit Spread — Defined-Risk Income",
        "description": "Sell a bull put spread above support when trend is up — capped risk, regular credit income (OptionsAlpha 50% take-profit)",
        "symbol": "QQQ",
        "market_type": "equity",
        "trigger": {"type": "schedule", "interval": "1d"},
        "conditions": [
            {"type": "price_vs_ma", "ma_period": 50, "operator": ">"},
            {"type": "indicator", "indicator": "rsi", "period": 14, "operator": ">", "value": 45},
        ],
        "condition_logic": "ALL",
        "action": {"type": "send_alert", "alert_message": "Uptrend — sell 0.25-delta bull put credit spread, take profit at 50%"},
        "exit_rules": [],
    },
    "funding_rate_carry": {
        "name": "Crypto Funding-Rate Carry",
        "description": "Market-neutral: collect positive perpetual funding (long spot / short perp) — carry income, not directional",
        "symbol": "BTCUSDT",
        "market_type": "crypto",
        "trigger": {"type": "schedule", "interval": "1h"},
        "conditions": [],
        "condition_logic": "ALL",
        "action": {"type": "send_alert", "alert_message": "Positive funding — long spot / short perp to collect carry (market-neutral)"},
        "exit_rules": [],
    },
}
