from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any
import logging
import time

logger = logging.getLogger(__name__)


@dataclass(slots=True)
class OrderRequest:
    symbol: str
    side: str               # buy|sell
    order_type: str         # market|limit|stop|bracket
    quantity: float
    limit_price: float | None = None
    stop_price: float | None = None
    stop_loss: float | None = None      # for bracket orders
    take_profit: float | None = None    # for bracket orders
    time_in_force: str = "GTC"
    account_id: str = ""
    strategy_id: str | None = None
    risk_bucket: str = "directional"   # for risk manager routing
    execution_algo: str = "limit_first"  # market|limit_first|twap|vwap


@dataclass(slots=True)
class OrderResult:
    broker_order_id: str
    status: str
    filled_qty: float = 0.0
    avg_fill_price: float | None = None
    raw_payload: dict | None = None


@dataclass(slots=True)
class QuoteResult:
    symbol: str
    bid: float
    ask: float
    last: float
    volume: float | None = None


class AbstractBroker(ABC):
    """Interface that all brokers must implement."""

    @staticmethod
    def _log_trade_metrics(signal_count: int, execution_time: float, pnl: float) -> None:
        """
        Log key trade metrics in a structured manner.

        Parameters
        ----------
        signal_count : int
            Number of signals processed in the operation.
        execution_time : float
            Duration of the operation in seconds.
        pnl : float
            Profit and loss generated by the operation.
        """
        logger.info(
            "Trade metrics",
            extra={
                "signal_count": signal_count,
                "execution_time_seconds": execution_time,
                "pnl": pnl,
            },
        )

    @staticmethod
    def _measure_execution(func):
        """
        Decorator to measure execution time of async broker methods
        and log it using _log_trade_metrics. Sub‑classes can call the
        wrapped method and provide signal_count and pnl values.
        """
        async def wrapper(self, *args, **kwargs):
            start = time.perf_counter()
            result = await func(self, *args, **kwargs)
            elapsed = time.perf_counter() - start
            # Default metrics; subclasses should call _log_trade_metrics with actual values.
            self._log_trade_metrics(signal_count=0, execution_time=elapsed, pnl=0.0)
            return result
        return wrapper

    @abstractmethod
    async def place_order(self, request: OrderRequest) -> OrderResult:
        """Submit an order to the broker. Raises BrokerError on failure."""

    @abstractmethod
    async def cancel_order(self, broker_order_id: str) -> bool:
        """Cancel an open order. Returns True if cancelled."""

    @abstractmethod
    async def get_order(self, broker_order_id: str) -> dict:
        """Get current status of an order."""

    @abstractmethod
    async def get_positions(self) -> list[dict]:
        """Return all open positions."""

    @abstractmethod
    async def get_account(self) -> dict:
        """Return account balance and equity."""

    @abstractmethod
    async def get_quote(self, symbol: str) -> QuoteResult:
        """Return current bid/ask/last for a symbol."""

    @abstractmethod
    async def get_historical(
        self, symbol: str, interval: str, limit: int = 500
    ) -> list[dict]:
        """Return OHLCV bars. Each dict: {ts, open, high, low, close, volume}."""