"""
Strategy Comparison Engine: run manual vs ML-enhanced strategy on same period,
compare against benchmarks, compute statistical significance.

This module defines the data structures and engine used to evaluate and
compare a baseline (manual) strategy against its machine‑learning‑enhanced
counterpart. It fetches benchmark data, runs backtests, and performs a
t‑test to assess whether any observed Sharpe ratio improvement is
statistically significant.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date
from typing import Any, Dict, Optional

import pandas as pd
from scipy import stats

from app.backtest.engine import BacktestMetrics, run_backtest
from app.comparison.benchmarks import fetch_benchmark_curves, get_benchmark_stats
from app.utils.logging import logger


@dataclass
class ComparisonResult:
    """
    Container for the outcome of a strategy comparison run.

    Attributes
    ----------
    strategy_name: str
        Human‑readable name of the strategy being evaluated.
    symbol: str
        Ticker symbol the strategy was applied to.
    interval: str
        Timeframe of the price data (e.g., "15m", "1h").
    start_date: date
        Beginning of the backtest period.
    end_date: date
        End of the backtest period.
    manual: Optional[BacktestMetrics]
        Backtest results for the baseline/manual signal set.
    ml_enhanced: Optional[BacktestMetrics]
        Backtest results for the ML‑enhanced signal set.
    benchmark_curves: Dict[str, Any]
        Raw benchmark equity curves returned by ``fetch_benchmark_curves``.
    benchmark_stats: Dict[str, Any]
        Summary statistics for the benchmarks obtained via ``get_benchmark_stats``.
    ml_improvement_sharpe: float
        Difference in Sharpe ratio (ML – manual), rounded to 4 decimals.
    t_statistic: float
        t‑statistic from the two‑sample t‑test comparing returns.
    p_value: float
        Two‑tailed p‑value from the t‑test, rounded to 6 decimals.
    is_significant: bool
        True if ``p_value`` < 0.05, indicating statistical significance.
    winner: str
        Identifier of the winning approach: "ml", "manual", or "neither".
    """

    strategy_name: str
    symbol: str
    interval: str
    start_date: date
    end_date: date
    manual: Optional[BacktestMetrics] = None
    ml_enhanced: Optional[BacktestMetrics] = None
    benchmark_curves: Dict[str, Any] = field(default_factory=dict)
    benchmark_stats: Dict[str, Any] = field(default_factory=dict)
    ml_improvement_sharpe: float = 0.0
    t_statistic: float = 0.0
    p_value: float = 1.0
    is_significant: bool = False
    winner: str = "neither"


class StrategyComparisonEngine:
    async def run_comparison(
        self,
        manual_signals: pd.Series,
        ml_signals: pd.Series,
        prices: pd.Series,
        strategy_name: str,
        symbol: str,
        interval: str,
        start_date: date,
        end_date: date,
        initial_equity: float = 100_000,
    ) -> ComparisonResult:
        """
        Execute a side‑by‑side comparison of manual and ML‑enhanced strategies.

        The method validates inputs, aligns the time series, runs backtests for
        each signal set, fetches benchmark data, and computes statistical
        significance of any Sharpe ratio improvement.

        Parameters
        ----------
        manual_signals : pd.Series
            Signal series generated by the baseline/manual strategy.
        ml_signals : pd.Series
            Signal series generated by the ML‑enhanced strategy.
        prices : pd.Series
            Historical price series used for backtesting.
        strategy_name : str
            Name of the strategy under test.
        symbol : str
            Trading symbol (e.g., "AAPL").
        interval : str
            Data interval (e.g., "15m").
        start_date : date
            Start date of the backtest period.
        end_date : date
            End date of the backtest period.
        initial_equity : float, optional
            Starting capital for the backtest (default: 100,000).

        Returns
        -------
        ComparisonResult
            Populated result object containing metrics, benchmark information,
            statistical test outcomes, and the identified winner.
        """
        # Input validation
        if not isinstance(manual_signals, pd.Series):
            raise ValueError("manual_signals must be a pandas Series.")
        if not isinstance(ml_signals, pd.Series):
            raise ValueError("ml_signals must be a pandas Series.")
        if not isinstance(prices, pd.Series):
            raise ValueError("prices must be a pandas Series.")

        if manual_signals.empty:
            raise ValueError("manual_signals series cannot be empty.")
        if ml_signals.empty:
            raise ValueError("ml_signals series cannot be empty.")
        if prices.empty:
            raise ValueError("prices series cannot be empty.")

        if not isinstance(strategy_name, str) or not strategy_name.strip():
            raise ValueError("strategy_name must be a non-empty string.")
        if not isinstance(symbol, str) or not symbol.strip():
            raise ValueError("symbol must be a non-empty string.")
        if not isinstance(interval, str) or not interval.strip():
            raise ValueError("interval must be a non-empty string.")

        if not isinstance(start_date, date):
            raise ValueError("start_date must be a datetime.date instance.")
        if not isinstance(end_date, date):
            raise ValueError("end_date must be a datetime.date instance.")
        if start_date > end_date:
            raise ValueError("start_date cannot be later than end_date.")

        if not isinstance(initial_equity, (int, float)):
            raise ValueError("initial_equity must be a numeric type.")
        if initial_equity <= 0:
            raise ValueError("initial_equity must be a positive number.")

        # Align series on the common index
        common_index = manual_signals.index.intersection(ml_signals.index).intersection(prices.index)
        if common_index.empty:
            raise ValueError("manual_signals, ml_signals, and prices must share at least one common index.")
        manual_signals = manual_signals.loc[common_index]
        ml_signals = ml_signals.loc[common_index]
        prices = prices.loc[common_index]

        manual_metrics = run_backtest(manual_signals, prices, initial_equity)
        ml_metrics = run_backtest(ml_signals, prices, initial_equity)

        benchmark_curves = await fetch_benchmark_curves(start_date, end_date)
        benchmark_stats = get_benchmark_stats()

        manual_eq = pd.Series([e["equity"] for e in manual_metrics.equity_curve])
        ml_eq = pd.Series([e["equity"] for e in ml_metrics.equity_curve])
        manual_ret = manual_eq.pct_change().dropna()
        ml_ret = ml_eq.pct_change().dropna()

        min_len = min(len(manual_ret), len(ml_ret))
        if min_len > 10:
            t_stat, p_val = stats.ttest_ind(ml_ret.iloc[:min_len], manual_ret.iloc[:min_len])
        else:
            t_stat, p_val = 0.0, 1.0

        improvement = ml_metrics.sharpe - manual_metrics.sharpe
        winner = "ml" if ml_metrics.sharpe > manual_metrics.sharpe else "manual"
        if abs(improvement) < 0.1:
            winner = "neither"

        logger.info(
            "Comparison complete",
            strategy=strategy_name,
            manual_sharpe=manual_metrics.sharpe,
            ml_sharpe=ml_metrics.sharpe,
            p_value=round(p_val, 4),
        )

        return ComparisonResult(
            strategy_name=strategy_name,
            symbol=symbol,
            interval=interval,
            start_date=start_date,
            end_date=end_date,
            manual=manual_metrics,
            ml_enhanced=ml_metrics,
            benchmark_curves=benchmark_curves,
            benchmark_stats=benchmark_stats,
            ml_improvement_sharpe=round(improvement, 4),
            t_statistic=round(float(t_stat), 4),
            p_value=round(float(p_val), 6),
            is_significant=p_val < 0.05,
            winner=winner,
        )