"""
Strategy Comparison Engine module.

Provides functionality to run a side‑by‑side comparison between a manual trading
signal series and an ML‑enhanced signal series over a specified period. The
engine executes backtests for both strategies, fetches benchmark data, computes
statistical significance, and returns a structured result.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date
from typing import Any, Dict

import pandas as pd
from scipy import stats

from app.backtest.engine import BacktestMetrics, run_backtest
from app.comparison.benchmarks import fetch_benchmark_curves, get_benchmark_stats
from app.utils.logging import logger


@dataclass
class ComparisonResult:
    """
    Holds the outcome of a strategy comparison run.

    Attributes
    ----------
    strategy_name: str
        Human‑readable name of the strategy under test.
    symbol: str
        Ticker symbol for which the comparison was performed.
    interval: str
        Data interval (e.g., ``"1h"``, ``"1d"``).
    start_date: date
        Inclusive start date of the backtest period.
    end_date: date
        Inclusive end date of the backtest period.
    manual: BacktestMetrics | None
        Metrics from the backtest that used the manual signal series.
    ml_enhanced: BacktestMetrics | None
        Metrics from the backtest that used the ML‑enhanced signal series.
    benchmark_curves: Dict[str, Any]
        Benchmark equity curves fetched for the period.
    benchmark_stats: Dict[str, Any]
        Pre‑computed statistics for the benchmarks.
    ml_improvement_sharpe: float
        Difference in Sharpe ratio (ML – manual) rounded to four decimals.
    t_statistic: float
        T‑statistic from the two‑sample t‑test, rounded to four decimals.
    p_value: float
        P‑value from the t‑test, rounded to six decimals.
    is_significant: bool
        Flag indicating whether the p‑value is below the 0.05 significance level.
    winner: str
        Identifier of the winning approach (``"ml"``, ``"manual"``, or ``"neither"``).
    """

    strategy_name: str
    symbol: str
    interval: str
    start_date: date
    end_date: date
    manual: BacktestMetrics | None = None
    ml_enhanced: BacktestMetrics | None = None
    benchmark_curves: Dict[str, Any] = field(default_factory=dict)
    benchmark_stats: Dict[str, Any] = field(default_factory=dict)
    ml_improvement_sharpe: float = 0.0
    t_statistic: float = 0.0
    p_value: float = 1.0
    is_significant: bool = False
    winner: str = "neither"


class StrategyComparisonEngine:
    """Engine that orchestrates the comparison between manual and ML‑enhanced strategies."""

    async def run_comparison(
        self,
        manual_signals: pd.Series,
        ml_signals: pd.Series,
        prices: pd.Series,
        strategy_name: str,
        symbol: str,
        interval: str,
        start_date: date,
        end_date: date,
        initial_equity: float = 100_000,
    ) -> ComparisonResult:
        """
        Execute backtests for both signal series, compare results, and compute significance.

        Parameters
        ----------
        manual_signals : pd.Series
            Signal series generated by the manual strategy.
        ml_signals : pd.Series
            Signal series generated by the ML‑enhanced strategy.
        prices : pd.Series
            Price series used for the backtests.
        strategy_name : str
            Name of the strategy being evaluated.
        symbol : str
            Ticker symbol for the assets under test.
        interval : str
            Data interval (e.g., ``"1h"``, ``"1d"``).
        start_date : date
            Start date of the backtest period (inclusive).
        end_date : date
            End date of the backtest period (inclusive).
        initial_equity : float, default 100_000
            Starting capital for each backtest.

        Returns
        -------
        ComparisonResult
            A populated dataclass containing metrics, benchmark data, statistical test
            results, and the identified winner.
        """
        manual_metrics = run_backtest(manual_signals, prices, initial_equity)
        ml_metrics = run_backtest(ml_signals, prices, initial_equity)

        benchmark_curves = await fetch_benchmark_curves(start_date, end_date)
        benchmark_stats = get_benchmark_stats()

        manual_eq = pd.Series([e["equity"] for e in manual_metrics.equity_curve])
        ml_eq = pd.Series([e["equity"] for e in ml_metrics.equity_curve])
        manual_ret = manual_eq.pct_change().dropna()
        ml_ret = ml_eq.pct_change().dropna()

        min_len = min(len(manual_ret), len(ml_ret))
        if min_len > 10:
            t_stat, p_val = stats.ttest_ind(ml_ret.iloc[:min_len], manual_ret.iloc[:min_len])
        else:
            t_stat, p_val = 0.0, 1.0

        improvement = ml_metrics.sharpe - manual_metrics.sharpe
        winner = "ml" if ml_metrics.sharpe > manual_metrics.sharpe else "manual"
        if abs(improvement) < 0.1:
            winner = "neither"

        logger.info(
            "Comparison complete",
            strategy=strategy_name,
            manual_sharpe=manual_metrics.sharpe,
            ml_sharpe=ml_metrics.sharpe,
            p_value=round(p_val, 4),
        )

        return ComparisonResult(
            strategy_name=strategy_name,
            symbol=symbol,
            interval=interval,
            start_date=start_date,
            end_date=end_date,
            manual=manual_metrics,
            ml_enhanced=ml_metrics,
            benchmark_curves=benchmark_curves,
            benchmark_stats=benchmark_stats,
            ml_improvement_sharpe=round(improvement, 4),
            t_statistic=round(float(t_stat), 4),
            p_value=round(float(p_val), 6),
            is_significant=p_val < 0.05,
            winner=winner,
        )