"""
Strategy Comparison Engine.

This module provides functionality to run a side‑by‑side comparison of a manual
trading strategy against its machine‑learning‑enhanced counterpart over a
specified time window. It executes backtests for both signal sets, fetches
benchmark data, computes statistical significance of any performance
difference, and returns a structured result object.

Typical usage:

    engine = StrategyComparisonEngine()
    result = await engine.run_comparison(
        manual_signals,
        ml_signals,
        price_series,
        strategy_name="my_strategy",
        symbol="AAPL",
        interval="5m",
        start_date=date(2023, 1, 1),
        end_date=date(2023, 6, 30),
    )
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date
from typing import Dict, Any, Optional

import pandas as pd
from scipy import stats

from app.backtest.engine import run_backtest, BacktestMetrics
from app.comparison.benchmarks import fetch_benchmark_curves, get_benchmark_stats
from app.utils.logging import logger


@dataclass
class ComparisonResult:
    """
    Container for the outcome of a strategy comparison.

    Attributes
    ----------
    strategy_name: str
        Human‑readable name of the strategy under test.
    symbol: str
        Ticker symbol the backtests were run on.
    interval: str
        Data granularity (e.g., "1h", "5m").
    start_date: date
        Inclusive start date of the backtest period.
    end_date: date
        Inclusive end date of the backtest period.
    manual: Optional[BacktestMetrics]
        Metrics generated from the manual signal set.
    ml_enhanced: Optional[BacktestMetrics]
        Metrics generated from the ML‑enhanced signal set.
    benchmark_curves: Dict[str, Any]
        Raw benchmark equity curves fetched for the period.
    benchmark_stats: Dict[str, Any]
        Pre‑computed statistics for the benchmarks.
    ml_improvement_sharpe: float
        Difference in Sharpe ratio (ML – manual), rounded to 4 decimals.
    t_statistic: float
        Two‑sample t‑test statistic comparing returns, rounded to 4 decimals.
    p_value: float
        Two‑sample t‑test p‑value, rounded to 6 decimals.
    is_significant: bool
        Whether the p‑value indicates statistical significance (< 0.05).
    winner: str
        Identifier of the better performer ("ml", "manual", or "neither").
    """
    strategy_name: str
    symbol: str
    interval: str
    start_date: date
    end_date: date
    manual: Optional[BacktestMetrics] = None
    ml_enhanced: Optional[BacktestMetrics] = None
    benchmark_curves: Dict[str, Any] = field(default_factory=dict)
    benchmark_stats: Dict[str, Any] = field(default_factory=dict)
    ml_improvement_sharpe: float = 0.0
    t_statistic: float = 0.0
    p_value: float = 1.0
    is_significant: bool = False
    winner: str = "neither"


class StrategyComparisonEngine:
    """Engine responsible for orchestrating strategy comparisons."""

    async def run_comparison(
        self,
        manual_signals: pd.Series,
        ml_signals: pd.Series,
        prices: pd.Series,
        strategy_name: str,
        symbol: str,
        interval: str,
        start_date: date,
        end_date: date,
        initial_equity: float = 100_000,
    ) -> ComparisonResult:
        """
        Execute a comparison between manual and ML‑enhanced signal sets.

        Parameters
        ----------
        manual_signals : pd.Series
            Series of boolean or integer signals generated by the manual strategy.
        ml_signals : pd.Series
            Series of signals generated by the ML‑enhanced strategy.
        prices : pd.Series
            Series of price data aligned with the signals.
        strategy_name : str
            Descriptive name of the strategy being evaluated.
        symbol : str
            Trading symbol (ticker) for which the backtests are run.
        interval : str
            Data interval (e.g., "1h", "15m").
        start_date : date
            Start date of the backtest period.
        end_date : date
            End date of the backtest period.
        initial_equity : float, default 100_000
            Starting capital for the backtests; must be positive.

        Returns
        -------
        ComparisonResult
            Dataclass instance containing backtest metrics, benchmark data,
            statistical test results, and a winner designation.
        """
        # Input validation
        if not isinstance(manual_signals, pd.Series):
            raise ValueError("manual_signals must be a pandas Series.")
        if not isinstance(ml_signals, pd.Series):
            raise ValueError("ml_signals must be a pandas Series.")
        if not isinstance(prices, pd.Series):
            raise ValueError("prices must be a pandas Series.")

        if manual_signals.empty:
            raise ValueError("manual_signals series cannot be empty.")
        if ml_signals.empty:
            raise ValueError("ml_signals series cannot be empty.")
        if prices.empty:
            raise ValueError("prices series cannot be empty.")

        if not isinstance(strategy_name, str) or not strategy_name.strip():
            raise ValueError("strategy_name must be a non-empty string.")
        if not isinstance(symbol, str) or not symbol.strip():
            raise ValueError("symbol must be a non-empty string.")
        if not isinstance(interval, str) or not interval.strip():
            raise ValueError("interval must be a non-empty string.")

        if not isinstance(start_date, date):
            raise ValueError("start_date must be a datetime.date instance.")
        if not isinstance(end_date, date):
            raise ValueError("end_date must be a datetime.date instance.")
        if start_date > end_date:
            raise ValueError("start_date cannot be later than end_date.")

        if not isinstance(initial_equity, (int, float)):
            raise ValueError("initial_equity must be a numeric type.")
        if initial_equity <= 0:
            raise ValueError("initial_equity must be a positive number.")

        # Align series on the common index to ensure consistency
        common_index = manual_signals.index.intersection(ml_signals.index).intersection(prices.index)
        if common_index.empty:
            raise ValueError("manual_signals, ml_signals, and prices must share at least one common index.")
        manual_signals = manual_signals.loc[common_index]
        ml_signals = ml_signals.loc[common_index]
        prices = prices.loc[common_index]

        manual_metrics = run_backtest(manual_signals, prices, initial_equity)
        ml_metrics = run_backtest(ml_signals, prices, initial_equity)

        benchmark_curves = await fetch_benchmark_curves(start_date, end_date)
        benchmark_stats = get_benchmark_stats()

        manual_eq = pd.Series([e["equity"] for e in manual_metrics.equity_curve])
        ml_eq = pd.Series([e["equity"] for e in ml_metrics.equity_curve])
        manual_ret = manual_eq.pct_change().dropna()
        ml_ret = ml_eq.pct_change().dropna()

        min_len = min(len(manual_ret), len(ml_ret))
        if min_len > 10:
            t_stat, p_val = stats.ttest_ind(ml_ret.iloc[:min_len], manual_ret.iloc[:min_len])
        else:
            t_stat, p_val = 0.0, 1.0

        improvement = ml_metrics.sharpe - manual_metrics.sharpe
        winner = "ml" if ml_metrics.sharpe > manual_metrics.sharpe else "manual"
        if abs(improvement) < 0.1:
            winner = "neither"

        logger.info(
            "Comparison complete",
            strategy=strategy_name,
            manual_sharpe=manual_metrics.sharpe,
            ml_sharpe=ml_metrics.sharpe,
            p_value=round(p_val, 4),
        )

        return ComparisonResult(
            strategy_name=strategy_name,
            symbol=symbol,
            interval=interval,
            start_date=start_date,
            end_date=end_date,
            manual=manual_metrics,
            ml_enhanced=ml_metrics,
            benchmark_curves=benchmark_curves,
            benchmark_stats=benchmark_stats,
            ml_improvement_sharpe=round(improvement, 4),
            t_statistic=round(float(t_stat), 4),
            p_value=round(float(p_val), 6),
            is_significant=p_val < 0.05,
            winner=winner,
        )