"""
Research Pipeline — runs every 4 hours via APScheduler.

Pipeline:
  1. Fetch recent market data summary (prices, volumes, regimes)
  2. Call free LLM to identify SOTA research opportunities
  3. Generate experiment configs for promising ideas
  4. Queue experiments to run_experiment.py async subprocess
  5. Store findings in AgentMemory for strategy_generator to act on
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import subprocess
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, List

from pydantic import BaseModel, Field, validator

from app.tasks.free_llm_router import call_race, call_consensus
from app.tasks.agent_memory import AgentMemory

logger = logging.getLogger(__name__)

EXPERIMENTS_DIR = Path(__file__).parent.parent.parent.parent / "experiments"
CONFIGS_DIR = EXPERIMENTS_DIR / "configs"
RESULTS_DIR = EXPERIMENTS_DIR / "results"


class ResearchIdea(BaseModel):
    """
    Schema representing a single research idea generated by the LLM.

    Example:
        {
            "name": "trend_breakout",
            "hypothesis": "EMA crossover on BTC/USDT leads to positive returns",
            "model": "lstm",
            "symbol": "BTC/USDT",
            "interval": "1h",
            "features": ["rsi_14", "macd", "bb_width"]
        }
    """

    name: str = Field(
        ...,
        description="Short identifier for the experiment idea.",
        example="trend_breakout",
    )
    hypothesis: str = Field(
        ...,
        description="Hypothesis that the experiment will test.",
        example="EMA crossover on BTC/USDT leads to positive returns",
    )
    model: str = Field(
        ...,
        description="Model type to be used for the experiment.",
        example="lstm",
    )
    symbol: str = Field(
        ...,
        description="Trading symbol, e.g., BTC/USDT or SPY.",
        example="BTC/USDT",
    )
    interval: str = Field(
        ...,
        description="Data interval for the experiment.",
        example="1h",
    )
    features: List[str] = Field(
        ...,
        description="List of technical feature names required for the experiment.",
        example=["rsi_14", "macd", "bb_width"],
    )

    @validator("model")
    def validate_model(cls, v: str) -> str:
        allowed = {"lstm", "xgboost", "manual"}
        if v not in allowed:
            raise ValueError(f"model must be one of {allowed}")
        return v

    @validator("symbol")
    def validate_symbol(cls, v: str) -> str:
        if "/" in v:
            parts = v.split("/")
            if len(parts) != 2 or not all(parts):
                raise ValueError("symbol with '/' must be in format BASE/QUOTE")
        else:
            if not v.isalpha():
                raise ValueError("symbol without '/' must contain only letters")
        return v

    @validator("interval")
    def validate_interval(cls, v: str) -> str:
        allowed = {"1h", "1d"}
        if v not in allowed:
            raise ValueError(f"interval must be one of {allowed}")
        return v

    @validator("features")
    def validate_features(cls, v: List[str]) -> List[str]:
        if not v:
            raise ValueError("features list must not be empty")
        return v


class ResearchPipeline:
    def __init__(self, redis_client: Any = None):
        self._memory = AgentMemory(redis_client) if redis_client else None

    async def run(self) -> None:
        logger.info("ResearchPipeline: starting 4h research cycle")
        try:
            context = await self._build_market_context()
            ideas = await self._generate_research_ideas(context)
            configs = await self._ideas_to_experiment_configs(ideas)
            await self._queue_experiments(configs)
            if self._memory:
                await self._memory.write(
                    "research_findings",
                    {
                        "ideas_count": len(ideas),
                        "configs_queued": len(configs),
                        "ideas": [idea.dict() for idea in ideas[:3]],
                    },
                )
            logger.info("ResearchPipeline: queued %d experiments", len(configs))
        except Exception as e:
            logger.exception("ResearchPipeline error: %s", e)

    async def _build_market_context(self) -> str:
        """Build a short market context string from memory (if available)."""
        if not self._memory:
            return "Unknown market regime. Assume neutral conditions."
        regime_data = await self._memory.get_latest("market_regime")
        platform_data = await self._memory.get_latest("platform_health")
        recent_suggestions = await self._memory.read_recent("llm_suggestions", n=3)

        regime = regime_data.get("regime", "unknown") if regime_data else "unknown"
        health = platform_data.get("health_ratio", 0.5) if platform_data else 0.5
        prev_ideas = [s.get("suggestion", "")[:100] for s in recent_suggestions]

        return (
            f"Current market regime: {regime}. "
            f"Platform health (% profitable strategies): {health:.0%}. "
            f"Recent LLM suggestions: {'; '.join(prev_ideas[:2])}"
        )

    async def _generate_research_ideas(self, context: str) -> List[ResearchIdea]:
        """Call the free LLM and parse its response into validated ResearchIdea objects."""
        prompt = f"""You are a quantitative trading researcher.

Market context: {context}

Generate 3 experiment ideas to improve trading performance. Each idea must:
- Be implementable with existing indicators (RSI, MACD, EMA, BB, ATR, ADX, VWAP)
- Have a clear hypothesis
- Specify: model type (lstm/xgboost/manual), symbol (BTC/USDT or SPY), interval (1h/1d)

Respond as JSON array:
[{{"name": "idea_name", "hypothesis": "...", "model": "lstm|xgboost|manual", "symbol": "BTC/USDT|SPY", "interval": "1h|1d", "features": ["rsi_14", ...]}}]"""

        response = await call_race(
            messages=[{"role": "user", "content": prompt}],
            temperature=0.5,
            max_tokens=800,
        )
        if not response:
            return []

        try:
            content = response.content.strip()
            start = content.find("[")
            end = content.rfind("]") + 1
            if start >= 0 and end > start:
                raw_ideas = json.loads(content[start:end])
                validated: List[ResearchIdea] = []
                for raw in raw_ideas:
                    try:
                        idea = ResearchIdea(**raw)
                        validated.append(idea)
                    except Exception as e:
                        logger.warning("ResearchPipeline: invalid idea discarded: %s", e)
                return validated
        except Exception as e:
            logger.warning("ResearchPipeline: failed to parse LLM ideas: %s", e)
        return []

    async def _ideas_to_experiment_configs(self, ideas: List[ResearchIdea]) -> List[Path]:
        """Convert validated ideas to YAML experiment config files."""
        CONFIGS_DIR.mkdir(parents=True, exist_ok=True)
        configs: List[Path] = []

        for idea in ideas[:2]:  # limit to 2 per cycle
            name = idea.name or f"auto_{int(time.time())}"
            model = idea.model
            symbol = idea.symbol
            interval = idea.interval
            features = idea.features

            config_path = CONFIGS_DIR / f"{name}.yaml"
            if config_path.exists():
                continue

            yaml_content = f"""# Auto-generated by ResearchPipeline at {datetime.now(timezone.utc).isoformat()}
# Hypothesis: {idea.hypothesis}
experiment:
  name: "{name}"
  model: "{model}"
  symbol: "{symbol}"
  exchange: "{'binance' if '/' in symbol else 'alpaca'}"
  interval: "{interval}"

data:
  train_start: "2022-01-01"
  train_end: "2023-12-31"
  val_start: "2024-01-01"
  val_end: "2024-06-30"
  test_start: "2024-07-01"
  test_end: "2024-12-31"

features:
  technical: {json.dumps(features)}
  lookback: 60

model_params:
  hidden_size: 128
  num_layers: 2
  dropout: 0.3
  bidirectional: true

training:
  epochs: 50
  batch_size: 256
  lr: 0.001
  optimizer: "adamw"
  scheduler: "cosine"
  early_stopping_patience: 8

strategy:
  name: "ml_momentum"
  confidence_threshold: 0.60
"""
            config_path.write_text(yaml_content)
            configs.append(config_path)
            logger.info("ResearchPipeline: created config %s", config_path.name)

        return configs

    async def _queue_experiments(self, configs: List[Path]) -> None:
        """Fire-and-forget experiment runs as background subprocesses."""
        script = EXPERIMENTS_DIR / "run_experiment.py"
        if not script.exists():
            logger.warning("ResearchPipeline: run_experiment.py not found at %s", script)
            return

        for config in configs:
            try:
                subprocess.Popen(
                    ["python", str(script), "--config", config.name],
                    cwd=str(EXPERIMENTS_DIR),
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
                logger.info("ResearchPipeline: queued experiment %s", config.name)
            except Exception as e:
                logger.warning("ResearchPipeline: failed to queue %s: %s", config.name, e)