from __future__ import annotations

import asyncio
import json
import random
from datetime import datetime, timezone
from pathlib import Path
from typing import List

from pydantic import BaseModel, Field, validator

from app.utils.logging import logger

RESEARCH_LOG = Path(__file__).parents[3] / "experiments" / "research_log.jsonl"
RESEARCH_LOG.parent.mkdir(parents=True, exist_ok=True)

RESEARCH_AGENDA = [
    {
        "topic": "yield_curve_momentum",
        "description": "10Y-2Y spread momentum as equity regime signal",
        "data_source": "FRED:T10Y2Y",
        "expected_sharpe": 0.8,
        "complexity": "low",
        "novelty": 0.6,
    },
    {
        "topic": "vix_term_structure_arb",
        "description": "VIX9D/VIX3M ratio for short-vol timing",
        "data_source": "CBOE_public",
        "expected_sharpe": 1.2,
        "complexity": "medium",
        "novelty": 0.7,
    },
    {
        "topic": "crypto_funding_rate_reversion",
        "description": "High funding rate → short perpetual → mean reversion",
        "data_source": "binance_public",
        "expected_sharpe": 1.8,
        "complexity": "medium",
        "novelty": 0.8,
    },
    {
        "topic": "wsb_sentiment_divergence",
        "description": "Apewisdom rank diverges from price action → contrarian trade",
        "data_source": "apewisdom_public",
        "expected_sharpe": 0.9,
        "complexity": "low",
        "novelty": 0.9,
    },
    {
        "topic": "earnings_drift_capture",
        "description": "Pre-earnings drift 5 days before announcement → exit day-1",
        "data_source": "yfinance_calendar",
        "expected_sharpe": 1.1,
        "complexity": "medium",
        "novelty": 0.5,
    },
    {
        "topic": "put_call_ratio_reversal",
        "description": "Extreme put/call ratio → contrarian equity signal",
        "data_source": "CBOE_public",
        "expected_sharpe": 0.7,
        "complexity": "low",
        "novelty": 0.4,
    },
    {
        "topic": "gnn_cross_asset_flow",
        "description": "GNN on cross-asset correlation graph for contagion signals",
        "data_source": "internal_model",
        "expected_sharpe": 2.1,
        "complexity": "high",
        "novelty": 0.95,
    },
    {
        "topic": "llm_earnings_sentiment",
        "description": "LLM analysis of earnings call transcripts for directional signal",
        "data_source": "sec_edgar_public",
        "expected_sharpe": 1.4,
        "complexity": "high",
        "novelty": 0.85,
    },
    {
        "topic": "sector_rotation_momentum",
        "description": "12-1 momentum applied to sector ETFs with monthly rebalance",
        "data_source": "alpaca_paper",
        "expected_sharpe": 0.9,
        "complexity": "low",
        "novelty": 0.3,
    },
    {
        "topic": "polymarket_prediction_arbitrage",
        "description": "YES+NO < $0.97 → buy both for risk-free return",
        "data_source": "polymarket_public",
        "expected_sharpe": 5.0,
        "complexity": "medium",
        "novelty": 0.7,
    },
]


class ResearchFinding(BaseModel):
    """
    Schema representing a single research finding generated by the ResearchScientist.
    """

    topic: str = Field(
        ...,
        description="Unique identifier for the research topic.",
        example="yield_curve_momentum",
    )
    description: str = Field(
        ...,
        description="Human‑readable description of the research hypothesis.",
        example="10Y-2Y spread momentum as equity regime signal",
    )
    estimated_sharpe: float = Field(
        ...,
        ge=0,
        description="Estimated Sharpe ratio for the proposed strategy.",
        example=0.8,
    )
    novelty_score: float = Field(
        ...,
        ge=0,
        le=1,
        description="Novelty of the idea on a 0‑1 scale (higher = more novel).",
        example=0.6,
    )
    complexity: str = Field(
        ...,
        description="Qualitative assessment of implementation complexity.",
        example="low",
    )
    data_source: str = Field(
        ...,
        description="Primary data source used for the signal.",
        example="FRED:T10Y2Y",
    )
    ic_estimate: float = Field(
        ...,
        ge=0,
        description="Information Coefficient estimate (0.05‑0.15 is considered good).",
        example=0.07,
    )
    sample_signal: str = Field(
        ...,
        description="Brief description of the specific signal evaluated.",
        example="IC=0.07, spread > 0.02",
    )
    recommended_action: str = Field(
        ...,
        description="Suggested next step for the research finding.",
        example="backtest",
    )
    confidence: float = Field(
        ...,
        ge=0,
        le=1,
        description="Confidence in the finding on a 0‑1 scale.",
        example=0.85,
    )
    researched_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="ISO‑8601 timestamp when the finding was generated.",
        example="2024-01-01T12:00:00+00:00",
    )

    @validator("recommended_action")
    def validate_action(cls, v: str) -> str:
        allowed = {"backtest", "implement", "monitor", "shelve"}
        if v not in allowed:
            raise ValueError(f"recommended_action must be one of {allowed}")
        return v

    @validator("complexity")
    def validate_complexity(cls, v: str) -> str:
        allowed = {"low", "medium", "high"}
        if v not in allowed:
            raise ValueError(f"complexity must be one of {allowed}")
        return v


class ResearchScientist:
    """
    Principal Research Scientist: continuously identifies alpha sources.
    Runs as background asyncio task every hour.
    """

    def __init__(self, interval_seconds: int = 3600):
        self.interval_seconds = interval_seconds
        self._cycle = 0
        self._findings: List[ResearchFinding] = []

    async def run(self) -> None:
        """Run forever."""
        logger.info("ResearchScientist started", interval=self.interval_seconds)
        while True:
            try:
                findings = await self.research_cycle()
                self._findings.extend(findings)
                # Keep only top 50 findings
                self._findings.sort(
                    key=lambda f: f.estimated_sharpe * f.confidence, reverse=True
                )
                self._findings = self._findings[:50]
            except asyncio.CancelledError:
                break
            except Exception as e:
                logger.error(f"ResearchScientist cycle failed: {e}")
            await asyncio.sleep(self.interval_seconds)

    async def research_cycle(self) -> List[ResearchFinding]:
        """One research cycle: sample topics, evaluate, log."""
        self._cycle += 1
        # Sample 3 topics per cycle (rotate through agenda)
        idx = (self._cycle - 1) % len(RESEARCH_AGENDA)
        topics_to_research = RESEARCH_AGENDA[idx : idx + 3] or RESEARCH_AGENDA[:3]

        findings: List[ResearchFinding] = []
        for topic_def in topics_to_research:
            finding = await self._evaluate_topic(topic_def)
            findings.append(finding)
            self._log_finding(finding)

            if finding.recommended_action in ("backtest", "implement"):
                logger.info(
                    "ResearchScientist: promising alpha found",
                    topic=finding.topic,
                    sharpe=finding.estimated_sharpe,
                    action=finding.recommended_action,
                )

        logger.info(
            "ResearchScientist: cycle complete",
            cycle=self._cycle,
            topics=len(topics_to_research),
            promising=[f.topic for f in findings if f.recommended_action != "shelve"],
        )
        return findings

    async def _evaluate_topic(self, topic_def: dict) -> ResearchFinding:
        """
        Evaluate a research topic. In production this would call real data APIs.
        Currently uses heuristic scoring + IC estimation based on known properties.
        """
        # IC estimation: complexity‑adjusted noise
        base_ic = topic_def["expected_sharpe"] * 0.05  # Sharpe/20 ≈ IC (rough rule of thumb)
        ic_noise = random.gauss(0, 0.01)
        ic = max(0.0, base_ic + ic_noise)

        # Confidence based on data availability and novelty
        novelty = topic_def["novelty"]
        data_confidence = 0.9 if "public" in topic_def["data_source"] else 0.7
        confidence = data_confidence * (1 - novelty * 0.2)  # novel = less prior evidence

        # Recommended action
        if ic > 0.08 and confidence > 0.7:
            action = "implement"
        elif ic > 0.05:
            action = "backtest"
        elif ic > 0.02:
            action = "monitor"
        else:
            action = "shelve"

        sample_signal = f"IC={ic:.3f}, novelty={novelty:.2f}"

        return ResearchFinding(
            topic=topic_def["topic"],
            description=topic_def["description"],
            estimated_sharpe=topic_def["expected_sharpe"],
            novelty_score=novelty,
            complexity=topic_def["complexity"],
            data_source=topic_def["data_source"],
            ic_estimate=ic,
            sample_signal=sample_signal,
            recommended_action=action,
            confidence=confidence,
        )

    def _log_finding(self, finding: ResearchFinding) -> None:
        """Append a JSON representation of the finding to the research log."""
        try:
            with RESEARCH_LOG.open("a") as f:
                json.dump(finding.dict(), f)
                f.write("\n")
        except Exception as e:
            logger.error(f"Failed to log research finding: {e}")