"""
Research Pipeline — runs every 4 hours via APScheduler.

Pipeline:
  1. Fetch recent market data summary (prices, volumes, regimes)
  2. Call free LLM to identify SOTA research opportunities
  3. Generate experiment configs for promising ideas
  4. Queue experiments to run_experiment.py async subprocess
  5. Store findings in AgentMemory for strategy_generator to act on
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import subprocess
import time
import unittest
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, List

from app.tasks.free_llm_router import call_race, call_consensus
from app.tasks.agent_memory import AgentMemory

logger = logging.getLogger(__name__)

EXPERIMENTS_DIR = Path(__file__).parent.parent.parent.parent / "experiments"
CONFIGS_DIR = EXPERIMENTS_DIR / "configs"
RESULTS_DIR = EXPERIMENTS_DIR / "results"


class ResearchPipeline:
    def __init__(self, redis_client: Any = None):
        self._memory = AgentMemory(redis_client) if redis_client else None

    async def run(self) -> None:
        logger.info("ResearchPipeline: starting 4h research cycle")
        try:
            context = await self._build_market_context()
            ideas = await self._generate_research_ideas(context)
            configs = await self._ideas_to_experiment_configs(ideas)
            await self._queue_experiments(configs)
            if self._memory:
                await self._memory.write(
                    "research_findings",
                    {
                        "ideas_count": len(ideas),
                        "configs_queued": len(configs),
                        "ideas": ideas[:3],
                    },
                )
            logger.info("ResearchPipeline: queued %d experiments", len(configs))
        except Exception as e:
            logger.exception("ResearchPipeline error: %s", e)

    async def _build_market_context(self) -> str:
        """Build a short market context string from memory (if available)."""
        if not self._memory:
            return "Unknown market regime. Assume neutral conditions."
        regime_data = await self._memory.get_latest("market_regime")
        platform_data = await self._memory.get_latest("platform_health")
        recent_suggestions = await self._memory.read_recent("llm_suggestions", n=3)

        regime = regime_data.get("regime", "unknown") if regime_data else "unknown"
        health = platform_data.get("health_ratio", 0.5) if platform_data else 0.5
        prev_ideas = [s.get("suggestion", "")[:100] for s in recent_suggestions]

        return (
            f"Current market regime: {regime}. "
            f"Platform health (% profitable strategies): {health:.0%}. "
            f"Recent LLM suggestions: {'; '.join(prev_ideas[:2])}"
        )

    async def _generate_research_ideas(self, context: str) -> List[dict]:
        prompt = f"""You are a quantitative trading researcher.

Market context: {context}

Generate 3 experiment ideas to improve trading performance. Each idea must:
- Be implementable with existing indicators (RSI, MACD, EMA, BB, ATR, ADX, VWAP)
- Have a clear hypothesis
- Specify: model type (lstm/xgboost/manual), symbol (BTC/USDT or SPY), interval (1h/1d)

Respond as JSON array:
[{{"name": "idea_name", "hypothesis": "...", "model": "lstm|xgboost|manual", "symbol": "BTC/USDT|SPY", "interval": "1h|1d", "features": ["rsi_14", ...]}}]"""

        response = await call_race(
            messages=[{"role": "user", "content": prompt}],
            temperature=0.5,
            max_tokens=800,
        )
        if not response:
            return []

        try:
            content = response.content.strip()
            # Extract JSON array
            start = content.find("[")
            end = content.rfind("]") + 1
            if start >= 0 and end > start:
                return json.loads(content[start:end])
        except Exception as e:
            logger.warning("ResearchPipeline: failed to parse LLM ideas: %s", e)
        return []

    async def _ideas_to_experiment_configs(self, ideas: List[dict]) -> List[Path]:
        """Convert LLM ideas to YAML experiment configs."""
        CONFIGS_DIR.mkdir(parents=True, exist_ok=True)
        configs: List[Path] = []

        for idea in ideas[:2]:  # limit to 2 per cycle
            name = idea.get("name", f"auto_{int(time.time())}")
            model = idea.get("model", "lstm")
            symbol = idea.get("symbol", "BTC/USDT")
            interval = idea.get("interval", "1h")
            features = idea.get("features", ["rsi_14", "macd", "bb_width"])

            config_path = CONFIGS_DIR / f"{name}.yaml"
            if config_path.exists():
                continue

            yaml_content = f"""# Auto-generated by ResearchPipeline at {datetime.now(timezone.utc).isoformat()}
# Hypothesis: {idea.get('hypothesis', 'N/A')}
experiment:
  name: "{name}"
  model: "{model}"
  symbol: "{symbol}"
  exchange: "{'binance' if '/' in symbol else 'alpaca'}"
  interval: "{interval}"

data:
  train_start: "2022-01-01"
  train_end: "2023-12-31"
  val_start: "2024-01-01"
  val_end: "2024-06-30"
  test_start: "2024-07-01"
  test_end: "2024-12-31"

features:
  technical: {json.dumps(features)}
  lookback: 60

model_params:
  hidden_size: 128
  num_layers: 2
  dropout: 0.3
  bidirectional: true

training:
  epochs: 50
  batch_size: 256
  lr: 0.001
  optimizer: "adamw"
  scheduler: "cosine"
  early_stopping_patience: 8

strategy:
  name: "ml_momentum"
  confidence_threshold: 0.60
"""
            config_path.write_text(yaml_content)
            configs.append(config_path)
            logger.info("ResearchPipeline: created config %s", config_path.name)

        return configs

    async def _queue_experiments(self, configs: List[Path]) -> None:
        """Fire-and-forget experiment runs as background subprocesses."""
        script = EXPERIMENTS_DIR / "run_experiment.py"
        if not script.exists():
            logger.warning("ResearchPipeline: run_experiment.py not found at %s", script)
            return

        for config in configs:
            try:
                subprocess.Popen(
                    ["python", str(script), "--config", config.name],
                    cwd=str(EXPERIMENTS_DIR),
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
                logger.info("ResearchPipeline: queued experiment %s", config.name)
            except Exception as e:
                logger.warning("ResearchPipeline: failed to queue %s: %s", config.name, e)


# ----------------------------------------------------------------------
# Unit tests for edge‑case behavior
# ----------------------------------------------------------------------
class TestResearchPipelineEdgeCases(unittest.IsolatedAsyncioTestCase):
    async def asyncSetUp(self):
        # Use a temporary directory for config files to keep tests isolated
        self._temp_dir = Path(await asyncio.to_thread(lambda: os.makedirs(
            Path(__file__).parent / "tmp_test_configs", exist_ok=True
        )))
        self.original_config_dir = CONFIGS_DIR
        # Monkey‑patch CONFIGS_DIR to point to the temporary location
        globals()["CONFIGS_DIR"] = Path(__file__).parent / "tmp_test_configs"

    async def asyncTearDown(self):
        # Clean up temporary files
        for child in globals()["CONFIGS_DIR"].iterdir():
            child.unlink()
        globals()["CONFIGS_DIR"] = self.original_config_dir

    async def test_generate_ideas_returns_empty_on_none_response(self):
        """When the LLM returns None, _generate_research_ideas should return an empty list."""
        async def fake_call_race(*args, **kwargs):
            return None

        # Patch the call_race function
        original = globals()["call_race"]
        globals()["call_race"] = fake_call_race
        pipeline = ResearchPipeline()
        ideas = await pipeline._generate_research_ideas("dummy context")
        self.assertIsInstance(ideas, list)
        self.assertEqual(len(ideas), 0)
        # Restore original function
        globals()["call_race"] = original

    async def test_generate_ideas_handles_malformed_json(self):
        """Malformed JSON from the LLM should be caught and result in an empty list."""
        class BadResponse:
            content = "Here is my answer: not a json array"

        async def fake_call_race(*args, **kwargs):
            return BadResponse()

        original = globals()["call_race"]
        globals()["call_race"] = fake_call_race
        pipeline = ResearchPipeline()
        ideas = await pipeline._generate_research_ideas("dummy context")
        self.assertEqual(ideas, [])
        globals()["call_race"] = original

    async def test_ideas_to_experiment_configs_with_empty_ideas(self):
        """Passing an empty ideas list should not raise and return an empty config list."""
        pipeline = ResearchPipeline()
        configs = await pipeline._ideas_to_experiment_configs([])
        self.assertIsInstance(configs, list)
        self.assertEqual(len(configs), 0)

    async def test_ideas_to_experiment_configs_avoids_overwrite(self):
        """If a config file already exists, it should be skipped, not overwritten."""
        pipeline = ResearchPipeline()
        # Prepare a dummy idea
        idea = {
            "name": "test_duplicate",
            "model": "lstm",
            "symbol": "BTC/USDT",
            "interval": "1h",
            "features": ["rsi_14"],
            "hypothesis": "test hypothesis",
        }
        # Create a file with the same name beforehand
        preexisting_path = CONFIGS_DIR / "test_duplicate.yaml"
        preexisting_path.parent.mkdir(parents=True, exist_ok=True)
        preexisting_path.write_text("preexisting content")

        configs = await pipeline._ideas_to_experiment_configs([idea])
        # The function should skip the existing file, returning an empty list
        self.assertEqual(configs, [])
        # Ensure the original content was not altered
        self.assertEqual(preexisting_path.read_text(), "preexisting content")


if __name__ == "__main__":
    unittest.main()