"""Daily morning standup — every team lead posts their overnight summary.

Runs at 09:00 UTC. Each team lead:
  1. Reads their domain metrics from Redis / DB
  2. Generates a standup report via the rule engine (or free LLM if key is set)
  3. Posts a Slack thread in their channel; team members reply in the thread

No Slack token → logs to the structlog output instead so the system still
"runs the standup" in paper/dev mode without a Slack workspace.
"""
from __future__ import annotations

import json
from datetime import UTC, datetime, timedelta

from app.utils.logging import logger

# Team lead → {channel, domain, emoji, members}
TEAM_LEADS: list[dict] = [
    {
        "lead": "alpha_dir",
        "channel": "desk-research",
        "emoji": "📈",
        "domain": "strategies",
        "task_type": "evaluate_strategies",
        "members": ["momentum_quant", "stat_arb_desk", "equity_lead"],
    },
    {
        "lead": "ml_lead",
        "channel": "ml-research",
        "emoji": "🧬",
        "domain": "ml-models",
        "task_type": "evaluate_models",
        "members": ["feature_engineer", "model_validator", "ml_researcher"],
    },
    {
        "lead": "risk_eng",
        "channel": "risk",
        "emoji": "🛡️",
        "domain": "risk",
        "task_type": "risk_check",
        "members": ["cro", "portfolio_manager"],
    },
    {
        "lead": "exec_eng",
        "channel": "desk-equities",
        "emoji": "⚡",
        "domain": "execution",
        "task_type": "slippage_analysis",
        "members": ["market_maker", "arb_trader"],
    },
    {
        "lead": "backend_lead",
        "channel": "engineering",
        "emoji": "⚙️",
        "domain": "data-pipeline",
        "task_type": "fetch_ohlcv",
        "members": ["data_engineer_2", "infra_lead", "devops_dir"],
    },
    {
        "lead": "vp_research",
        "channel": "desk-research",
        "emoji": "🔭",
        "domain": "alpha-mining",
        "task_type": "alpha_mining",
        "members": ["quant_researcher", "alt_data_lead", "research_scientist"],
    },
]


async def _get_task_context(task_type: str, db_session_factory) -> dict:
    """Fetch the most recent completed task result for this type from the DB."""
    try:
        from sqlalchemy import select

        from app.models.task import Task, TaskStatus

        since = datetime.now(UTC) - timedelta(hours=24)
        async with db_session_factory() as db:
            result = await db.execute(
                select(Task)
                .where(Task.task_type == task_type)
                .where(Task.status == TaskStatus.completed)
                .where(Task.created_at >= since)
                .order_by(Task.created_at.desc())
                .limit(1)
            )
            task = result.scalar_one_or_none()
            if task and task.result:
                return task.result if isinstance(task.result, dict) else json.loads(task.result)
    except Exception as exc:
        logger.debug("standup: could not fetch task context", task_type=task_type, error=str(exc))
    return {"task_type": task_type, "status": "no_recent_data"}


async def _generate_standup_report(team: dict, context: dict) -> dict:
    """Generate standup content for a team lead using the rule engine or free LLM."""
    from app.llm.employees import reason_about_task

    report = await reason_about_task(team["task_type"], context)
    return report


def _format_slack_thread(team: dict, report: dict, context: dict) -> str:
    """Format a standup message for Slack."""
    now = datetime.now(UTC).strftime("%A %Y-%m-%d")
    lead = team["lead"]
    emoji = team["emoji"]
    members = " ".join(f"@{m}" for m in team["members"])

    analysis = report.get("analysis", "No analysis available.")
    recs = report.get("recommendations", [])
    source = report.get("source", "llm")
    source_label = "⚙️ rule-engine" if source == "rule_engine" else "🤖 LLM"

    lines = [
        f"{emoji} *Good morning from {lead}* — {now}",
        "",
        f"📋 *Domain:* {team['domain']}",
        "",
        f"*Overnight Summary:*",
        analysis,
        "",
    ]

    if recs:
        lines.append("*Action Items for Today:*")
        for i, r in enumerate(recs, 1):
            lines.append(f"{i}. {r}")
        lines.append("")

    lines.append(f"{members} — please reply with your updates below 👇")
    lines.append(f"_Report generated by {source_label}_")

    return "\n".join(lines)


async def _post_to_slack(channel: str, text: str) -> bool:
    """Post a message to Slack. Returns True if successful."""
    try:
        from app.config import settings as _settings
        token = getattr(_settings, "slack_bot_token", "") or ""
        if not token:
            return False

        import httpx
        async with httpx.AsyncClient(timeout=10.0) as client:
            resp = await client.post(
                "https://slack.com/api/chat.postMessage",
                headers={"Authorization": f"Bearer {token}"},
                json={"channel": f"#{channel}", "text": text},
            )
            data = resp.json()
            return data.get("ok", False)
    except Exception as exc:
        logger.debug("standup: Slack post failed", error=str(exc))
        return False


async def run_daily_standup(db_session_factory=None) -> dict:
    """Run the daily standup for all teams. Returns a summary of what was posted."""
    if db_session_factory is None:
        try:
            from app.database import AsyncSessionLocal
            db_session_factory = AsyncSessionLocal
        except Exception:
            pass

    summary = {"date": datetime.now(UTC).isoformat(), "teams": [], "slack_posts": 0}

    for team in TEAM_LEADS:
        try:
            context = {}
            if db_session_factory:
                context = await _get_task_context(team["task_type"], db_session_factory)

            report = await _generate_standup_report(team, context)
            message = _format_slack_thread(team, report, context)

            posted = await _post_to_slack(team["channel"], message)
            if posted:
                summary["slack_posts"] += 1

            team_summary = {
                "lead": team["lead"],
                "channel": team["channel"],
                "analysis": report.get("analysis", "")[:200],
                "recommendations_count": len(report.get("recommendations", [])),
                "slack_posted": posted,
                "source": report.get("source", "unknown"),
            }
            summary["teams"].append(team_summary)

            logger.info(
                "standup: team report generated",
                lead=team["lead"],
                channel=team["channel"],
                slack_posted=posted,
                source=report.get("source"),
            )

        except Exception as exc:
            logger.error("standup: team report failed", lead=team["lead"], error=str(exc))
            summary["teams"].append({"lead": team["lead"], "error": str(exc)})

    logger.info(
        "Daily standup complete",
        teams=len(summary["teams"]),
        slack_posts=summary["slack_posts"],
    )
    return summary
