"""initial_schema

Revision ID: ee1a38997dca
Revises: 
Create Date: 2026-05-27 11:22:52.464759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1a38997dca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparison_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('manual_sharpe', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('manual_sortino', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('manual_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('manual_max_dd', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('manual_win_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('ml_sharpe', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('ml_sortino', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('ml_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ml_max_dd', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('ml_win_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('spy_sharpe', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('spy_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('t_statistic', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('p_value', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('is_significant', sa.Boolean(), nullable=True),
    sa.Column('winner', sa.String(length=8), nullable=True),
    sa.Column('equity_curves', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('val_accuracy', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('val_sharpe', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('test_sharpe', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('artifact_path', sa.String(length=512), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metrics_history', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ml_models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('model_type', sa.String(length=32), nullable=False),
    sa.Column('market_type', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('artifact_path', sa.String(length=512), nullable=False),
    sa.Column('hyperparams', sa.JSON(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('train_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('train_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('val_accuracy', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('val_sharpe', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('val_loss', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ohlcv',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ohlcv_symbol_exchange_interval_ts', 'ohlcv', ['symbol', 'exchange', 'interval', 'ts'], unique=True)
    op.create_index('ix_ohlcv_ts', 'ohlcv', ['ts'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('broker', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('encrypted_key', sa.String(length=1024), nullable=True),
    sa.Column('encrypted_secret', sa.String(length=1024), nullable=True),
    sa.Column('extra_config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_predictions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prediction', sa.String(length=8), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('feature_values', sa.JSON(), nullable=False),
    sa.Column('actual_outcome', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_predictions_model_id'), 'ml_predictions', ['model_id'], unique=False)
    op.create_index(op.f('ix_ml_predictions_symbol'), 'ml_predictions', ['symbol'], unique=False)
    op.create_index(op.f('ix_ml_predictions_ts'), 'ml_predictions', ['ts'], unique=False)
    op.create_table('account_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_equity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cash', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_snapshots_ts'), 'account_snapshots', ['ts'], unique=False)
    op.create_table('backtest_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('total_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('annualized_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('calmar_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('equity_curve', sa.JSON(), nullable=True),
    sa.Column('trades_log', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('positions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'symbol')
    )
    op.create_table('risk_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('risk_bucket', sa.String(length=16), nullable=True),
    sa.Column('threshold', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('market_type', sa.String(length=16), nullable=False),
    sa.Column('strategy_type', sa.String(length=16), nullable=False),
    sa.Column('risk_bucket', sa.String(length=16), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('tick_interval_seconds', sa.Float(), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=True),
    sa.Column('broker_order_id', sa.String(length=128), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('filled_qty', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('avg_fill_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('time_in_force', sa.String(length=8), nullable=False),
    sa.Column('execution_algo', sa.String(length=32), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('take_profit_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('stop_loss_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('trailing_stop_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('notional', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('bracket_parent_id', sa.String(), nullable=True),
    sa.Column('risk_reward_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bracket_parent_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_account_created', 'orders', ['account_id', 'created_at'], unique=False)
    op.create_index('ix_orders_account_status', 'orders', ['account_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_broker_order_id'), 'orders', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_index('ix_orders_symbol_status', 'orders', ['symbol', 'status'], unique=False)
    op.create_table('risk_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value_at_trigger', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('action_taken', sa.String(length=64), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['risk_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=True),
    sa.Column('strategy_name', sa.String(length=128), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fees', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hold_seconds', sa.Integer(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trades_account_closed', 'trades', ['account_id', 'closed_at'], unique=False)
    op.create_index(op.f('ix_trades_account_id'), 'trades', ['account_id'], unique=False)
    op.create_index(op.f('ix_trades_closed_at'), 'trades', ['closed_at'], unique=False)
    op.create_index('ix_trades_strategy_closed', 'trades', ['strategy_id', 'closed_at'], unique=False)
    op.create_index(op.f('ix_trades_strategy_id'), 'trades', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_trades_strategy_name'), 'trades', ['strategy_name'], unique=False)
    op.create_table('fills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fee', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fee_currency', sa.String(length=16), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slippage_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('signal_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('expected_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('fill_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('slippage_bps', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('execution_algo', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slippage_records_order_id'), 'slippage_records', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slippage_records_order_id'), table_name='slippage_records')
    op.drop_table('slippage_records')
    op.drop_table('fills')
    op.drop_index(op.f('ix_trades_strategy_name'), table_name='trades')
    op.drop_index(op.f('ix_trades_strategy_id'), table_name='trades')
    op.drop_index('ix_trades_strategy_closed', table_name='trades')
    op.drop_index(op.f('ix_trades_closed_at'), table_name='trades')
    op.drop_index(op.f('ix_trades_account_id'), table_name='trades')
    op.drop_index('ix_trades_account_closed', table_name='trades')
    op.drop_table('trades')
    op.drop_table('risk_events')
    op.drop_index('ix_orders_symbol_status', table_name='orders')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_broker_order_id'), table_name='orders')
    op.drop_index('ix_orders_account_status', table_name='orders')
    op.drop_index('ix_orders_account_created', table_name='orders')
    op.drop_table('orders')
    op.drop_table('strategies')
    op.drop_table('risk_rules')
    op.drop_table('positions')
    op.drop_table('backtest_results')
    op.drop_index(op.f('ix_account_snapshots_ts'), table_name='account_snapshots')
    op.drop_table('account_snapshots')
    op.drop_index(op.f('ix_ml_predictions_ts'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_symbol'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_model_id'), table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_ohlcv_ts', table_name='ohlcv')
    op.drop_index('ix_ohlcv_symbol_exchange_interval_ts', table_name='ohlcv')
    op.drop_table('ohlcv')
    op.drop_table('ml_models')
    op.drop_table('experiments')
    op.drop_table('comparison_results')
    # ### end Alembic commands ###
