#!/usr/bin/env python3
"""Generate docs/WORKFLOWS.md — the "employee manifest" for the ~86 GitHub Actions.

Read-only inventory: for every workflow it records name, triggers (cron cadence +
event types) and a one-line purpose, then groups by name-prefix to surface
duplicate "families" (slack-*, agent-*, render-*, ...) that are consolidation
candidates. Deletes nothing — this is the safe first step of the workflow audit.

Run: python scripts/gen_workflow_manifest.py
"""
from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
WF_DIR = REPO / ".github" / "workflows"
OUT = REPO / "docs" / "WORKFLOWS.md"

_EVENTS = [
    "schedule", "workflow_dispatch", "workflow_run", "push", "pull_request",
    "pull_request_target", "issues", "issue_comment", "repository_dispatch",
    "check_suite", "deployment_status",
]


def parse(path: Path) -> dict:
    text = path.read_text(encoding="utf-8", errors="replace")
    name_m = re.search(r"(?m)^name:\s*(.+?)\s*$", text)
    name = name_m.group(1).strip().strip('"\'') if name_m else path.stem
    crons = re.findall(r'(?m)^\s*-\s*cron:\s*["\']?([^"\'\n]+)["\']?', text)
    triggers = [e for e in _EVENTS if re.search(rf"(?m)^\s+{e}:", text)]
    # purpose: first non-empty comment line, else the workflow name
    purpose = name
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("#") and len(s) > 2:
            purpose = s.lstrip("# ").strip()
            break
    return {"file": path.name, "name": name, "crons": crons,
            "triggers": triggers, "purpose": purpose}


def main() -> None:
    files = sorted(WF_DIR.glob("*.yml")) + sorted(WF_DIR.glob("*.yaml"))
    rows = [parse(f) for f in files]

    families: dict[str, list[str]] = {}
    for r in rows:
        prefix = r["file"].split("-")[0]
        families.setdefault(prefix, []).append(r["file"])
    dup_families = {k: v for k, v in sorted(families.items()) if len(v) >= 3}

    scheduled = [r for r in rows if r["crons"]]

    lines: list[str] = []
    lines.append("# QuantEdge — Workflow / Employee Manifest")
    lines.append("")
    lines.append("> Auto-generated by `scripts/gen_workflow_manifest.py`. Read-only inventory of")
    lines.append("> every GitHub Actions workflow (the autonomous 'employees') so cadence and overlap")
    lines.append("> are legible. Regenerate after adding/removing a workflow.")
    lines.append("")
    lines.append(f"**Total workflows:** {len(rows)}  |  **Scheduled (cron):** {len(scheduled)}")
    lines.append("")
    lines.append("## Consolidation candidates (families with ≥3 workflows)")
    lines.append("")
    if dup_families:
        for prefix, members in dup_families.items():
            lines.append(f"- **`{prefix}-*`** ({len(members)}): {', '.join(members)}")
    else:
        lines.append("_None._")
    lines.append("")
    lines.append("## All workflows")
    lines.append("")
    lines.append("| Workflow file | Name | Cron | Triggers | Purpose |")
    lines.append("|---|---|---|---|---|")
    for r in rows:
        cron = "<br>".join(f"`{c}`" for c in r["crons"]) or "—"
        trig = ", ".join(t for t in r["triggers"] if t != "schedule") or "—"
        purpose = r["purpose"].replace("|", "\\|")[:110]
        lines.append(f"| `{r['file']}` | {r['name'][:48]} | {cron} | {trig} | {purpose} |")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(REPO)} — {len(rows)} workflows, "
          f"{len(scheduled)} scheduled, {len(dup_families)} dup-families")


if __name__ == "__main__":
    main()
