#!/usr/bin/env bash
# One-time setup: configure Codex desktop to use xAI Grok via OpenRouter.
# Run: bash scripts/setup_codex.sh
# Requires: OPENROUTER_API_KEY set in your environment or .env

set -euo pipefail

CODEX_DIR="$HOME/.codex"
CODEX_CFG="$CODEX_DIR/config.toml"
mkdir -p "$CODEX_DIR"

# Pull key from env or .env file
if [ -z "${OPENROUTER_API_KEY:-}" ] && [ -f .env ]; then
  export "$(grep OPENROUTER_API_KEY .env | xargs)" 2>/dev/null || true
fi

if [ -z "${OPENROUTER_API_KEY:-}" ]; then
  echo "⚠️  OPENROUTER_API_KEY not set. Get a free key at openrouter.ai"
  echo "    Set it: export OPENROUTER_API_KEY=sk-or-..."
  exit 1
fi

cat > "$CODEX_CFG" << TOML
# QuantEdge — Codex Desktop User Config (auto-generated by setup_codex.sh)
# Uses xAI Grok Build 0.1 via OpenRouter as the coding engine

model = "x-ai/grok-build-0.1"
model_provider = "openrouter"

[model_providers.openrouter]
name = "OpenRouter → xAI Grok"
base_url = "https://openrouter.ai/api/v1"
api_key = "${OPENROUTER_API_KEY}"
wire_api = "chat"

[model_providers.openrouter.headers]
"HTTP-Referer" = "https://quantedge.ai"
"X-Title" = "QuantEdge"
TOML

# Substitute actual key
sed -i "s|\${OPENROUTER_API_KEY}|${OPENROUTER_API_KEY}|" "$CODEX_CFG"

echo "✅  Codex configured → $CODEX_CFG"
echo "    Model: x-ai/grok-build-0.1 via OpenRouter"
echo "    Restart Codex desktop to apply."
