#!/usr/bin/env bash
# Configure Codex desktop to use xAI Grok Build 0.1 via OpenRouter.
# Run: bash scripts/setup_codex.sh
#
# Key is resolved automatically — no manual export needed:
#   1. OPENROUTER_API_KEY already in current environment
#   2. .env file (repo root or current directory)
#   3. .claude/settings.local.json (Claude Code local settings)
#   4. OPENROUTER_API_KEY_2 as fallback

set -uo pipefail

CODEX_DIR="$HOME/.codex"
CODEX_CFG="$CODEX_DIR/config.toml"
mkdir -p "$CODEX_DIR"

# ── 1. Already in environment ─────────────────────────────────────────────────
KEY="${OPENROUTER_API_KEY:-}"

# ── 2. .env file (try repo root, then cwd) ────────────────────────────────────
if [ -z "$KEY" ]; then
  REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo "$PWD")"
  for env_path in "$REPO_ROOT/.env" ".env" "$HOME/.env"; do
    if [ -f "$env_path" ]; then
      MAYBE=$(grep -E '^OPENROUTER_API_KEY=' "$env_path" 2>/dev/null | head -1 | cut -d'=' -f2- | tr -d '"' | tr -d "'" | xargs 2>/dev/null || true)
      if [ -n "$MAYBE" ]; then
        KEY="$MAYBE"
        echo "  (key from $env_path)"
        break
      fi
    fi
  done
fi

# ── 3. .claude/settings.local.json ────────────────────────────────────────────
if [ -z "$KEY" ]; then
  REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo "$PWD")"
  LOCAL_CFG="$REPO_ROOT/.claude/settings.local.json"
  if [ -f "$LOCAL_CFG" ]; then
    MAYBE=$(python3 -c "
import json, sys
try:
    d = json.load(open('$LOCAL_CFG'))
    print(d.get('env',{}).get('OPENROUTER_API_KEY',''))
except Exception:
    pass
" 2>/dev/null || true)
    if [ -n "$MAYBE" ] && [ "$MAYBE" != "YOUR_KEY_HERE" ]; then
      KEY="$MAYBE"
      echo "  (key from .claude/settings.local.json)"
    fi
  fi
fi

# ── 4. Fallback to secondary key ──────────────────────────────────────────────
if [ -z "$KEY" ]; then
  KEY="${OPENROUTER_API_KEY_2:-}"
  [ -n "$KEY" ] && echo "  (using OPENROUTER_API_KEY_2 as fallback)"
fi

# ── Write config ──────────────────────────────────────────────────────────────
if [ -n "$KEY" ]; then
  echo "✅  OpenRouter key found: ${KEY:0:8}..."
  PLACEHOLDER="__OR_KEY__"
else
  echo "⚠️  No OPENROUTER_API_KEY found."
  echo "    Add it to .env:  OPENROUTER_API_KEY=sk-or-..."
  echo "    Or to .claude/settings.local.json → env.OPENROUTER_API_KEY"
  echo "    Writing config with placeholder — re-run after adding the key."
  KEY="YOUR_OPENROUTER_API_KEY_HERE"
fi

# Write template first (no shell variable substitution issues)
cat > "$CODEX_CFG" << 'TOML'
# QuantEdge — Codex Desktop User Config (auto-generated by setup_codex.sh)
# Model: xAI Grok Build 0.1 via OpenRouter  — re-run setup_codex.sh to refresh.

model = "x-ai/grok-build-0.1"
model_provider = "openrouter"

[model_providers.openrouter]
name = "OpenRouter → xAI Grok Build 0.1"
base_url = "https://openrouter.ai/api/v1"
api_key = "__OR_KEY__"
wire_api = "chat"

[model_providers.openrouter.headers]
"HTTP-Referer" = "https://quantedge.ai"
"X-Title" = "QuantEdge"
TOML

# Safe substitution via Python (handles any special chars in the key)
python3 - "$KEY" "$CODEX_CFG" << 'PYEOF'
import sys
key, cfg_path = sys.argv[1], sys.argv[2]
content = open(cfg_path).read().replace("__OR_KEY__", key)
open(cfg_path, "w").write(content)
PYEOF

echo "✅  Codex configured → $CODEX_CFG"
echo "    Model: x-ai/grok-build-0.1 via OpenRouter"
echo "    Restart Codex Desktop to apply."
