#!/bin/bash
# Autonomous strategy researcher — runs every 4 hours.
#
# Reads experiments/research_queue.yaml, picks the next pending paper,
# spawns a Claude Code SDK session to implement the strategy according
# to backend/app/strategies/RESEARCHER_GUIDE.md, runs the test suite,
# and either commits to a feature branch + opens a PR, or reverts cleanly.
#
# Prereqs:
#   - CLAUDE_API_KEY exported in the environment
#   - gh CLI authenticated (for PR creation)
#   - python venv active with project deps installed
#   - working tree clean before each cycle
#
# Usage:
#   ./scripts/agents/researcher_loop.sh                    # loop forever, 4h cadence
#   ./scripts/agents/researcher_loop.sh --once             # single iteration (smoke test)
#   ./scripts/agents/researcher_loop.sh --interval 7200    # custom interval seconds
#
# Logs every cycle to experiments/research_log.jsonl.

set -u

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
QUEUE_FILE="${REPO_ROOT}/experiments/research_queue.yaml"
GUIDE_FILE="${REPO_ROOT}/backend/app/strategies/RESEARCHER_GUIDE.md"
LOG_FILE="${REPO_ROOT}/experiments/research_log.jsonl"
PICKER_SCRIPT="${REPO_ROOT}/scripts/agents/pick_next_paper.py"

INTERVAL_SECONDS=14400   # 4 hours
RUN_ONCE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --once)     RUN_ONCE=1; shift ;;
    --interval) INTERVAL_SECONDS="$2"; shift 2 ;;
    *)          echo "Unknown flag: $1"; exit 2 ;;
  esac
done

log_event() {
  local status="$1"
  local paper_id="$2"
  local message="$3"
  local ts
  ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf '{"ts":"%s","status":"%s","paper_id":"%s","message":%s}\n' \
    "$ts" "$status" "$paper_id" "$(printf '%s' "$message" | python -c 'import json,sys;print(json.dumps(sys.stdin.read()))')" \
    >> "$LOG_FILE"
}

run_cycle() {
  echo "[$(date)] === Researcher cycle starting ==="

  # Verify clean working tree before starting
  if [[ -n "$(git -C "$REPO_ROOT" status --porcelain)" ]]; then
    echo "Working tree is dirty. Skipping this cycle."
    log_event "skipped" "-" "working tree dirty"
    return 0
  fi

  echo "[$(date)] Picking next research target..."
  NEXT_PAPER="$(python "$PICKER_SCRIPT" 2>/dev/null || true)"

  if [[ -z "$NEXT_PAPER" ]]; then
    echo "Research queue empty or picker unavailable."
    log_event "queue_empty" "-" "no pending papers"
    return 0
  fi

  # Expected output format from picker: "<id>|<title>|<url>"
  PAPER_ID="$(echo "$NEXT_PAPER" | cut -d'|' -f1)"
  PAPER_TITLE="$(echo "$NEXT_PAPER" | cut -d'|' -f2)"
  PAPER_URL="$(echo "$NEXT_PAPER" | cut -d'|' -f3)"

  BRANCH_NAME="feature/research-${PAPER_ID}-$(date +%Y%m%d-%H%M)"
  echo "Implementing paper ${PAPER_ID}: ${PAPER_TITLE}"
  echo "Branch: ${BRANCH_NAME}"

  git -C "$REPO_ROOT" checkout -b "$BRANCH_NAME" || {
    log_event "error" "$PAPER_ID" "failed to create branch"
    return 1
  }

  PROMPT="Read ${GUIDE_FILE} in full, then implement the strategy described in: ${PAPER_TITLE} (${PAPER_URL}). \
Follow every item in the implementation checklist (section 3 of the guide). \
Place the strategy at backend/app/strategies/manual/<descriptive_name>.py. \
Add a unit test at backend/tests/strategies/test_<descriptive_name>.py. \
Cite the paper in the docstring. Use .shift(1) on every indicator to prevent look-ahead. \
Do NOT modify any existing strategy files. When finished, do not commit — the wrapper script will."

  if ! claude --headless --prompt "$PROMPT"; then
    echo "Claude session failed. Reverting."
    git -C "$REPO_ROOT" checkout -- .
    git -C "$REPO_ROOT" clean -fd
    git -C "$REPO_ROOT" checkout main
    git -C "$REPO_ROOT" branch -D "$BRANCH_NAME"
    log_event "claude_failed" "$PAPER_ID" "headless session returned nonzero"
    return 1
  fi

  echo "[$(date)] Running test suite..."
  if ! (cd "$REPO_ROOT/backend" && pytest tests/ -x -q); then
    echo "Tests failed. Reverting branch."
    git -C "$REPO_ROOT" reset --hard HEAD
    git -C "$REPO_ROOT" clean -fd
    git -C "$REPO_ROOT" checkout main
    git -C "$REPO_ROOT" branch -D "$BRANCH_NAME"
    log_event "tests_failed" "$PAPER_ID" "pytest failed; branch reverted"
    return 1
  fi

  if [[ -z "$(git -C "$REPO_ROOT" status --porcelain)" ]]; then
    echo "Claude produced no changes. Cleaning up."
    git -C "$REPO_ROOT" checkout main
    git -C "$REPO_ROOT" branch -D "$BRANCH_NAME"
    log_event "no_changes" "$PAPER_ID" "claude produced no diff"
    return 0
  fi

  echo "[$(date)] Tests passed. Committing and opening PR..."
  git -C "$REPO_ROOT" add -A
  git -C "$REPO_ROOT" commit -m "research: implement ${PAPER_TITLE} (paper ${PAPER_ID})

Auto-generated by researcher_loop.sh.
Source: ${PAPER_URL}
"

  git -C "$REPO_ROOT" push -u origin "$BRANCH_NAME"

  if command -v gh >/dev/null 2>&1; then
    gh pr create \
      --base main \
      --head "$BRANCH_NAME" \
      --title "research: ${PAPER_TITLE}" \
      --body "Automated implementation of paper ${PAPER_ID}.\n\nSource: ${PAPER_URL}\n\nReviewer checklist: see backend/app/strategies/RESEARCHER_GUIDE.md section 3."
  else
    echo "gh CLI not installed; skipping PR creation."
  fi

  # Mark the paper as implemented in the queue
  python "$PICKER_SCRIPT" --mark-implemented "$PAPER_ID" 2>/dev/null || true

  git -C "$REPO_ROOT" checkout main
  log_event "success" "$PAPER_ID" "PR opened on ${BRANCH_NAME}"
  echo "[$(date)] Cycle complete for paper ${PAPER_ID}."
}

main_loop() {
  while true; do
    run_cycle || echo "Cycle returned nonzero; continuing."
    if [[ "$RUN_ONCE" -eq 1 ]]; then
      echo "Single-iteration mode: exiting."
      break
    fi
    echo "[$(date)] Sleeping ${INTERVAL_SECONDS}s until next cycle..."
    sleep "$INTERVAL_SECONDS"
  done
}

main_loop
