"""SSM (State Space Model) training entry point. Mirrors train_lstm.py interface."""
from __future__ import annotations

import argparse
import asyncio
import json
from pathlib import Path

import pandas as pd
import torch
from torch.utils.data import DataLoader, TensorDataset

from app.ml.features.engineer import engineer_features, create_sequences, add_labels
from app.ml.models.ssm_model import SSMPredictor
from app.ml.training.trainer import ARTIFACTS_DIR, train_with_lightning
from app.utils.logging import logger


def _apply_confirmation_filter(df: pd.DataFrame, label_col: str = "label", window: int = 2) -> pd.DataFrame:
    """Apply a confirmation filter so that a signal is kept only if it appears consecutively.

    Args:
        df: DataFrame containing the label column.
        label_col: Name of the label column generated by ``add_labels``.
        window: Number of consecutive periods required for confirmation.

    Returns:
        DataFrame with filtered labels.
    """
    if label_col not in df.columns:
        logger.warning("Label column %s not found; skipping confirmation filter.", label_col)
        return df

    # Rolling sum of the label; keep only rows where the sum equals the window size
    rolled = df[label_col].rolling(window, min_periods=window).sum()
    df[label_col] = (rolled == window).astype(int)
    return df


def build_dataloaders(
    df: pd.DataFrame,
    seq_len: int = 60,
    batch_size: int = 256,
    train_frac: float = 0.7,
    val_frac: float = 0.15,
    entry_threshold: float = 0.003,
    confirmation_window: int = 2,
) -> tuple[DataLoader, DataLoader, DataLoader, int]:
    """Prepare PyTorch dataloaders for training, validation, and testing.

    The function engineers features, creates labels with a tighter entry threshold,
    applies a confirmation filter, and then builds sequence tensors.

    Args:
        df: Raw OHLCV dataframe.
        seq_len: Length of each input sequence.
        batch_size: Batch size for the DataLoaders.
        train_frac: Fraction of data used for training.
        val_frac: Fraction of data used for validation.
        entry_threshold: Threshold for label generation (tighter than default).
        confirmation_window: Number of consecutive signals required for entry.

    Returns:
        Tuple containing train, validation, test DataLoaders and the number of features.
    """
    df = engineer_features(df)
    df = add_labels(df, threshold=entry_threshold)
    df = _apply_confirmation_filter(df, label_col="label", window=confirmation_window)

    X, y = create_sequences(df, seq_len=seq_len)
    X_t = torch.tensor(X, dtype=torch.float32)
    y_t = torch.tensor(y, dtype=torch.float32)

    n = len(X_t)
    n_train = int(n * train_frac)
    n_val = int(n * val_frac)

    train_ds = TensorDataset(X_t[:n_train], y_t[:n_train])
    val_ds = TensorDataset(X_t[n_train : n_train + n_val], y_t[n_train : n_train + n_val])
    test_ds = TensorDataset(X_t[n_train + n_val :], y_t[n_train + n_val :])

    n_features = X_t.shape[2]

    return (
        DataLoader(train_ds, batch_size=batch_size, shuffle=True),
        DataLoader(val_ds, batch_size=batch_size, shuffle=False),
        DataLoader(test_ds, batch_size=batch_size, shuffle=False),
        n_features,
    )


async def train(
    ohlcv_df: pd.DataFrame,
    experiment_name: str = "ssm_default",
    d_model: int = 64,
    n_layers: int = 4,
    dropout: float = 0.1,
    seq_len: int = 60,
    max_epochs: int = 100,
    batch_size: int = 256,
    lr: float = 1e-3,
    entry_threshold: float = 0.003,
    confirmation_window: int = 2,
) -> dict:
    """Train the SSM predictor and persist the resulting model.

    Args:
        ohlcv_df: DataFrame with OHLCV data.
        experiment_name: Identifier for the experiment.
        d_model: Dimensionality of the model embeddings.
        n_layers: Number of transformer layers.
        dropout: Dropout probability.
        seq_len: Length of input sequences.
        max_epochs: Maximum training epochs.
        batch_size: Batch size for DataLoaders.
        lr: Learning rate.
        entry_threshold: Threshold used for label creation.
        confirmation_window: Confirmation window for entry signals.

    Returns:
        Dictionary containing training metrics and artifact path.
    """
    train_loader, val_loader, test_loader, n_features = build_dataloaders(
        ohlcv_df,
        seq_len=seq_len,
        batch_size=batch_size,
        entry_threshold=entry_threshold,
        confirmation_window=confirmation_window,
    )

    model = SSMPredictor(
        input_size=n_features,
        d_model=d_model,
        n_layers=n_layers,
        dropout=dropout,
    )

    results = train_with_lightning(
        model=model,
        train_loader=train_loader,
        val_loader=val_loader,
        experiment_name=experiment_name,
        max_epochs=max_epochs,
        lr=lr,
    )

    save_path = ARTIFACTS_DIR / experiment_name / "final_model.pt"
    save_path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(
        {
            "model_state_dict": model.state_dict(),
            "n_features": n_features,
            "d_model": d_model,
            "n_layers": n_layers,
            "dropout": dropout,
            "seq_len": seq_len,
            "experiment": experiment_name,
        },
        str(save_path),
    )

    results["artifact_path"] = str(save_path)
    logger.info("SSM training complete", **results)
    return results


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--csv", required=True, help="Path to OHLCV CSV with columns: open,high,low,close,volume")
    parser.add_argument("--name", default="ssm_run")
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--d-model", type=int, default=64)
    parser.add_argument("--n-layers", type=int, default=4)
    parser.add_argument("--entry-threshold", type=float, default=0.003, help="Threshold for label generation")
    parser.add_argument(
        "--confirmation-window",
        type=int,
        default=2,
        help="Number of consecutive signals required for entry confirmation",
    )
    args = parser.parse_args()

    df = pd.read_csv(args.csv, index_col=0, parse_dates=True)
    result = asyncio.run(
        train(
            df,
            experiment_name=args.name,
            max_epochs=args.epochs,
            d_model=args.d_model,
            n_layers=args.n_layers,
            entry_threshold=args.entry_threshold,
            confirmation_window=args.confirmation_window,
        )
    )
    print(json.dumps(result, indent=2))